// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package bowtie

import (
	"context"
	"reflect"

	"github.com/bowtieworks/pulumi-bowtie/sdk/go/bowtie/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Collection struct {
	pulumi.CustomResourceState

	// An optional description of the collection.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// The locations contained in this collection.
	Members CollectionMemberArrayOutput `pulumi:"members"`
	// The human readable name of the collection.
	Name pulumi.StringOutput `pulumi:"name"`
}

// NewCollection registers a new resource with the given unique name, arguments, and options.
func NewCollection(ctx *pulumi.Context,
	name string, args *CollectionArgs, opts ...pulumi.ResourceOption) (*Collection, error) {
	if args == nil {
		args = &CollectionArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Collection
	err := ctx.RegisterResource("bowtie:index/collection:Collection", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetCollection gets an existing Collection resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCollection(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *CollectionState, opts ...pulumi.ResourceOption) (*Collection, error) {
	var resource Collection
	err := ctx.ReadResource("bowtie:index/collection:Collection", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Collection resources.
type collectionState struct {
	// An optional description of the collection.
	Description *string `pulumi:"description"`
	// The locations contained in this collection.
	Members []CollectionMember `pulumi:"members"`
	// The human readable name of the collection.
	Name *string `pulumi:"name"`
}

type CollectionState struct {
	// An optional description of the collection.
	Description pulumi.StringPtrInput
	// The locations contained in this collection.
	Members CollectionMemberArrayInput
	// The human readable name of the collection.
	Name pulumi.StringPtrInput
}

func (CollectionState) ElementType() reflect.Type {
	return reflect.TypeOf((*collectionState)(nil)).Elem()
}

type collectionArgs struct {
	// An optional description of the collection.
	Description *string `pulumi:"description"`
	// The locations contained in this collection.
	Members []CollectionMember `pulumi:"members"`
	// The human readable name of the collection.
	Name *string `pulumi:"name"`
}

// The set of arguments for constructing a Collection resource.
type CollectionArgs struct {
	// An optional description of the collection.
	Description pulumi.StringPtrInput
	// The locations contained in this collection.
	Members CollectionMemberArrayInput
	// The human readable name of the collection.
	Name pulumi.StringPtrInput
}

func (CollectionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*collectionArgs)(nil)).Elem()
}

type CollectionInput interface {
	pulumi.Input

	ToCollectionOutput() CollectionOutput
	ToCollectionOutputWithContext(ctx context.Context) CollectionOutput
}

func (*Collection) ElementType() reflect.Type {
	return reflect.TypeOf((**Collection)(nil)).Elem()
}

func (i *Collection) ToCollectionOutput() CollectionOutput {
	return i.ToCollectionOutputWithContext(context.Background())
}

func (i *Collection) ToCollectionOutputWithContext(ctx context.Context) CollectionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CollectionOutput)
}

type CollectionOutput struct{ *pulumi.OutputState }

func (CollectionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Collection)(nil)).Elem()
}

func (o CollectionOutput) ToCollectionOutput() CollectionOutput {
	return o
}

func (o CollectionOutput) ToCollectionOutputWithContext(ctx context.Context) CollectionOutput {
	return o
}

// An optional description of the collection.
func (o CollectionOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Collection) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// The locations contained in this collection.
func (o CollectionOutput) Members() CollectionMemberArrayOutput {
	return o.ApplyT(func(v *Collection) CollectionMemberArrayOutput { return v.Members }).(CollectionMemberArrayOutput)
}

// The human readable name of the collection.
func (o CollectionOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Collection) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CollectionInput)(nil)).Elem(), &Collection{})
	pulumi.RegisterOutputType(CollectionOutput{})
}
