// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package bowtie

import (
	"context"
	"reflect"

	"github.com/bowtieworks/pulumi-bowtie/sdk/go/bowtie/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Controller struct {
	pulumi.CustomResourceState

	// Whether temporary console users may be created on this Controller.
	AllowTemporaryConsoleUsers pulumi.BoolOutput `pulumi:"allowTemporaryConsoleUsers"`
	// Whether this Controller may use the identity provider.
	CanUseIdp pulumi.BoolOutput `pulumi:"canUseIdp"`
	// Whether this Controller may serve public HTTPS.
	CanUsePublicHttps pulumi.BoolOutput `pulumi:"canUsePublicHttps"`
	// Whether this Controller may use a vanity domain.
	CanUseVanityDomain pulumi.BoolOutput `pulumi:"canUseVanityDomain"`
	// The software version the Controller is currently running.
	CurrentVersion pulumi.StringOutput `pulumi:"currentVersion"`
	// The Controller's HTTPS endpoint.
	HttpsEndpoint pulumi.StringOutput `pulumi:"httpsEndpoint"`
	LastUpdated   pulumi.StringOutput `pulumi:"lastUpdated"`
	// Keepalive interval, in seconds, advertised to peers.
	PersistentKeepalive pulumi.IntOutput `pulumi:"persistentKeepalive"`
	// The publicly reachable address clients and other Controllers use to reach this Controller.
	PublicAddress pulumi.StringOutput `pulumi:"publicAddress"`
	// The Controller's VPN public key.
	PublicKey pulumi.StringOutput `pulumi:"publicKey"`
	// The site this Controller belongs to.
	SiteId pulumi.StringOutput `pulumi:"siteId"`
	// Where the Controller accepts SSH: `any`, `local-only`, or `tunnel-only`.
	SshListener pulumi.StringOutput `pulumi:"sshListener"`
	// Emit per-packet policy verdict logs.
	TrackPolicyVerdictLogs pulumi.BoolOutput `pulumi:"trackPolicyVerdictLogs"`
	// Record per-packet policy verdict metrics.
	TrackPolicyVerdictMetrics pulumi.BoolOutput `pulumi:"trackPolicyVerdictMetrics"`
	// Consider pre-release versions when selecting updates. Unset falls back to the organization default.
	VersionIncludePrereleases pulumi.BoolOutput `pulumi:"versionIncludePrereleases"`
	// Minimum age, in days, a release must have before this Controller adopts it under a latest-version strategy. Unset falls
	// back to the organization default.
	VersionMinimumAge pulumi.IntOutput `pulumi:"versionMinimumAge"`
	// Spreads update times across a fleet. One of `no-delay`, `randomized-delay`, or `consistent-randomized-delay`.
	VersionStrategySplayType pulumi.StringOutput `pulumi:"versionStrategySplayType"`
	// A systemd time-span used by `randomized-delay` and `consistent-randomized-delay`.
	VersionStrategySplayValue pulumi.StringOutput `pulumi:"versionStrategySplayValue"`
	// How this Controller chooses update versions. One of `org-default`, `manual`, `specific`, `newest-at-interval`, or
	// `newest-at-calendar`. This is the upgrade orchestration control.
	VersionStrategyType pulumi.StringOutput `pulumi:"versionStrategyType"`
	// The value for `versionStrategyType` when it requires one: a version string for `specific`, a systemd time-span for
	// `newest-at-interval`, or a systemd calendar expression for `newest-at-calendar`. Leave unset for `org-default` and
	// `manual`.
	VersionStrategyValue pulumi.StringOutput `pulumi:"versionStrategyValue"`
	// A collection ID used as the web-filter trusted proxy list for this Controller.
	WebFilterTrustedProxyCollection pulumi.StringOutput `pulumi:"webFilterTrustedProxyCollection"`
	// The UDP port the Controller listens on for VPN connections.
	WireguardPort pulumi.IntOutput `pulumi:"wireguardPort"`
	// How the VPN port is reached: `static` (publicly reachable) or `dynamic` (privately reachable or NAT-punched).
	WireguardStrategy pulumi.StringOutput `pulumi:"wireguardStrategy"`
}

// NewController registers a new resource with the given unique name, arguments, and options.
func NewController(ctx *pulumi.Context,
	name string, args *ControllerArgs, opts ...pulumi.ResourceOption) (*Controller, error) {
	if args == nil {
		args = &ControllerArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Controller
	err := ctx.RegisterResource("bowtie:index/controller:Controller", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetController gets an existing Controller resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetController(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ControllerState, opts ...pulumi.ResourceOption) (*Controller, error) {
	var resource Controller
	err := ctx.ReadResource("bowtie:index/controller:Controller", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Controller resources.
type controllerState struct {
	// Whether temporary console users may be created on this Controller.
	AllowTemporaryConsoleUsers *bool `pulumi:"allowTemporaryConsoleUsers"`
	// Whether this Controller may use the identity provider.
	CanUseIdp *bool `pulumi:"canUseIdp"`
	// Whether this Controller may serve public HTTPS.
	CanUsePublicHttps *bool `pulumi:"canUsePublicHttps"`
	// Whether this Controller may use a vanity domain.
	CanUseVanityDomain *bool `pulumi:"canUseVanityDomain"`
	// The software version the Controller is currently running.
	CurrentVersion *string `pulumi:"currentVersion"`
	// The Controller's HTTPS endpoint.
	HttpsEndpoint *string `pulumi:"httpsEndpoint"`
	LastUpdated   *string `pulumi:"lastUpdated"`
	// Keepalive interval, in seconds, advertised to peers.
	PersistentKeepalive *int `pulumi:"persistentKeepalive"`
	// The publicly reachable address clients and other Controllers use to reach this Controller.
	PublicAddress *string `pulumi:"publicAddress"`
	// The Controller's VPN public key.
	PublicKey *string `pulumi:"publicKey"`
	// The site this Controller belongs to.
	SiteId *string `pulumi:"siteId"`
	// Where the Controller accepts SSH: `any`, `local-only`, or `tunnel-only`.
	SshListener *string `pulumi:"sshListener"`
	// Emit per-packet policy verdict logs.
	TrackPolicyVerdictLogs *bool `pulumi:"trackPolicyVerdictLogs"`
	// Record per-packet policy verdict metrics.
	TrackPolicyVerdictMetrics *bool `pulumi:"trackPolicyVerdictMetrics"`
	// Consider pre-release versions when selecting updates. Unset falls back to the organization default.
	VersionIncludePrereleases *bool `pulumi:"versionIncludePrereleases"`
	// Minimum age, in days, a release must have before this Controller adopts it under a latest-version strategy. Unset falls
	// back to the organization default.
	VersionMinimumAge *int `pulumi:"versionMinimumAge"`
	// Spreads update times across a fleet. One of `no-delay`, `randomized-delay`, or `consistent-randomized-delay`.
	VersionStrategySplayType *string `pulumi:"versionStrategySplayType"`
	// A systemd time-span used by `randomized-delay` and `consistent-randomized-delay`.
	VersionStrategySplayValue *string `pulumi:"versionStrategySplayValue"`
	// How this Controller chooses update versions. One of `org-default`, `manual`, `specific`, `newest-at-interval`, or
	// `newest-at-calendar`. This is the upgrade orchestration control.
	VersionStrategyType *string `pulumi:"versionStrategyType"`
	// The value for `versionStrategyType` when it requires one: a version string for `specific`, a systemd time-span for
	// `newest-at-interval`, or a systemd calendar expression for `newest-at-calendar`. Leave unset for `org-default` and
	// `manual`.
	VersionStrategyValue *string `pulumi:"versionStrategyValue"`
	// A collection ID used as the web-filter trusted proxy list for this Controller.
	WebFilterTrustedProxyCollection *string `pulumi:"webFilterTrustedProxyCollection"`
	// The UDP port the Controller listens on for VPN connections.
	WireguardPort *int `pulumi:"wireguardPort"`
	// How the VPN port is reached: `static` (publicly reachable) or `dynamic` (privately reachable or NAT-punched).
	WireguardStrategy *string `pulumi:"wireguardStrategy"`
}

type ControllerState struct {
	// Whether temporary console users may be created on this Controller.
	AllowTemporaryConsoleUsers pulumi.BoolPtrInput
	// Whether this Controller may use the identity provider.
	CanUseIdp pulumi.BoolPtrInput
	// Whether this Controller may serve public HTTPS.
	CanUsePublicHttps pulumi.BoolPtrInput
	// Whether this Controller may use a vanity domain.
	CanUseVanityDomain pulumi.BoolPtrInput
	// The software version the Controller is currently running.
	CurrentVersion pulumi.StringPtrInput
	// The Controller's HTTPS endpoint.
	HttpsEndpoint pulumi.StringPtrInput
	LastUpdated   pulumi.StringPtrInput
	// Keepalive interval, in seconds, advertised to peers.
	PersistentKeepalive pulumi.IntPtrInput
	// The publicly reachable address clients and other Controllers use to reach this Controller.
	PublicAddress pulumi.StringPtrInput
	// The Controller's VPN public key.
	PublicKey pulumi.StringPtrInput
	// The site this Controller belongs to.
	SiteId pulumi.StringPtrInput
	// Where the Controller accepts SSH: `any`, `local-only`, or `tunnel-only`.
	SshListener pulumi.StringPtrInput
	// Emit per-packet policy verdict logs.
	TrackPolicyVerdictLogs pulumi.BoolPtrInput
	// Record per-packet policy verdict metrics.
	TrackPolicyVerdictMetrics pulumi.BoolPtrInput
	// Consider pre-release versions when selecting updates. Unset falls back to the organization default.
	VersionIncludePrereleases pulumi.BoolPtrInput
	// Minimum age, in days, a release must have before this Controller adopts it under a latest-version strategy. Unset falls
	// back to the organization default.
	VersionMinimumAge pulumi.IntPtrInput
	// Spreads update times across a fleet. One of `no-delay`, `randomized-delay`, or `consistent-randomized-delay`.
	VersionStrategySplayType pulumi.StringPtrInput
	// A systemd time-span used by `randomized-delay` and `consistent-randomized-delay`.
	VersionStrategySplayValue pulumi.StringPtrInput
	// How this Controller chooses update versions. One of `org-default`, `manual`, `specific`, `newest-at-interval`, or
	// `newest-at-calendar`. This is the upgrade orchestration control.
	VersionStrategyType pulumi.StringPtrInput
	// The value for `versionStrategyType` when it requires one: a version string for `specific`, a systemd time-span for
	// `newest-at-interval`, or a systemd calendar expression for `newest-at-calendar`. Leave unset for `org-default` and
	// `manual`.
	VersionStrategyValue pulumi.StringPtrInput
	// A collection ID used as the web-filter trusted proxy list for this Controller.
	WebFilterTrustedProxyCollection pulumi.StringPtrInput
	// The UDP port the Controller listens on for VPN connections.
	WireguardPort pulumi.IntPtrInput
	// How the VPN port is reached: `static` (publicly reachable) or `dynamic` (privately reachable or NAT-punched).
	WireguardStrategy pulumi.StringPtrInput
}

func (ControllerState) ElementType() reflect.Type {
	return reflect.TypeOf((*controllerState)(nil)).Elem()
}

type controllerArgs struct {
	// Whether temporary console users may be created on this Controller.
	AllowTemporaryConsoleUsers *bool `pulumi:"allowTemporaryConsoleUsers"`
	// Whether this Controller may use the identity provider.
	CanUseIdp *bool `pulumi:"canUseIdp"`
	// Whether this Controller may serve public HTTPS.
	CanUsePublicHttps *bool `pulumi:"canUsePublicHttps"`
	// Whether this Controller may use a vanity domain.
	CanUseVanityDomain *bool `pulumi:"canUseVanityDomain"`
	// Keepalive interval, in seconds, advertised to peers.
	PersistentKeepalive *int `pulumi:"persistentKeepalive"`
	// The publicly reachable address clients and other Controllers use to reach this Controller.
	PublicAddress *string `pulumi:"publicAddress"`
	// The site this Controller belongs to.
	SiteId *string `pulumi:"siteId"`
	// Where the Controller accepts SSH: `any`, `local-only`, or `tunnel-only`.
	SshListener *string `pulumi:"sshListener"`
	// Emit per-packet policy verdict logs.
	TrackPolicyVerdictLogs *bool `pulumi:"trackPolicyVerdictLogs"`
	// Record per-packet policy verdict metrics.
	TrackPolicyVerdictMetrics *bool `pulumi:"trackPolicyVerdictMetrics"`
	// Consider pre-release versions when selecting updates. Unset falls back to the organization default.
	VersionIncludePrereleases *bool `pulumi:"versionIncludePrereleases"`
	// Minimum age, in days, a release must have before this Controller adopts it under a latest-version strategy. Unset falls
	// back to the organization default.
	VersionMinimumAge *int `pulumi:"versionMinimumAge"`
	// Spreads update times across a fleet. One of `no-delay`, `randomized-delay`, or `consistent-randomized-delay`.
	VersionStrategySplayType *string `pulumi:"versionStrategySplayType"`
	// A systemd time-span used by `randomized-delay` and `consistent-randomized-delay`.
	VersionStrategySplayValue *string `pulumi:"versionStrategySplayValue"`
	// How this Controller chooses update versions. One of `org-default`, `manual`, `specific`, `newest-at-interval`, or
	// `newest-at-calendar`. This is the upgrade orchestration control.
	VersionStrategyType *string `pulumi:"versionStrategyType"`
	// The value for `versionStrategyType` when it requires one: a version string for `specific`, a systemd time-span for
	// `newest-at-interval`, or a systemd calendar expression for `newest-at-calendar`. Leave unset for `org-default` and
	// `manual`.
	VersionStrategyValue *string `pulumi:"versionStrategyValue"`
	// A collection ID used as the web-filter trusted proxy list for this Controller.
	WebFilterTrustedProxyCollection *string `pulumi:"webFilterTrustedProxyCollection"`
	// The UDP port the Controller listens on for VPN connections.
	WireguardPort *int `pulumi:"wireguardPort"`
	// How the VPN port is reached: `static` (publicly reachable) or `dynamic` (privately reachable or NAT-punched).
	WireguardStrategy *string `pulumi:"wireguardStrategy"`
}

// The set of arguments for constructing a Controller resource.
type ControllerArgs struct {
	// Whether temporary console users may be created on this Controller.
	AllowTemporaryConsoleUsers pulumi.BoolPtrInput
	// Whether this Controller may use the identity provider.
	CanUseIdp pulumi.BoolPtrInput
	// Whether this Controller may serve public HTTPS.
	CanUsePublicHttps pulumi.BoolPtrInput
	// Whether this Controller may use a vanity domain.
	CanUseVanityDomain pulumi.BoolPtrInput
	// Keepalive interval, in seconds, advertised to peers.
	PersistentKeepalive pulumi.IntPtrInput
	// The publicly reachable address clients and other Controllers use to reach this Controller.
	PublicAddress pulumi.StringPtrInput
	// The site this Controller belongs to.
	SiteId pulumi.StringPtrInput
	// Where the Controller accepts SSH: `any`, `local-only`, or `tunnel-only`.
	SshListener pulumi.StringPtrInput
	// Emit per-packet policy verdict logs.
	TrackPolicyVerdictLogs pulumi.BoolPtrInput
	// Record per-packet policy verdict metrics.
	TrackPolicyVerdictMetrics pulumi.BoolPtrInput
	// Consider pre-release versions when selecting updates. Unset falls back to the organization default.
	VersionIncludePrereleases pulumi.BoolPtrInput
	// Minimum age, in days, a release must have before this Controller adopts it under a latest-version strategy. Unset falls
	// back to the organization default.
	VersionMinimumAge pulumi.IntPtrInput
	// Spreads update times across a fleet. One of `no-delay`, `randomized-delay`, or `consistent-randomized-delay`.
	VersionStrategySplayType pulumi.StringPtrInput
	// A systemd time-span used by `randomized-delay` and `consistent-randomized-delay`.
	VersionStrategySplayValue pulumi.StringPtrInput
	// How this Controller chooses update versions. One of `org-default`, `manual`, `specific`, `newest-at-interval`, or
	// `newest-at-calendar`. This is the upgrade orchestration control.
	VersionStrategyType pulumi.StringPtrInput
	// The value for `versionStrategyType` when it requires one: a version string for `specific`, a systemd time-span for
	// `newest-at-interval`, or a systemd calendar expression for `newest-at-calendar`. Leave unset for `org-default` and
	// `manual`.
	VersionStrategyValue pulumi.StringPtrInput
	// A collection ID used as the web-filter trusted proxy list for this Controller.
	WebFilterTrustedProxyCollection pulumi.StringPtrInput
	// The UDP port the Controller listens on for VPN connections.
	WireguardPort pulumi.IntPtrInput
	// How the VPN port is reached: `static` (publicly reachable) or `dynamic` (privately reachable or NAT-punched).
	WireguardStrategy pulumi.StringPtrInput
}

func (ControllerArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*controllerArgs)(nil)).Elem()
}

type ControllerInput interface {
	pulumi.Input

	ToControllerOutput() ControllerOutput
	ToControllerOutputWithContext(ctx context.Context) ControllerOutput
}

func (*Controller) ElementType() reflect.Type {
	return reflect.TypeOf((**Controller)(nil)).Elem()
}

func (i *Controller) ToControllerOutput() ControllerOutput {
	return i.ToControllerOutputWithContext(context.Background())
}

func (i *Controller) ToControllerOutputWithContext(ctx context.Context) ControllerOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ControllerOutput)
}

type ControllerOutput struct{ *pulumi.OutputState }

func (ControllerOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Controller)(nil)).Elem()
}

func (o ControllerOutput) ToControllerOutput() ControllerOutput {
	return o
}

func (o ControllerOutput) ToControllerOutputWithContext(ctx context.Context) ControllerOutput {
	return o
}

// Whether temporary console users may be created on this Controller.
func (o ControllerOutput) AllowTemporaryConsoleUsers() pulumi.BoolOutput {
	return o.ApplyT(func(v *Controller) pulumi.BoolOutput { return v.AllowTemporaryConsoleUsers }).(pulumi.BoolOutput)
}

// Whether this Controller may use the identity provider.
func (o ControllerOutput) CanUseIdp() pulumi.BoolOutput {
	return o.ApplyT(func(v *Controller) pulumi.BoolOutput { return v.CanUseIdp }).(pulumi.BoolOutput)
}

// Whether this Controller may serve public HTTPS.
func (o ControllerOutput) CanUsePublicHttps() pulumi.BoolOutput {
	return o.ApplyT(func(v *Controller) pulumi.BoolOutput { return v.CanUsePublicHttps }).(pulumi.BoolOutput)
}

// Whether this Controller may use a vanity domain.
func (o ControllerOutput) CanUseVanityDomain() pulumi.BoolOutput {
	return o.ApplyT(func(v *Controller) pulumi.BoolOutput { return v.CanUseVanityDomain }).(pulumi.BoolOutput)
}

// The software version the Controller is currently running.
func (o ControllerOutput) CurrentVersion() pulumi.StringOutput {
	return o.ApplyT(func(v *Controller) pulumi.StringOutput { return v.CurrentVersion }).(pulumi.StringOutput)
}

// The Controller's HTTPS endpoint.
func (o ControllerOutput) HttpsEndpoint() pulumi.StringOutput {
	return o.ApplyT(func(v *Controller) pulumi.StringOutput { return v.HttpsEndpoint }).(pulumi.StringOutput)
}

func (o ControllerOutput) LastUpdated() pulumi.StringOutput {
	return o.ApplyT(func(v *Controller) pulumi.StringOutput { return v.LastUpdated }).(pulumi.StringOutput)
}

// Keepalive interval, in seconds, advertised to peers.
func (o ControllerOutput) PersistentKeepalive() pulumi.IntOutput {
	return o.ApplyT(func(v *Controller) pulumi.IntOutput { return v.PersistentKeepalive }).(pulumi.IntOutput)
}

// The publicly reachable address clients and other Controllers use to reach this Controller.
func (o ControllerOutput) PublicAddress() pulumi.StringOutput {
	return o.ApplyT(func(v *Controller) pulumi.StringOutput { return v.PublicAddress }).(pulumi.StringOutput)
}

// The Controller's VPN public key.
func (o ControllerOutput) PublicKey() pulumi.StringOutput {
	return o.ApplyT(func(v *Controller) pulumi.StringOutput { return v.PublicKey }).(pulumi.StringOutput)
}

// The site this Controller belongs to.
func (o ControllerOutput) SiteId() pulumi.StringOutput {
	return o.ApplyT(func(v *Controller) pulumi.StringOutput { return v.SiteId }).(pulumi.StringOutput)
}

// Where the Controller accepts SSH: `any`, `local-only`, or `tunnel-only`.
func (o ControllerOutput) SshListener() pulumi.StringOutput {
	return o.ApplyT(func(v *Controller) pulumi.StringOutput { return v.SshListener }).(pulumi.StringOutput)
}

// Emit per-packet policy verdict logs.
func (o ControllerOutput) TrackPolicyVerdictLogs() pulumi.BoolOutput {
	return o.ApplyT(func(v *Controller) pulumi.BoolOutput { return v.TrackPolicyVerdictLogs }).(pulumi.BoolOutput)
}

// Record per-packet policy verdict metrics.
func (o ControllerOutput) TrackPolicyVerdictMetrics() pulumi.BoolOutput {
	return o.ApplyT(func(v *Controller) pulumi.BoolOutput { return v.TrackPolicyVerdictMetrics }).(pulumi.BoolOutput)
}

// Consider pre-release versions when selecting updates. Unset falls back to the organization default.
func (o ControllerOutput) VersionIncludePrereleases() pulumi.BoolOutput {
	return o.ApplyT(func(v *Controller) pulumi.BoolOutput { return v.VersionIncludePrereleases }).(pulumi.BoolOutput)
}

// Minimum age, in days, a release must have before this Controller adopts it under a latest-version strategy. Unset falls
// back to the organization default.
func (o ControllerOutput) VersionMinimumAge() pulumi.IntOutput {
	return o.ApplyT(func(v *Controller) pulumi.IntOutput { return v.VersionMinimumAge }).(pulumi.IntOutput)
}

// Spreads update times across a fleet. One of `no-delay`, `randomized-delay`, or `consistent-randomized-delay`.
func (o ControllerOutput) VersionStrategySplayType() pulumi.StringOutput {
	return o.ApplyT(func(v *Controller) pulumi.StringOutput { return v.VersionStrategySplayType }).(pulumi.StringOutput)
}

// A systemd time-span used by `randomized-delay` and `consistent-randomized-delay`.
func (o ControllerOutput) VersionStrategySplayValue() pulumi.StringOutput {
	return o.ApplyT(func(v *Controller) pulumi.StringOutput { return v.VersionStrategySplayValue }).(pulumi.StringOutput)
}

// How this Controller chooses update versions. One of `org-default`, `manual`, `specific`, `newest-at-interval`, or
// `newest-at-calendar`. This is the upgrade orchestration control.
func (o ControllerOutput) VersionStrategyType() pulumi.StringOutput {
	return o.ApplyT(func(v *Controller) pulumi.StringOutput { return v.VersionStrategyType }).(pulumi.StringOutput)
}

// The value for `versionStrategyType` when it requires one: a version string for `specific`, a systemd time-span for
// `newest-at-interval`, or a systemd calendar expression for `newest-at-calendar`. Leave unset for `org-default` and
// `manual`.
func (o ControllerOutput) VersionStrategyValue() pulumi.StringOutput {
	return o.ApplyT(func(v *Controller) pulumi.StringOutput { return v.VersionStrategyValue }).(pulumi.StringOutput)
}

// A collection ID used as the web-filter trusted proxy list for this Controller.
func (o ControllerOutput) WebFilterTrustedProxyCollection() pulumi.StringOutput {
	return o.ApplyT(func(v *Controller) pulumi.StringOutput { return v.WebFilterTrustedProxyCollection }).(pulumi.StringOutput)
}

// The UDP port the Controller listens on for VPN connections.
func (o ControllerOutput) WireguardPort() pulumi.IntOutput {
	return o.ApplyT(func(v *Controller) pulumi.IntOutput { return v.WireguardPort }).(pulumi.IntOutput)
}

// How the VPN port is reached: `static` (publicly reachable) or `dynamic` (privately reachable or NAT-punched).
func (o ControllerOutput) WireguardStrategy() pulumi.StringOutput {
	return o.ApplyT(func(v *Controller) pulumi.StringOutput { return v.WireguardStrategy }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ControllerInput)(nil)).Elem(), &Controller{})
	pulumi.RegisterOutputType(ControllerOutput{})
}
