// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package bowtie

import (
	"context"
	"reflect"

	"errors"
	"github.com/bowtieworks/pulumi-bowtie/sdk/go/bowtie/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Dns struct {
	pulumi.CustomResourceState

	// Names under this domain to exclude from resolution.
	Excludes DnsExcludeArrayOutput `pulumi:"excludes"`
	// Limit name resolution for this domain only to these sites.
	IncludeOnlySites pulumi.StringArrayOutput `pulumi:"includeOnlySites"`
	// Whether to only log metrics for this domain and not all requests.
	IsCounted pulumi.BoolOutput `pulumi:"isCounted"`
	// Whether to resolve names using DNS64.
	IsDns64 pulumi.BoolOutput `pulumi:"isDns64"`
	// Whether to drop A record responses from requests for this domain.
	IsDropA pulumi.BoolOutput `pulumi:"isDropA"`
	// Whether all record responses for this domain should be dropped.
	IsDropAll pulumi.BoolOutput `pulumi:"isDropAll"`
	// Whether to log all requests for names in this domain.
	IsLog pulumi.BoolOutput `pulumi:"isLog"`
	// Whether this domain should be treated as a search domain.
	IsSearchDomain pulumi.BoolOutput `pulumi:"isSearchDomain"`
	// Metadata about the last time a write API was called by this provider for this resource.
	LastUpdated pulumi.StringOutput `pulumi:"lastUpdated"`
	// The DNS zone name you wish to target. Example: `example.com`
	Name pulumi.StringOutput `pulumi:"name"`
	// Provider Metadata storing extra API data about the upstream servers for this domain
	Servers DnsServerArrayOutput `pulumi:"servers"`
}

// NewDns registers a new resource with the given unique name, arguments, and options.
func NewDns(ctx *pulumi.Context,
	name string, args *DnsArgs, opts ...pulumi.ResourceOption) (*Dns, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Servers == nil {
		return nil, errors.New("invalid value for required argument 'Servers'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Dns
	err := ctx.RegisterResource("bowtie:index/dns:Dns", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDns gets an existing Dns resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDns(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DnsState, opts ...pulumi.ResourceOption) (*Dns, error) {
	var resource Dns
	err := ctx.ReadResource("bowtie:index/dns:Dns", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Dns resources.
type dnsState struct {
	// Names under this domain to exclude from resolution.
	Excludes []DnsExclude `pulumi:"excludes"`
	// Limit name resolution for this domain only to these sites.
	IncludeOnlySites []string `pulumi:"includeOnlySites"`
	// Whether to only log metrics for this domain and not all requests.
	IsCounted *bool `pulumi:"isCounted"`
	// Whether to resolve names using DNS64.
	IsDns64 *bool `pulumi:"isDns64"`
	// Whether to drop A record responses from requests for this domain.
	IsDropA *bool `pulumi:"isDropA"`
	// Whether all record responses for this domain should be dropped.
	IsDropAll *bool `pulumi:"isDropAll"`
	// Whether to log all requests for names in this domain.
	IsLog *bool `pulumi:"isLog"`
	// Whether this domain should be treated as a search domain.
	IsSearchDomain *bool `pulumi:"isSearchDomain"`
	// Metadata about the last time a write API was called by this provider for this resource.
	LastUpdated *string `pulumi:"lastUpdated"`
	// The DNS zone name you wish to target. Example: `example.com`
	Name *string `pulumi:"name"`
	// Provider Metadata storing extra API data about the upstream servers for this domain
	Servers []DnsServer `pulumi:"servers"`
}

type DnsState struct {
	// Names under this domain to exclude from resolution.
	Excludes DnsExcludeArrayInput
	// Limit name resolution for this domain only to these sites.
	IncludeOnlySites pulumi.StringArrayInput
	// Whether to only log metrics for this domain and not all requests.
	IsCounted pulumi.BoolPtrInput
	// Whether to resolve names using DNS64.
	IsDns64 pulumi.BoolPtrInput
	// Whether to drop A record responses from requests for this domain.
	IsDropA pulumi.BoolPtrInput
	// Whether all record responses for this domain should be dropped.
	IsDropAll pulumi.BoolPtrInput
	// Whether to log all requests for names in this domain.
	IsLog pulumi.BoolPtrInput
	// Whether this domain should be treated as a search domain.
	IsSearchDomain pulumi.BoolPtrInput
	// Metadata about the last time a write API was called by this provider for this resource.
	LastUpdated pulumi.StringPtrInput
	// The DNS zone name you wish to target. Example: `example.com`
	Name pulumi.StringPtrInput
	// Provider Metadata storing extra API data about the upstream servers for this domain
	Servers DnsServerArrayInput
}

func (DnsState) ElementType() reflect.Type {
	return reflect.TypeOf((*dnsState)(nil)).Elem()
}

type dnsArgs struct {
	// Names under this domain to exclude from resolution.
	Excludes []DnsExclude `pulumi:"excludes"`
	// Limit name resolution for this domain only to these sites.
	IncludeOnlySites []string `pulumi:"includeOnlySites"`
	// Whether to only log metrics for this domain and not all requests.
	IsCounted *bool `pulumi:"isCounted"`
	// Whether to resolve names using DNS64.
	IsDns64 *bool `pulumi:"isDns64"`
	// Whether to drop A record responses from requests for this domain.
	IsDropA *bool `pulumi:"isDropA"`
	// Whether all record responses for this domain should be dropped.
	IsDropAll *bool `pulumi:"isDropAll"`
	// Whether to log all requests for names in this domain.
	IsLog *bool `pulumi:"isLog"`
	// Whether this domain should be treated as a search domain.
	IsSearchDomain *bool `pulumi:"isSearchDomain"`
	// The DNS zone name you wish to target. Example: `example.com`
	Name *string `pulumi:"name"`
	// Provider Metadata storing extra API data about the upstream servers for this domain
	Servers []DnsServer `pulumi:"servers"`
}

// The set of arguments for constructing a Dns resource.
type DnsArgs struct {
	// Names under this domain to exclude from resolution.
	Excludes DnsExcludeArrayInput
	// Limit name resolution for this domain only to these sites.
	IncludeOnlySites pulumi.StringArrayInput
	// Whether to only log metrics for this domain and not all requests.
	IsCounted pulumi.BoolPtrInput
	// Whether to resolve names using DNS64.
	IsDns64 pulumi.BoolPtrInput
	// Whether to drop A record responses from requests for this domain.
	IsDropA pulumi.BoolPtrInput
	// Whether all record responses for this domain should be dropped.
	IsDropAll pulumi.BoolPtrInput
	// Whether to log all requests for names in this domain.
	IsLog pulumi.BoolPtrInput
	// Whether this domain should be treated as a search domain.
	IsSearchDomain pulumi.BoolPtrInput
	// The DNS zone name you wish to target. Example: `example.com`
	Name pulumi.StringPtrInput
	// Provider Metadata storing extra API data about the upstream servers for this domain
	Servers DnsServerArrayInput
}

func (DnsArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*dnsArgs)(nil)).Elem()
}

type DnsInput interface {
	pulumi.Input

	ToDnsOutput() DnsOutput
	ToDnsOutputWithContext(ctx context.Context) DnsOutput
}

func (*Dns) ElementType() reflect.Type {
	return reflect.TypeOf((**Dns)(nil)).Elem()
}

func (i *Dns) ToDnsOutput() DnsOutput {
	return i.ToDnsOutputWithContext(context.Background())
}

func (i *Dns) ToDnsOutputWithContext(ctx context.Context) DnsOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DnsOutput)
}

type DnsOutput struct{ *pulumi.OutputState }

func (DnsOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Dns)(nil)).Elem()
}

func (o DnsOutput) ToDnsOutput() DnsOutput {
	return o
}

func (o DnsOutput) ToDnsOutputWithContext(ctx context.Context) DnsOutput {
	return o
}

// Names under this domain to exclude from resolution.
func (o DnsOutput) Excludes() DnsExcludeArrayOutput {
	return o.ApplyT(func(v *Dns) DnsExcludeArrayOutput { return v.Excludes }).(DnsExcludeArrayOutput)
}

// Limit name resolution for this domain only to these sites.
func (o DnsOutput) IncludeOnlySites() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Dns) pulumi.StringArrayOutput { return v.IncludeOnlySites }).(pulumi.StringArrayOutput)
}

// Whether to only log metrics for this domain and not all requests.
func (o DnsOutput) IsCounted() pulumi.BoolOutput {
	return o.ApplyT(func(v *Dns) pulumi.BoolOutput { return v.IsCounted }).(pulumi.BoolOutput)
}

// Whether to resolve names using DNS64.
func (o DnsOutput) IsDns64() pulumi.BoolOutput {
	return o.ApplyT(func(v *Dns) pulumi.BoolOutput { return v.IsDns64 }).(pulumi.BoolOutput)
}

// Whether to drop A record responses from requests for this domain.
func (o DnsOutput) IsDropA() pulumi.BoolOutput {
	return o.ApplyT(func(v *Dns) pulumi.BoolOutput { return v.IsDropA }).(pulumi.BoolOutput)
}

// Whether all record responses for this domain should be dropped.
func (o DnsOutput) IsDropAll() pulumi.BoolOutput {
	return o.ApplyT(func(v *Dns) pulumi.BoolOutput { return v.IsDropAll }).(pulumi.BoolOutput)
}

// Whether to log all requests for names in this domain.
func (o DnsOutput) IsLog() pulumi.BoolOutput {
	return o.ApplyT(func(v *Dns) pulumi.BoolOutput { return v.IsLog }).(pulumi.BoolOutput)
}

// Whether this domain should be treated as a search domain.
func (o DnsOutput) IsSearchDomain() pulumi.BoolOutput {
	return o.ApplyT(func(v *Dns) pulumi.BoolOutput { return v.IsSearchDomain }).(pulumi.BoolOutput)
}

// Metadata about the last time a write API was called by this provider for this resource.
func (o DnsOutput) LastUpdated() pulumi.StringOutput {
	return o.ApplyT(func(v *Dns) pulumi.StringOutput { return v.LastUpdated }).(pulumi.StringOutput)
}

// The DNS zone name you wish to target. Example: `example.com`
func (o DnsOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Dns) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Provider Metadata storing extra API data about the upstream servers for this domain
func (o DnsOutput) Servers() DnsServerArrayOutput {
	return o.ApplyT(func(v *Dns) DnsServerArrayOutput { return v.Servers }).(DnsServerArrayOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DnsInput)(nil)).Elem(), &Dns{})
	pulumi.RegisterOutputType(DnsOutput{})
}
