// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package bowtie

import (
	"context"
	"reflect"

	"github.com/bowtieworks/pulumi-bowtie/sdk/go/bowtie/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type DnsBlockList struct {
	pulumi.CustomResourceState

	LastUpdated pulumi.StringOutput `pulumi:"lastUpdated"`
	// The human readable name of the block list.
	Name pulumi.StringOutput `pulumi:"name"`
	// Optional list of DNS names to exclude from any retrieved DNS block lists.
	OverrideToAllows pulumi.StringArrayOutput `pulumi:"overrideToAllows"`
	// An upstream URL that returns a DNS block list.
	Upstream pulumi.StringPtrOutput `pulumi:"upstream"`
}

// NewDnsBlockList registers a new resource with the given unique name, arguments, and options.
func NewDnsBlockList(ctx *pulumi.Context,
	name string, args *DnsBlockListArgs, opts ...pulumi.ResourceOption) (*DnsBlockList, error) {
	if args == nil {
		args = &DnsBlockListArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource DnsBlockList
	err := ctx.RegisterResource("bowtie:index/dnsBlockList:DnsBlockList", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDnsBlockList gets an existing DnsBlockList resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDnsBlockList(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DnsBlockListState, opts ...pulumi.ResourceOption) (*DnsBlockList, error) {
	var resource DnsBlockList
	err := ctx.ReadResource("bowtie:index/dnsBlockList:DnsBlockList", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DnsBlockList resources.
type dnsBlockListState struct {
	LastUpdated *string `pulumi:"lastUpdated"`
	// The human readable name of the block list.
	Name *string `pulumi:"name"`
	// Optional list of DNS names to exclude from any retrieved DNS block lists.
	OverrideToAllows []string `pulumi:"overrideToAllows"`
	// An upstream URL that returns a DNS block list.
	Upstream *string `pulumi:"upstream"`
}

type DnsBlockListState struct {
	LastUpdated pulumi.StringPtrInput
	// The human readable name of the block list.
	Name pulumi.StringPtrInput
	// Optional list of DNS names to exclude from any retrieved DNS block lists.
	OverrideToAllows pulumi.StringArrayInput
	// An upstream URL that returns a DNS block list.
	Upstream pulumi.StringPtrInput
}

func (DnsBlockListState) ElementType() reflect.Type {
	return reflect.TypeOf((*dnsBlockListState)(nil)).Elem()
}

type dnsBlockListArgs struct {
	// The human readable name of the block list.
	Name *string `pulumi:"name"`
	// Optional list of DNS names to exclude from any retrieved DNS block lists.
	OverrideToAllows []string `pulumi:"overrideToAllows"`
	// An upstream URL that returns a DNS block list.
	Upstream *string `pulumi:"upstream"`
}

// The set of arguments for constructing a DnsBlockList resource.
type DnsBlockListArgs struct {
	// The human readable name of the block list.
	Name pulumi.StringPtrInput
	// Optional list of DNS names to exclude from any retrieved DNS block lists.
	OverrideToAllows pulumi.StringArrayInput
	// An upstream URL that returns a DNS block list.
	Upstream pulumi.StringPtrInput
}

func (DnsBlockListArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*dnsBlockListArgs)(nil)).Elem()
}

type DnsBlockListInput interface {
	pulumi.Input

	ToDnsBlockListOutput() DnsBlockListOutput
	ToDnsBlockListOutputWithContext(ctx context.Context) DnsBlockListOutput
}

func (*DnsBlockList) ElementType() reflect.Type {
	return reflect.TypeOf((**DnsBlockList)(nil)).Elem()
}

func (i *DnsBlockList) ToDnsBlockListOutput() DnsBlockListOutput {
	return i.ToDnsBlockListOutputWithContext(context.Background())
}

func (i *DnsBlockList) ToDnsBlockListOutputWithContext(ctx context.Context) DnsBlockListOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DnsBlockListOutput)
}

type DnsBlockListOutput struct{ *pulumi.OutputState }

func (DnsBlockListOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DnsBlockList)(nil)).Elem()
}

func (o DnsBlockListOutput) ToDnsBlockListOutput() DnsBlockListOutput {
	return o
}

func (o DnsBlockListOutput) ToDnsBlockListOutputWithContext(ctx context.Context) DnsBlockListOutput {
	return o
}

func (o DnsBlockListOutput) LastUpdated() pulumi.StringOutput {
	return o.ApplyT(func(v *DnsBlockList) pulumi.StringOutput { return v.LastUpdated }).(pulumi.StringOutput)
}

// The human readable name of the block list.
func (o DnsBlockListOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *DnsBlockList) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Optional list of DNS names to exclude from any retrieved DNS block lists.
func (o DnsBlockListOutput) OverrideToAllows() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *DnsBlockList) pulumi.StringArrayOutput { return v.OverrideToAllows }).(pulumi.StringArrayOutput)
}

// An upstream URL that returns a DNS block list.
func (o DnsBlockListOutput) Upstream() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *DnsBlockList) pulumi.StringPtrOutput { return v.Upstream }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DnsBlockListInput)(nil)).Elem(), &DnsBlockList{})
	pulumi.RegisterOutputType(DnsBlockListOutput{})
}
