// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package bowtie

import (
	"context"
	"reflect"

	"github.com/bowtieworks/pulumi-bowtie/sdk/go/bowtie/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetDevice(ctx *pulumi.Context, args *GetDeviceArgs, opts ...pulumi.InvokeOption) (*GetDeviceResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetDeviceResult
	err := ctx.Invoke("bowtie:index/getDevice:getDevice", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getDevice.
type GetDeviceArgs struct {
	Id string `pulumi:"id"`
}

// A collection of values returned by getDevice.
type GetDeviceResult struct {
	AssignedToUser  string `pulumi:"assignedToUser"`
	ControllerId    string `pulumi:"controllerId"`
	DeviceOs        string `pulumi:"deviceOs"`
	DeviceType      string `pulumi:"deviceType"`
	Id              string `pulumi:"id"`
	Ipv6            string `pulumi:"ipv6"`
	LastSeen        string `pulumi:"lastSeen"`
	LastSeenVersion string `pulumi:"lastSeenVersion"`
	Name            string `pulumi:"name"`
	PublicKey       string `pulumi:"publicKey"`
	Serial          string `pulumi:"serial"`
	State           string `pulumi:"state"`
}

func GetDeviceOutput(ctx *pulumi.Context, args GetDeviceOutputArgs, opts ...pulumi.InvokeOption) GetDeviceResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetDeviceResultOutput, error) {
			args := v.(GetDeviceArgs)
			opts = internal.PkgInvokeDefaultOpts(opts)
			var rv GetDeviceResult
			secret, err := ctx.InvokePackageRaw("bowtie:index/getDevice:getDevice", args, &rv, "", opts...)
			if err != nil {
				return GetDeviceResultOutput{}, err
			}

			output := pulumi.ToOutput(rv).(GetDeviceResultOutput)
			if secret {
				return pulumi.ToSecret(output).(GetDeviceResultOutput), nil
			}
			return output, nil
		}).(GetDeviceResultOutput)
}

// A collection of arguments for invoking getDevice.
type GetDeviceOutputArgs struct {
	Id pulumi.StringInput `pulumi:"id"`
}

func (GetDeviceOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDeviceArgs)(nil)).Elem()
}

// A collection of values returned by getDevice.
type GetDeviceResultOutput struct{ *pulumi.OutputState }

func (GetDeviceResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDeviceResult)(nil)).Elem()
}

func (o GetDeviceResultOutput) ToGetDeviceResultOutput() GetDeviceResultOutput {
	return o
}

func (o GetDeviceResultOutput) ToGetDeviceResultOutputWithContext(ctx context.Context) GetDeviceResultOutput {
	return o
}

func (o GetDeviceResultOutput) AssignedToUser() pulumi.StringOutput {
	return o.ApplyT(func(v GetDeviceResult) string { return v.AssignedToUser }).(pulumi.StringOutput)
}

func (o GetDeviceResultOutput) ControllerId() pulumi.StringOutput {
	return o.ApplyT(func(v GetDeviceResult) string { return v.ControllerId }).(pulumi.StringOutput)
}

func (o GetDeviceResultOutput) DeviceOs() pulumi.StringOutput {
	return o.ApplyT(func(v GetDeviceResult) string { return v.DeviceOs }).(pulumi.StringOutput)
}

func (o GetDeviceResultOutput) DeviceType() pulumi.StringOutput {
	return o.ApplyT(func(v GetDeviceResult) string { return v.DeviceType }).(pulumi.StringOutput)
}

func (o GetDeviceResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetDeviceResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetDeviceResultOutput) Ipv6() pulumi.StringOutput {
	return o.ApplyT(func(v GetDeviceResult) string { return v.Ipv6 }).(pulumi.StringOutput)
}

func (o GetDeviceResultOutput) LastSeen() pulumi.StringOutput {
	return o.ApplyT(func(v GetDeviceResult) string { return v.LastSeen }).(pulumi.StringOutput)
}

func (o GetDeviceResultOutput) LastSeenVersion() pulumi.StringOutput {
	return o.ApplyT(func(v GetDeviceResult) string { return v.LastSeenVersion }).(pulumi.StringOutput)
}

func (o GetDeviceResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v GetDeviceResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o GetDeviceResultOutput) PublicKey() pulumi.StringOutput {
	return o.ApplyT(func(v GetDeviceResult) string { return v.PublicKey }).(pulumi.StringOutput)
}

func (o GetDeviceResultOutput) Serial() pulumi.StringOutput {
	return o.ApplyT(func(v GetDeviceResult) string { return v.Serial }).(pulumi.StringOutput)
}

func (o GetDeviceResultOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v GetDeviceResult) string { return v.State }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetDeviceResultOutput{})
}
