// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package bowtie

import (
	"context"
	"reflect"

	"github.com/bowtieworks/pulumi-bowtie/sdk/go/bowtie/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupDeviceGroup(ctx *pulumi.Context, args *LookupDeviceGroupArgs, opts ...pulumi.InvokeOption) (*LookupDeviceGroupResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupDeviceGroupResult
	err := ctx.Invoke("bowtie:index/getDeviceGroup:getDeviceGroup", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getDeviceGroup.
type LookupDeviceGroupArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getDeviceGroup.
type LookupDeviceGroupResult struct {
	Description string `pulumi:"description"`
	Id          string `pulumi:"id"`
	Name        string `pulumi:"name"`
}

func LookupDeviceGroupOutput(ctx *pulumi.Context, args LookupDeviceGroupOutputArgs, opts ...pulumi.InvokeOption) LookupDeviceGroupResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupDeviceGroupResultOutput, error) {
			args := v.(LookupDeviceGroupArgs)
			opts = internal.PkgInvokeDefaultOpts(opts)
			var rv LookupDeviceGroupResult
			secret, err := ctx.InvokePackageRaw("bowtie:index/getDeviceGroup:getDeviceGroup", args, &rv, "", opts...)
			if err != nil {
				return LookupDeviceGroupResultOutput{}, err
			}

			output := pulumi.ToOutput(rv).(LookupDeviceGroupResultOutput)
			if secret {
				return pulumi.ToSecret(output).(LookupDeviceGroupResultOutput), nil
			}
			return output, nil
		}).(LookupDeviceGroupResultOutput)
}

// A collection of arguments for invoking getDeviceGroup.
type LookupDeviceGroupOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupDeviceGroupOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupDeviceGroupArgs)(nil)).Elem()
}

// A collection of values returned by getDeviceGroup.
type LookupDeviceGroupResultOutput struct{ *pulumi.OutputState }

func (LookupDeviceGroupResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupDeviceGroupResult)(nil)).Elem()
}

func (o LookupDeviceGroupResultOutput) ToLookupDeviceGroupResultOutput() LookupDeviceGroupResultOutput {
	return o
}

func (o LookupDeviceGroupResultOutput) ToLookupDeviceGroupResultOutputWithContext(ctx context.Context) LookupDeviceGroupResultOutput {
	return o
}

func (o LookupDeviceGroupResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDeviceGroupResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupDeviceGroupResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDeviceGroupResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupDeviceGroupResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDeviceGroupResult) string { return v.Name }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupDeviceGroupResultOutput{})
}
