// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package bowtie

import (
	"context"
	"reflect"

	"github.com/bowtieworks/pulumi-bowtie/sdk/go/bowtie/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupResourceGroup(ctx *pulumi.Context, args *LookupResourceGroupArgs, opts ...pulumi.InvokeOption) (*LookupResourceGroupResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupResourceGroupResult
	err := ctx.Invoke("bowtie:index/getResourceGroup:getResourceGroup", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getResourceGroup.
type LookupResourceGroupArgs struct {
	Name string `pulumi:"name"`
}

// A collection of values returned by getResourceGroup.
type LookupResourceGroupResult struct {
	Id         string   `pulumi:"id"`
	Inheriteds []string `pulumi:"inheriteds"`
	Name       string   `pulumi:"name"`
	Resources  []string `pulumi:"resources"`
}

func LookupResourceGroupOutput(ctx *pulumi.Context, args LookupResourceGroupOutputArgs, opts ...pulumi.InvokeOption) LookupResourceGroupResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupResourceGroupResultOutput, error) {
			args := v.(LookupResourceGroupArgs)
			opts = internal.PkgInvokeDefaultOpts(opts)
			var rv LookupResourceGroupResult
			secret, err := ctx.InvokePackageRaw("bowtie:index/getResourceGroup:getResourceGroup", args, &rv, "", opts...)
			if err != nil {
				return LookupResourceGroupResultOutput{}, err
			}

			output := pulumi.ToOutput(rv).(LookupResourceGroupResultOutput)
			if secret {
				return pulumi.ToSecret(output).(LookupResourceGroupResultOutput), nil
			}
			return output, nil
		}).(LookupResourceGroupResultOutput)
}

// A collection of arguments for invoking getResourceGroup.
type LookupResourceGroupOutputArgs struct {
	Name pulumi.StringInput `pulumi:"name"`
}

func (LookupResourceGroupOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupResourceGroupArgs)(nil)).Elem()
}

// A collection of values returned by getResourceGroup.
type LookupResourceGroupResultOutput struct{ *pulumi.OutputState }

func (LookupResourceGroupResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupResourceGroupResult)(nil)).Elem()
}

func (o LookupResourceGroupResultOutput) ToLookupResourceGroupResultOutput() LookupResourceGroupResultOutput {
	return o
}

func (o LookupResourceGroupResultOutput) ToLookupResourceGroupResultOutputWithContext(ctx context.Context) LookupResourceGroupResultOutput {
	return o
}

func (o LookupResourceGroupResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupResourceGroupResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupResourceGroupResultOutput) Inheriteds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupResourceGroupResult) []string { return v.Inheriteds }).(pulumi.StringArrayOutput)
}

func (o LookupResourceGroupResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupResourceGroupResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupResourceGroupResultOutput) Resources() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupResourceGroupResult) []string { return v.Resources }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupResourceGroupResultOutput{})
}
