// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package bowtie

import (
	"context"
	"reflect"

	"github.com/bowtieworks/pulumi-bowtie/sdk/go/bowtie/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func LookupUser(ctx *pulumi.Context, args *LookupUserArgs, opts ...pulumi.InvokeOption) (*LookupUserResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupUserResult
	err := ctx.Invoke("bowtie:index/getUser:getUser", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getUser.
type LookupUserArgs struct {
	Email string `pulumi:"email"`
}

// A collection of values returned by getUser.
type LookupUserResult struct {
	AuthzControlPlane bool   `pulumi:"authzControlPlane"`
	AuthzDevices      bool   `pulumi:"authzDevices"`
	AuthzPolicies     bool   `pulumi:"authzPolicies"`
	AuthzUsers        bool   `pulumi:"authzUsers"`
	Email             string `pulumi:"email"`
	Id                string `pulumi:"id"`
	Name              string `pulumi:"name"`
	Status            string `pulumi:"status"`
}

func LookupUserOutput(ctx *pulumi.Context, args LookupUserOutputArgs, opts ...pulumi.InvokeOption) LookupUserResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupUserResultOutput, error) {
			args := v.(LookupUserArgs)
			opts = internal.PkgInvokeDefaultOpts(opts)
			var rv LookupUserResult
			secret, err := ctx.InvokePackageRaw("bowtie:index/getUser:getUser", args, &rv, "", opts...)
			if err != nil {
				return LookupUserResultOutput{}, err
			}

			output := pulumi.ToOutput(rv).(LookupUserResultOutput)
			if secret {
				return pulumi.ToSecret(output).(LookupUserResultOutput), nil
			}
			return output, nil
		}).(LookupUserResultOutput)
}

// A collection of arguments for invoking getUser.
type LookupUserOutputArgs struct {
	Email pulumi.StringInput `pulumi:"email"`
}

func (LookupUserOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupUserArgs)(nil)).Elem()
}

// A collection of values returned by getUser.
type LookupUserResultOutput struct{ *pulumi.OutputState }

func (LookupUserResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupUserResult)(nil)).Elem()
}

func (o LookupUserResultOutput) ToLookupUserResultOutput() LookupUserResultOutput {
	return o
}

func (o LookupUserResultOutput) ToLookupUserResultOutputWithContext(ctx context.Context) LookupUserResultOutput {
	return o
}

func (o LookupUserResultOutput) AuthzControlPlane() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupUserResult) bool { return v.AuthzControlPlane }).(pulumi.BoolOutput)
}

func (o LookupUserResultOutput) AuthzDevices() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupUserResult) bool { return v.AuthzDevices }).(pulumi.BoolOutput)
}

func (o LookupUserResultOutput) AuthzPolicies() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupUserResult) bool { return v.AuthzPolicies }).(pulumi.BoolOutput)
}

func (o LookupUserResultOutput) AuthzUsers() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupUserResult) bool { return v.AuthzUsers }).(pulumi.BoolOutput)
}

func (o LookupUserResultOutput) Email() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUserResult) string { return v.Email }).(pulumi.StringOutput)
}

func (o LookupUserResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUserResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupUserResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUserResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupUserResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUserResult) string { return v.Status }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupUserResultOutput{})
}
