// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package bowtie

import (
	"context"
	"reflect"

	"github.com/bowtieworks/pulumi-bowtie/sdk/go/bowtie/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type OrgConfig struct {
	pulumi.CustomResourceState

	// Automatically admit a Controller that presents a valid pre-shared key, for zero-touch cluster scale-out.
	AllowControllerApprovalWithPskOnly pulumi.BoolOutput `pulumi:"allowControllerApprovalWithPskOnly"`
	// Automatically approve a device when its user authenticates after installing the client.
	AllowDeviceApprovalOnUserAuth pulumi.BoolOutput `pulumi:"allowDeviceApprovalOnUserAuth"`
	// Organization default for how Controllers listen on the SSH port: `any`, `local-only`, or `tunnel-only`.
	ControllerSshListener pulumi.StringOutput `pulumi:"controllerSshListener"`
	// Default for considering pre-release versions when Controllers do not specify their own value.
	ControllerVersionIncludePrereleases pulumi.BoolOutput `pulumi:"controllerVersionIncludePrereleases"`
	// Default minimum age, in days, a release must have before adoption under a latest-version strategy.
	ControllerVersionMinimumAge pulumi.IntOutput `pulumi:"controllerVersionMinimumAge"`
	// Organization default update stagger: `no-delay`, `randomized-delay`, or `consistent-randomized-delay`.
	ControllerVersionSplayType pulumi.StringOutput `pulumi:"controllerVersionSplayType"`
	// A systemd time-span for `randomized-delay` and `consistent-randomized-delay`.
	ControllerVersionSplayValue pulumi.StringOutput `pulumi:"controllerVersionSplayValue"`
	// Organization default update strategy: `manual`, `specific`, `newest-at-interval`, or `newest-at-calendar`.
	// (`org-default` is not valid here; the organization default cannot itself defer to the organization default.)
	ControllerVersionStrategyType pulumi.StringOutput `pulumi:"controllerVersionStrategyType"`
	// Value for the default update strategy when it requires one (a version, time-span, or calendar expression).
	ControllerVersionStrategyValue pulumi.StringOutput `pulumi:"controllerVersionStrategyValue"`
	// Delete devices that have not checked in for more than this many days. Must be greater than 7.
	DeleteDevicesMoreStaleThanDays pulumi.IntOutput `pulumi:"deleteDevicesMoreStaleThanDays"`
	// When false, destructive device cleanup only proceeds when a quorum of Controller peers is connected.
	DisablePeersRequireQuorum pulumi.BoolOutput   `pulumi:"disablePeersRequireQuorum"`
	LastUpdated               pulumi.StringOutput `pulumi:"lastUpdated"`
	// Percentage (0-100) of Controller peers required for quorum. Default 51.
	PeersRequireQuorumPercentage pulumi.IntOutput `pulumi:"peersRequireQuorumPercentage"`
	// Revoke approval for devices that have not checked in for more than this many days. Must be greater than 7.
	RemoveApprovalDevicesMoreStaleThanDays pulumi.IntOutput `pulumi:"removeApprovalDevicesMoreStaleThanDays"`
	// Disassociate a device from its user after this many minutes.
	UserDeviceDisassociationMinutes pulumi.IntOutput `pulumi:"userDeviceDisassociationMinutes"`
}

// NewOrgConfig registers a new resource with the given unique name, arguments, and options.
func NewOrgConfig(ctx *pulumi.Context,
	name string, args *OrgConfigArgs, opts ...pulumi.ResourceOption) (*OrgConfig, error) {
	if args == nil {
		args = &OrgConfigArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource OrgConfig
	err := ctx.RegisterResource("bowtie:index/orgConfig:OrgConfig", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetOrgConfig gets an existing OrgConfig resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetOrgConfig(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *OrgConfigState, opts ...pulumi.ResourceOption) (*OrgConfig, error) {
	var resource OrgConfig
	err := ctx.ReadResource("bowtie:index/orgConfig:OrgConfig", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering OrgConfig resources.
type orgConfigState struct {
	// Automatically admit a Controller that presents a valid pre-shared key, for zero-touch cluster scale-out.
	AllowControllerApprovalWithPskOnly *bool `pulumi:"allowControllerApprovalWithPskOnly"`
	// Automatically approve a device when its user authenticates after installing the client.
	AllowDeviceApprovalOnUserAuth *bool `pulumi:"allowDeviceApprovalOnUserAuth"`
	// Organization default for how Controllers listen on the SSH port: `any`, `local-only`, or `tunnel-only`.
	ControllerSshListener *string `pulumi:"controllerSshListener"`
	// Default for considering pre-release versions when Controllers do not specify their own value.
	ControllerVersionIncludePrereleases *bool `pulumi:"controllerVersionIncludePrereleases"`
	// Default minimum age, in days, a release must have before adoption under a latest-version strategy.
	ControllerVersionMinimumAge *int `pulumi:"controllerVersionMinimumAge"`
	// Organization default update stagger: `no-delay`, `randomized-delay`, or `consistent-randomized-delay`.
	ControllerVersionSplayType *string `pulumi:"controllerVersionSplayType"`
	// A systemd time-span for `randomized-delay` and `consistent-randomized-delay`.
	ControllerVersionSplayValue *string `pulumi:"controllerVersionSplayValue"`
	// Organization default update strategy: `manual`, `specific`, `newest-at-interval`, or `newest-at-calendar`.
	// (`org-default` is not valid here; the organization default cannot itself defer to the organization default.)
	ControllerVersionStrategyType *string `pulumi:"controllerVersionStrategyType"`
	// Value for the default update strategy when it requires one (a version, time-span, or calendar expression).
	ControllerVersionStrategyValue *string `pulumi:"controllerVersionStrategyValue"`
	// Delete devices that have not checked in for more than this many days. Must be greater than 7.
	DeleteDevicesMoreStaleThanDays *int `pulumi:"deleteDevicesMoreStaleThanDays"`
	// When false, destructive device cleanup only proceeds when a quorum of Controller peers is connected.
	DisablePeersRequireQuorum *bool   `pulumi:"disablePeersRequireQuorum"`
	LastUpdated               *string `pulumi:"lastUpdated"`
	// Percentage (0-100) of Controller peers required for quorum. Default 51.
	PeersRequireQuorumPercentage *int `pulumi:"peersRequireQuorumPercentage"`
	// Revoke approval for devices that have not checked in for more than this many days. Must be greater than 7.
	RemoveApprovalDevicesMoreStaleThanDays *int `pulumi:"removeApprovalDevicesMoreStaleThanDays"`
	// Disassociate a device from its user after this many minutes.
	UserDeviceDisassociationMinutes *int `pulumi:"userDeviceDisassociationMinutes"`
}

type OrgConfigState struct {
	// Automatically admit a Controller that presents a valid pre-shared key, for zero-touch cluster scale-out.
	AllowControllerApprovalWithPskOnly pulumi.BoolPtrInput
	// Automatically approve a device when its user authenticates after installing the client.
	AllowDeviceApprovalOnUserAuth pulumi.BoolPtrInput
	// Organization default for how Controllers listen on the SSH port: `any`, `local-only`, or `tunnel-only`.
	ControllerSshListener pulumi.StringPtrInput
	// Default for considering pre-release versions when Controllers do not specify their own value.
	ControllerVersionIncludePrereleases pulumi.BoolPtrInput
	// Default minimum age, in days, a release must have before adoption under a latest-version strategy.
	ControllerVersionMinimumAge pulumi.IntPtrInput
	// Organization default update stagger: `no-delay`, `randomized-delay`, or `consistent-randomized-delay`.
	ControllerVersionSplayType pulumi.StringPtrInput
	// A systemd time-span for `randomized-delay` and `consistent-randomized-delay`.
	ControllerVersionSplayValue pulumi.StringPtrInput
	// Organization default update strategy: `manual`, `specific`, `newest-at-interval`, or `newest-at-calendar`.
	// (`org-default` is not valid here; the organization default cannot itself defer to the organization default.)
	ControllerVersionStrategyType pulumi.StringPtrInput
	// Value for the default update strategy when it requires one (a version, time-span, or calendar expression).
	ControllerVersionStrategyValue pulumi.StringPtrInput
	// Delete devices that have not checked in for more than this many days. Must be greater than 7.
	DeleteDevicesMoreStaleThanDays pulumi.IntPtrInput
	// When false, destructive device cleanup only proceeds when a quorum of Controller peers is connected.
	DisablePeersRequireQuorum pulumi.BoolPtrInput
	LastUpdated               pulumi.StringPtrInput
	// Percentage (0-100) of Controller peers required for quorum. Default 51.
	PeersRequireQuorumPercentage pulumi.IntPtrInput
	// Revoke approval for devices that have not checked in for more than this many days. Must be greater than 7.
	RemoveApprovalDevicesMoreStaleThanDays pulumi.IntPtrInput
	// Disassociate a device from its user after this many minutes.
	UserDeviceDisassociationMinutes pulumi.IntPtrInput
}

func (OrgConfigState) ElementType() reflect.Type {
	return reflect.TypeOf((*orgConfigState)(nil)).Elem()
}

type orgConfigArgs struct {
	// Automatically admit a Controller that presents a valid pre-shared key, for zero-touch cluster scale-out.
	AllowControllerApprovalWithPskOnly *bool `pulumi:"allowControllerApprovalWithPskOnly"`
	// Automatically approve a device when its user authenticates after installing the client.
	AllowDeviceApprovalOnUserAuth *bool `pulumi:"allowDeviceApprovalOnUserAuth"`
	// Organization default for how Controllers listen on the SSH port: `any`, `local-only`, or `tunnel-only`.
	ControllerSshListener *string `pulumi:"controllerSshListener"`
	// Default for considering pre-release versions when Controllers do not specify their own value.
	ControllerVersionIncludePrereleases *bool `pulumi:"controllerVersionIncludePrereleases"`
	// Default minimum age, in days, a release must have before adoption under a latest-version strategy.
	ControllerVersionMinimumAge *int `pulumi:"controllerVersionMinimumAge"`
	// Organization default update stagger: `no-delay`, `randomized-delay`, or `consistent-randomized-delay`.
	ControllerVersionSplayType *string `pulumi:"controllerVersionSplayType"`
	// A systemd time-span for `randomized-delay` and `consistent-randomized-delay`.
	ControllerVersionSplayValue *string `pulumi:"controllerVersionSplayValue"`
	// Organization default update strategy: `manual`, `specific`, `newest-at-interval`, or `newest-at-calendar`.
	// (`org-default` is not valid here; the organization default cannot itself defer to the organization default.)
	ControllerVersionStrategyType *string `pulumi:"controllerVersionStrategyType"`
	// Value for the default update strategy when it requires one (a version, time-span, or calendar expression).
	ControllerVersionStrategyValue *string `pulumi:"controllerVersionStrategyValue"`
	// Delete devices that have not checked in for more than this many days. Must be greater than 7.
	DeleteDevicesMoreStaleThanDays *int `pulumi:"deleteDevicesMoreStaleThanDays"`
	// When false, destructive device cleanup only proceeds when a quorum of Controller peers is connected.
	DisablePeersRequireQuorum *bool `pulumi:"disablePeersRequireQuorum"`
	// Percentage (0-100) of Controller peers required for quorum. Default 51.
	PeersRequireQuorumPercentage *int `pulumi:"peersRequireQuorumPercentage"`
	// Revoke approval for devices that have not checked in for more than this many days. Must be greater than 7.
	RemoveApprovalDevicesMoreStaleThanDays *int `pulumi:"removeApprovalDevicesMoreStaleThanDays"`
	// Disassociate a device from its user after this many minutes.
	UserDeviceDisassociationMinutes *int `pulumi:"userDeviceDisassociationMinutes"`
}

// The set of arguments for constructing a OrgConfig resource.
type OrgConfigArgs struct {
	// Automatically admit a Controller that presents a valid pre-shared key, for zero-touch cluster scale-out.
	AllowControllerApprovalWithPskOnly pulumi.BoolPtrInput
	// Automatically approve a device when its user authenticates after installing the client.
	AllowDeviceApprovalOnUserAuth pulumi.BoolPtrInput
	// Organization default for how Controllers listen on the SSH port: `any`, `local-only`, or `tunnel-only`.
	ControllerSshListener pulumi.StringPtrInput
	// Default for considering pre-release versions when Controllers do not specify their own value.
	ControllerVersionIncludePrereleases pulumi.BoolPtrInput
	// Default minimum age, in days, a release must have before adoption under a latest-version strategy.
	ControllerVersionMinimumAge pulumi.IntPtrInput
	// Organization default update stagger: `no-delay`, `randomized-delay`, or `consistent-randomized-delay`.
	ControllerVersionSplayType pulumi.StringPtrInput
	// A systemd time-span for `randomized-delay` and `consistent-randomized-delay`.
	ControllerVersionSplayValue pulumi.StringPtrInput
	// Organization default update strategy: `manual`, `specific`, `newest-at-interval`, or `newest-at-calendar`.
	// (`org-default` is not valid here; the organization default cannot itself defer to the organization default.)
	ControllerVersionStrategyType pulumi.StringPtrInput
	// Value for the default update strategy when it requires one (a version, time-span, or calendar expression).
	ControllerVersionStrategyValue pulumi.StringPtrInput
	// Delete devices that have not checked in for more than this many days. Must be greater than 7.
	DeleteDevicesMoreStaleThanDays pulumi.IntPtrInput
	// When false, destructive device cleanup only proceeds when a quorum of Controller peers is connected.
	DisablePeersRequireQuorum pulumi.BoolPtrInput
	// Percentage (0-100) of Controller peers required for quorum. Default 51.
	PeersRequireQuorumPercentage pulumi.IntPtrInput
	// Revoke approval for devices that have not checked in for more than this many days. Must be greater than 7.
	RemoveApprovalDevicesMoreStaleThanDays pulumi.IntPtrInput
	// Disassociate a device from its user after this many minutes.
	UserDeviceDisassociationMinutes pulumi.IntPtrInput
}

func (OrgConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*orgConfigArgs)(nil)).Elem()
}

type OrgConfigInput interface {
	pulumi.Input

	ToOrgConfigOutput() OrgConfigOutput
	ToOrgConfigOutputWithContext(ctx context.Context) OrgConfigOutput
}

func (*OrgConfig) ElementType() reflect.Type {
	return reflect.TypeOf((**OrgConfig)(nil)).Elem()
}

func (i *OrgConfig) ToOrgConfigOutput() OrgConfigOutput {
	return i.ToOrgConfigOutputWithContext(context.Background())
}

func (i *OrgConfig) ToOrgConfigOutputWithContext(ctx context.Context) OrgConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OrgConfigOutput)
}

type OrgConfigOutput struct{ *pulumi.OutputState }

func (OrgConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**OrgConfig)(nil)).Elem()
}

func (o OrgConfigOutput) ToOrgConfigOutput() OrgConfigOutput {
	return o
}

func (o OrgConfigOutput) ToOrgConfigOutputWithContext(ctx context.Context) OrgConfigOutput {
	return o
}

// Automatically admit a Controller that presents a valid pre-shared key, for zero-touch cluster scale-out.
func (o OrgConfigOutput) AllowControllerApprovalWithPskOnly() pulumi.BoolOutput {
	return o.ApplyT(func(v *OrgConfig) pulumi.BoolOutput { return v.AllowControllerApprovalWithPskOnly }).(pulumi.BoolOutput)
}

// Automatically approve a device when its user authenticates after installing the client.
func (o OrgConfigOutput) AllowDeviceApprovalOnUserAuth() pulumi.BoolOutput {
	return o.ApplyT(func(v *OrgConfig) pulumi.BoolOutput { return v.AllowDeviceApprovalOnUserAuth }).(pulumi.BoolOutput)
}

// Organization default for how Controllers listen on the SSH port: `any`, `local-only`, or `tunnel-only`.
func (o OrgConfigOutput) ControllerSshListener() pulumi.StringOutput {
	return o.ApplyT(func(v *OrgConfig) pulumi.StringOutput { return v.ControllerSshListener }).(pulumi.StringOutput)
}

// Default for considering pre-release versions when Controllers do not specify their own value.
func (o OrgConfigOutput) ControllerVersionIncludePrereleases() pulumi.BoolOutput {
	return o.ApplyT(func(v *OrgConfig) pulumi.BoolOutput { return v.ControllerVersionIncludePrereleases }).(pulumi.BoolOutput)
}

// Default minimum age, in days, a release must have before adoption under a latest-version strategy.
func (o OrgConfigOutput) ControllerVersionMinimumAge() pulumi.IntOutput {
	return o.ApplyT(func(v *OrgConfig) pulumi.IntOutput { return v.ControllerVersionMinimumAge }).(pulumi.IntOutput)
}

// Organization default update stagger: `no-delay`, `randomized-delay`, or `consistent-randomized-delay`.
func (o OrgConfigOutput) ControllerVersionSplayType() pulumi.StringOutput {
	return o.ApplyT(func(v *OrgConfig) pulumi.StringOutput { return v.ControllerVersionSplayType }).(pulumi.StringOutput)
}

// A systemd time-span for `randomized-delay` and `consistent-randomized-delay`.
func (o OrgConfigOutput) ControllerVersionSplayValue() pulumi.StringOutput {
	return o.ApplyT(func(v *OrgConfig) pulumi.StringOutput { return v.ControllerVersionSplayValue }).(pulumi.StringOutput)
}

// Organization default update strategy: `manual`, `specific`, `newest-at-interval`, or `newest-at-calendar`.
// (`org-default` is not valid here; the organization default cannot itself defer to the organization default.)
func (o OrgConfigOutput) ControllerVersionStrategyType() pulumi.StringOutput {
	return o.ApplyT(func(v *OrgConfig) pulumi.StringOutput { return v.ControllerVersionStrategyType }).(pulumi.StringOutput)
}

// Value for the default update strategy when it requires one (a version, time-span, or calendar expression).
func (o OrgConfigOutput) ControllerVersionStrategyValue() pulumi.StringOutput {
	return o.ApplyT(func(v *OrgConfig) pulumi.StringOutput { return v.ControllerVersionStrategyValue }).(pulumi.StringOutput)
}

// Delete devices that have not checked in for more than this many days. Must be greater than 7.
func (o OrgConfigOutput) DeleteDevicesMoreStaleThanDays() pulumi.IntOutput {
	return o.ApplyT(func(v *OrgConfig) pulumi.IntOutput { return v.DeleteDevicesMoreStaleThanDays }).(pulumi.IntOutput)
}

// When false, destructive device cleanup only proceeds when a quorum of Controller peers is connected.
func (o OrgConfigOutput) DisablePeersRequireQuorum() pulumi.BoolOutput {
	return o.ApplyT(func(v *OrgConfig) pulumi.BoolOutput { return v.DisablePeersRequireQuorum }).(pulumi.BoolOutput)
}

func (o OrgConfigOutput) LastUpdated() pulumi.StringOutput {
	return o.ApplyT(func(v *OrgConfig) pulumi.StringOutput { return v.LastUpdated }).(pulumi.StringOutput)
}

// Percentage (0-100) of Controller peers required for quorum. Default 51.
func (o OrgConfigOutput) PeersRequireQuorumPercentage() pulumi.IntOutput {
	return o.ApplyT(func(v *OrgConfig) pulumi.IntOutput { return v.PeersRequireQuorumPercentage }).(pulumi.IntOutput)
}

// Revoke approval for devices that have not checked in for more than this many days. Must be greater than 7.
func (o OrgConfigOutput) RemoveApprovalDevicesMoreStaleThanDays() pulumi.IntOutput {
	return o.ApplyT(func(v *OrgConfig) pulumi.IntOutput { return v.RemoveApprovalDevicesMoreStaleThanDays }).(pulumi.IntOutput)
}

// Disassociate a device from its user after this many minutes.
func (o OrgConfigOutput) UserDeviceDisassociationMinutes() pulumi.IntOutput {
	return o.ApplyT(func(v *OrgConfig) pulumi.IntOutput { return v.UserDeviceDisassociationMinutes }).(pulumi.IntOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*OrgConfigInput)(nil)).Elem(), &OrgConfig{})
	pulumi.RegisterOutputType(OrgConfigOutput{})
}
