// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package bowtie

import (
	"context"
	"reflect"

	"github.com/bowtieworks/pulumi-bowtie/sdk/go/bowtie/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The provider type for the bowtie package. By default, resources use package-wide configuration
// settings, however an explicit `Provider` instance may be created and passed during resource
// construction to achieve fine-grained programmatic control over provider settings. See the
// [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
type Provider struct {
	pulumi.ProviderResourceState

	// A PEM-encoded CA bundle (inline contents or a path to a file) used to verify the Controller's TLS certificate, for
	// Controllers issued by a private certificate authority. Honors the `BOWTIE_CA_BUNDLE` environment variable if set.
	CaBundle pulumi.StringPtrOutput `pulumi:"caBundle"`
	// The Bowtie HTTP Controller endpoint. Honors the `BOWTIE_HOST` environment variable if set. Example:
	// `https://bowtie.example.com`
	Host     pulumi.StringPtrOutput `pulumi:"host"`
	Password pulumi.StringPtrOutput `pulumi:"password"`
	Username pulumi.StringPtrOutput `pulumi:"username"`
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		args = &ProviderArgs{}
	}

	if args.Password != nil {
		args.Password = pulumi.ToSecret(args.Password).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"password",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Provider
	err := ctx.RegisterResource("pulumi:providers:bowtie", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	// A PEM-encoded CA bundle (inline contents or a path to a file) used to verify the Controller's TLS certificate, for
	// Controllers issued by a private certificate authority. Honors the `BOWTIE_CA_BUNDLE` environment variable if set.
	CaBundle *string `pulumi:"caBundle"`
	// The Bowtie HTTP Controller endpoint. Honors the `BOWTIE_HOST` environment variable if set. Example:
	// `https://bowtie.example.com`
	Host *string `pulumi:"host"`
	// Skip TLS certificate verification when connecting to the Controller. Honors the `BOWTIE_INSECURE` environment variable
	// if set. Intended for development controllers with self-signed certificates; do not enable against production.
	Insecure           *bool   `pulumi:"insecure"`
	LazyAuthentication *bool   `pulumi:"lazyAuthentication"`
	Password           *string `pulumi:"password"`
	// Control whether the provider will send policy resource locations using the new tagged type format or legacy format.
	TaggedLocations *bool   `pulumi:"taggedLocations"`
	Username        *string `pulumi:"username"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	// A PEM-encoded CA bundle (inline contents or a path to a file) used to verify the Controller's TLS certificate, for
	// Controllers issued by a private certificate authority. Honors the `BOWTIE_CA_BUNDLE` environment variable if set.
	CaBundle pulumi.StringPtrInput
	// The Bowtie HTTP Controller endpoint. Honors the `BOWTIE_HOST` environment variable if set. Example:
	// `https://bowtie.example.com`
	Host pulumi.StringPtrInput
	// Skip TLS certificate verification when connecting to the Controller. Honors the `BOWTIE_INSECURE` environment variable
	// if set. Intended for development controllers with self-signed certificates; do not enable against production.
	Insecure           pulumi.BoolPtrInput
	LazyAuthentication pulumi.BoolPtrInput
	Password           pulumi.StringPtrInput
	// Control whether the provider will send policy resource locations using the new tagged type format or legacy format.
	TaggedLocations pulumi.BoolPtrInput
	Username        pulumi.StringPtrInput
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}

type ProviderInput interface {
	pulumi.Input

	ToProviderOutput() ProviderOutput
	ToProviderOutputWithContext(ctx context.Context) ProviderOutput
}

func (*Provider) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (i *Provider) ToProviderOutput() ProviderOutput {
	return i.ToProviderOutputWithContext(context.Background())
}

func (i *Provider) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderOutput)
}

type ProviderOutput struct{ *pulumi.OutputState }

func (ProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (o ProviderOutput) ToProviderOutput() ProviderOutput {
	return o
}

func (o ProviderOutput) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return o
}

// A PEM-encoded CA bundle (inline contents or a path to a file) used to verify the Controller's TLS certificate, for
// Controllers issued by a private certificate authority. Honors the `BOWTIE_CA_BUNDLE` environment variable if set.
func (o ProviderOutput) CaBundle() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.CaBundle }).(pulumi.StringPtrOutput)
}

// The Bowtie HTTP Controller endpoint. Honors the `BOWTIE_HOST` environment variable if set. Example:
// `https://bowtie.example.com`
func (o ProviderOutput) Host() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.Host }).(pulumi.StringPtrOutput)
}

func (o ProviderOutput) Password() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.Password }).(pulumi.StringPtrOutput)
}

func (o ProviderOutput) Username() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.Username }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderInput)(nil)).Elem(), &Provider{})
	pulumi.RegisterOutputType(ProviderOutput{})
}
