// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package bowtie

import (
	"context"
	"reflect"

	"errors"
	"github.com/bowtieworks/pulumi-bowtie/sdk/go/bowtie/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ResourceGroup struct {
	pulumi.CustomResourceState

	// The list of resource groups to include in this resource group
	Inheriteds pulumi.StringArrayOutput `pulumi:"inheriteds"`
	// The human readable name/description of the resource group.
	Name pulumi.StringOutput `pulumi:"name"`
	// The resources that should directly be included in this resource group
	Resources pulumi.StringArrayOutput `pulumi:"resources"`
}

// NewResourceGroup registers a new resource with the given unique name, arguments, and options.
func NewResourceGroup(ctx *pulumi.Context,
	name string, args *ResourceGroupArgs, opts ...pulumi.ResourceOption) (*ResourceGroup, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Inheriteds == nil {
		return nil, errors.New("invalid value for required argument 'Inheriteds'")
	}
	if args.Resources == nil {
		return nil, errors.New("invalid value for required argument 'Resources'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ResourceGroup
	err := ctx.RegisterResource("bowtie:index/resourceGroup:ResourceGroup", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetResourceGroup gets an existing ResourceGroup resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetResourceGroup(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ResourceGroupState, opts ...pulumi.ResourceOption) (*ResourceGroup, error) {
	var resource ResourceGroup
	err := ctx.ReadResource("bowtie:index/resourceGroup:ResourceGroup", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ResourceGroup resources.
type resourceGroupState struct {
	// The list of resource groups to include in this resource group
	Inheriteds []string `pulumi:"inheriteds"`
	// The human readable name/description of the resource group.
	Name *string `pulumi:"name"`
	// The resources that should directly be included in this resource group
	Resources []string `pulumi:"resources"`
}

type ResourceGroupState struct {
	// The list of resource groups to include in this resource group
	Inheriteds pulumi.StringArrayInput
	// The human readable name/description of the resource group.
	Name pulumi.StringPtrInput
	// The resources that should directly be included in this resource group
	Resources pulumi.StringArrayInput
}

func (ResourceGroupState) ElementType() reflect.Type {
	return reflect.TypeOf((*resourceGroupState)(nil)).Elem()
}

type resourceGroupArgs struct {
	// The list of resource groups to include in this resource group
	Inheriteds []string `pulumi:"inheriteds"`
	// The human readable name/description of the resource group.
	Name *string `pulumi:"name"`
	// The resources that should directly be included in this resource group
	Resources []string `pulumi:"resources"`
}

// The set of arguments for constructing a ResourceGroup resource.
type ResourceGroupArgs struct {
	// The list of resource groups to include in this resource group
	Inheriteds pulumi.StringArrayInput
	// The human readable name/description of the resource group.
	Name pulumi.StringPtrInput
	// The resources that should directly be included in this resource group
	Resources pulumi.StringArrayInput
}

func (ResourceGroupArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*resourceGroupArgs)(nil)).Elem()
}

type ResourceGroupInput interface {
	pulumi.Input

	ToResourceGroupOutput() ResourceGroupOutput
	ToResourceGroupOutputWithContext(ctx context.Context) ResourceGroupOutput
}

func (*ResourceGroup) ElementType() reflect.Type {
	return reflect.TypeOf((**ResourceGroup)(nil)).Elem()
}

func (i *ResourceGroup) ToResourceGroupOutput() ResourceGroupOutput {
	return i.ToResourceGroupOutputWithContext(context.Background())
}

func (i *ResourceGroup) ToResourceGroupOutputWithContext(ctx context.Context) ResourceGroupOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ResourceGroupOutput)
}

type ResourceGroupOutput struct{ *pulumi.OutputState }

func (ResourceGroupOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ResourceGroup)(nil)).Elem()
}

func (o ResourceGroupOutput) ToResourceGroupOutput() ResourceGroupOutput {
	return o
}

func (o ResourceGroupOutput) ToResourceGroupOutputWithContext(ctx context.Context) ResourceGroupOutput {
	return o
}

// The list of resource groups to include in this resource group
func (o ResourceGroupOutput) Inheriteds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *ResourceGroup) pulumi.StringArrayOutput { return v.Inheriteds }).(pulumi.StringArrayOutput)
}

// The human readable name/description of the resource group.
func (o ResourceGroupOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *ResourceGroup) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// The resources that should directly be included in this resource group
func (o ResourceGroupOutput) Resources() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *ResourceGroup) pulumi.StringArrayOutput { return v.Resources }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ResourceGroupInput)(nil)).Elem(), &ResourceGroup{})
	pulumi.RegisterOutputType(ResourceGroupOutput{})
}
