// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package bowtie

import (
	"context"
	"reflect"

	"errors"
	"github.com/bowtieworks/pulumi-bowtie/sdk/go/bowtie/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Resource struct {
	pulumi.CustomResourceState

	// The address of the resource. May be a CIDR address, single IP, or DNS name.
	Location ResourceLocationOutput `pulumi:"location"`
	// Human readable name of the resource.
	Name pulumi.StringOutput `pulumi:"name"`
	// Which ports to include in this resource.
	Ports ResourcePortsOutput `pulumi:"ports"`
	// Matching connection protocol.
	Protocol pulumi.StringOutput `pulumi:"protocol"`
}

// NewResource registers a new resource with the given unique name, arguments, and options.
func NewResource(ctx *pulumi.Context,
	name string, args *ResourceArgs, opts ...pulumi.ResourceOption) (*Resource, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Location == nil {
		return nil, errors.New("invalid value for required argument 'Location'")
	}
	if args.Ports == nil {
		return nil, errors.New("invalid value for required argument 'Ports'")
	}
	if args.Protocol == nil {
		return nil, errors.New("invalid value for required argument 'Protocol'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Resource
	err := ctx.RegisterResource("bowtie:index/resource:Resource", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetResource gets an existing Resource resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetResource(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ResourceState, opts ...pulumi.ResourceOption) (*Resource, error) {
	var resource Resource
	err := ctx.ReadResource("bowtie:index/resource:Resource", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering Resource resources.
type resourceState struct {
	// The address of the resource. May be a CIDR address, single IP, or DNS name.
	Location *ResourceLocation `pulumi:"location"`
	// Human readable name of the resource.
	Name *string `pulumi:"name"`
	// Which ports to include in this resource.
	Ports *ResourcePorts `pulumi:"ports"`
	// Matching connection protocol.
	Protocol *string `pulumi:"protocol"`
}

type ResourceState struct {
	// The address of the resource. May be a CIDR address, single IP, or DNS name.
	Location ResourceLocationPtrInput
	// Human readable name of the resource.
	Name pulumi.StringPtrInput
	// Which ports to include in this resource.
	Ports ResourcePortsPtrInput
	// Matching connection protocol.
	Protocol pulumi.StringPtrInput
}

func (ResourceState) ElementType() reflect.Type {
	return reflect.TypeOf((*resourceState)(nil)).Elem()
}

type resourceArgs struct {
	// The address of the resource. May be a CIDR address, single IP, or DNS name.
	Location ResourceLocation `pulumi:"location"`
	// Human readable name of the resource.
	Name *string `pulumi:"name"`
	// Which ports to include in this resource.
	Ports ResourcePorts `pulumi:"ports"`
	// Matching connection protocol.
	Protocol string `pulumi:"protocol"`
}

// The set of arguments for constructing a Resource resource.
type ResourceArgs struct {
	// The address of the resource. May be a CIDR address, single IP, or DNS name.
	Location ResourceLocationInput
	// Human readable name of the resource.
	Name pulumi.StringPtrInput
	// Which ports to include in this resource.
	Ports ResourcePortsInput
	// Matching connection protocol.
	Protocol pulumi.StringInput
}

func (ResourceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*resourceArgs)(nil)).Elem()
}

type ResourceInput interface {
	pulumi.Input

	ToResourceOutput() ResourceOutput
	ToResourceOutputWithContext(ctx context.Context) ResourceOutput
}

func (*Resource) ElementType() reflect.Type {
	return reflect.TypeOf((**Resource)(nil)).Elem()
}

func (i *Resource) ToResourceOutput() ResourceOutput {
	return i.ToResourceOutputWithContext(context.Background())
}

func (i *Resource) ToResourceOutputWithContext(ctx context.Context) ResourceOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ResourceOutput)
}

type ResourceOutput struct{ *pulumi.OutputState }

func (ResourceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Resource)(nil)).Elem()
}

func (o ResourceOutput) ToResourceOutput() ResourceOutput {
	return o
}

func (o ResourceOutput) ToResourceOutputWithContext(ctx context.Context) ResourceOutput {
	return o
}

// The address of the resource. May be a CIDR address, single IP, or DNS name.
func (o ResourceOutput) Location() ResourceLocationOutput {
	return o.ApplyT(func(v *Resource) ResourceLocationOutput { return v.Location }).(ResourceLocationOutput)
}

// Human readable name of the resource.
func (o ResourceOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *Resource) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Which ports to include in this resource.
func (o ResourceOutput) Ports() ResourcePortsOutput {
	return o.ApplyT(func(v *Resource) ResourcePortsOutput { return v.Ports }).(ResourcePortsOutput)
}

// Matching connection protocol.
func (o ResourceOutput) Protocol() pulumi.StringOutput {
	return o.ApplyT(func(v *Resource) pulumi.StringOutput { return v.Protocol }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ResourceInput)(nil)).Elem(), &Resource{})
	pulumi.RegisterOutputType(ResourceOutput{})
}
