// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package bowtie

import (
	"context"
	"reflect"

	"errors"
	"github.com/bowtieworks/pulumi-bowtie/sdk/go/bowtie/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type RouteExclusion struct {
	pulumi.CustomResourceState

	// Rollout strategy: `always`, `never` (staged but inactive), `percentageUserMatch`, or `percentageDeviceMatch`. Defaults
	// to `always`.
	ApplyStrategy pulumi.StringOutput `pulumi:"applyStrategy"`
	// The match percentage (0-255, in ~0.5% increments) used when `applyStrategy` is `percentageUserMatch` or
	// `percentageDeviceMatch`.
	ApplyStrategyPercentage pulumi.IntPtrOutput `pulumi:"applyStrategyPercentage"`
	// The ID of the collection whose CIDR members are excluded from the tunnel. The collection must already exist.
	CollectionId pulumi.StringOutput `pulumi:"collectionId"`
	// Apply only to devices in these device group IDs.
	MatchOnlyDeviceGroups pulumi.StringArrayOutput `pulumi:"matchOnlyDeviceGroups"`
	// Apply only to devices with this OS: `windows`, `macos`, `linux`, `ios`, `android`, `chromeos`, `Controller`, or
	// `unknown`. Changing or removing this recreates the exclusion.
	MatchOnlyDeviceOs pulumi.StringPtrOutput `pulumi:"matchOnlyDeviceOs"`
	// Apply only to devices of this type: `laptop`, `desktop`, `mobile`, `server`, or `other`. Changing or removing this
	// recreates the exclusion.
	MatchOnlyDeviceType pulumi.StringPtrOutput `pulumi:"matchOnlyDeviceType"`
	// Apply only to devices owned by this organization ID. Changing or removing this recreates the exclusion.
	MatchOnlyOwnership pulumi.StringPtrOutput `pulumi:"matchOnlyOwnership"`
	// Apply only to devices whose user is in these user group IDs.
	MatchOnlyUserGroups pulumi.StringArrayOutput `pulumi:"matchOnlyUserGroups"`
	// Human-readable name for the exclusion.
	Name pulumi.StringOutput `pulumi:"name"`
	// If set, the exclusion only applies when the device's WAN IP falls within one of these CIDRs (for example, an office
	// network).
	OnlyIfWanMatchesCidrs pulumi.StringArrayOutput `pulumi:"onlyIfWanMatchesCidrs"`
	// The site IDs this exclusion applies to. Omit to apply to all sites.
	Sites pulumi.StringArrayOutput `pulumi:"sites"`
	// A content hash of the exclusion, computed by the Controller.
	Version pulumi.StringOutput `pulumi:"version"`
}

// NewRouteExclusion registers a new resource with the given unique name, arguments, and options.
func NewRouteExclusion(ctx *pulumi.Context,
	name string, args *RouteExclusionArgs, opts ...pulumi.ResourceOption) (*RouteExclusion, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.CollectionId == nil {
		return nil, errors.New("invalid value for required argument 'CollectionId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource RouteExclusion
	err := ctx.RegisterResource("bowtie:index/routeExclusion:RouteExclusion", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetRouteExclusion gets an existing RouteExclusion resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetRouteExclusion(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *RouteExclusionState, opts ...pulumi.ResourceOption) (*RouteExclusion, error) {
	var resource RouteExclusion
	err := ctx.ReadResource("bowtie:index/routeExclusion:RouteExclusion", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering RouteExclusion resources.
type routeExclusionState struct {
	// Rollout strategy: `always`, `never` (staged but inactive), `percentageUserMatch`, or `percentageDeviceMatch`. Defaults
	// to `always`.
	ApplyStrategy *string `pulumi:"applyStrategy"`
	// The match percentage (0-255, in ~0.5% increments) used when `applyStrategy` is `percentageUserMatch` or
	// `percentageDeviceMatch`.
	ApplyStrategyPercentage *int `pulumi:"applyStrategyPercentage"`
	// The ID of the collection whose CIDR members are excluded from the tunnel. The collection must already exist.
	CollectionId *string `pulumi:"collectionId"`
	// Apply only to devices in these device group IDs.
	MatchOnlyDeviceGroups []string `pulumi:"matchOnlyDeviceGroups"`
	// Apply only to devices with this OS: `windows`, `macos`, `linux`, `ios`, `android`, `chromeos`, `Controller`, or
	// `unknown`. Changing or removing this recreates the exclusion.
	MatchOnlyDeviceOs *string `pulumi:"matchOnlyDeviceOs"`
	// Apply only to devices of this type: `laptop`, `desktop`, `mobile`, `server`, or `other`. Changing or removing this
	// recreates the exclusion.
	MatchOnlyDeviceType *string `pulumi:"matchOnlyDeviceType"`
	// Apply only to devices owned by this organization ID. Changing or removing this recreates the exclusion.
	MatchOnlyOwnership *string `pulumi:"matchOnlyOwnership"`
	// Apply only to devices whose user is in these user group IDs.
	MatchOnlyUserGroups []string `pulumi:"matchOnlyUserGroups"`
	// Human-readable name for the exclusion.
	Name *string `pulumi:"name"`
	// If set, the exclusion only applies when the device's WAN IP falls within one of these CIDRs (for example, an office
	// network).
	OnlyIfWanMatchesCidrs []string `pulumi:"onlyIfWanMatchesCidrs"`
	// The site IDs this exclusion applies to. Omit to apply to all sites.
	Sites []string `pulumi:"sites"`
	// A content hash of the exclusion, computed by the Controller.
	Version *string `pulumi:"version"`
}

type RouteExclusionState struct {
	// Rollout strategy: `always`, `never` (staged but inactive), `percentageUserMatch`, or `percentageDeviceMatch`. Defaults
	// to `always`.
	ApplyStrategy pulumi.StringPtrInput
	// The match percentage (0-255, in ~0.5% increments) used when `applyStrategy` is `percentageUserMatch` or
	// `percentageDeviceMatch`.
	ApplyStrategyPercentage pulumi.IntPtrInput
	// The ID of the collection whose CIDR members are excluded from the tunnel. The collection must already exist.
	CollectionId pulumi.StringPtrInput
	// Apply only to devices in these device group IDs.
	MatchOnlyDeviceGroups pulumi.StringArrayInput
	// Apply only to devices with this OS: `windows`, `macos`, `linux`, `ios`, `android`, `chromeos`, `Controller`, or
	// `unknown`. Changing or removing this recreates the exclusion.
	MatchOnlyDeviceOs pulumi.StringPtrInput
	// Apply only to devices of this type: `laptop`, `desktop`, `mobile`, `server`, or `other`. Changing or removing this
	// recreates the exclusion.
	MatchOnlyDeviceType pulumi.StringPtrInput
	// Apply only to devices owned by this organization ID. Changing or removing this recreates the exclusion.
	MatchOnlyOwnership pulumi.StringPtrInput
	// Apply only to devices whose user is in these user group IDs.
	MatchOnlyUserGroups pulumi.StringArrayInput
	// Human-readable name for the exclusion.
	Name pulumi.StringPtrInput
	// If set, the exclusion only applies when the device's WAN IP falls within one of these CIDRs (for example, an office
	// network).
	OnlyIfWanMatchesCidrs pulumi.StringArrayInput
	// The site IDs this exclusion applies to. Omit to apply to all sites.
	Sites pulumi.StringArrayInput
	// A content hash of the exclusion, computed by the Controller.
	Version pulumi.StringPtrInput
}

func (RouteExclusionState) ElementType() reflect.Type {
	return reflect.TypeOf((*routeExclusionState)(nil)).Elem()
}

type routeExclusionArgs struct {
	// Rollout strategy: `always`, `never` (staged but inactive), `percentageUserMatch`, or `percentageDeviceMatch`. Defaults
	// to `always`.
	ApplyStrategy *string `pulumi:"applyStrategy"`
	// The match percentage (0-255, in ~0.5% increments) used when `applyStrategy` is `percentageUserMatch` or
	// `percentageDeviceMatch`.
	ApplyStrategyPercentage *int `pulumi:"applyStrategyPercentage"`
	// The ID of the collection whose CIDR members are excluded from the tunnel. The collection must already exist.
	CollectionId string `pulumi:"collectionId"`
	// Apply only to devices in these device group IDs.
	MatchOnlyDeviceGroups []string `pulumi:"matchOnlyDeviceGroups"`
	// Apply only to devices with this OS: `windows`, `macos`, `linux`, `ios`, `android`, `chromeos`, `Controller`, or
	// `unknown`. Changing or removing this recreates the exclusion.
	MatchOnlyDeviceOs *string `pulumi:"matchOnlyDeviceOs"`
	// Apply only to devices of this type: `laptop`, `desktop`, `mobile`, `server`, or `other`. Changing or removing this
	// recreates the exclusion.
	MatchOnlyDeviceType *string `pulumi:"matchOnlyDeviceType"`
	// Apply only to devices owned by this organization ID. Changing or removing this recreates the exclusion.
	MatchOnlyOwnership *string `pulumi:"matchOnlyOwnership"`
	// Apply only to devices whose user is in these user group IDs.
	MatchOnlyUserGroups []string `pulumi:"matchOnlyUserGroups"`
	// Human-readable name for the exclusion.
	Name *string `pulumi:"name"`
	// If set, the exclusion only applies when the device's WAN IP falls within one of these CIDRs (for example, an office
	// network).
	OnlyIfWanMatchesCidrs []string `pulumi:"onlyIfWanMatchesCidrs"`
	// The site IDs this exclusion applies to. Omit to apply to all sites.
	Sites []string `pulumi:"sites"`
}

// The set of arguments for constructing a RouteExclusion resource.
type RouteExclusionArgs struct {
	// Rollout strategy: `always`, `never` (staged but inactive), `percentageUserMatch`, or `percentageDeviceMatch`. Defaults
	// to `always`.
	ApplyStrategy pulumi.StringPtrInput
	// The match percentage (0-255, in ~0.5% increments) used when `applyStrategy` is `percentageUserMatch` or
	// `percentageDeviceMatch`.
	ApplyStrategyPercentage pulumi.IntPtrInput
	// The ID of the collection whose CIDR members are excluded from the tunnel. The collection must already exist.
	CollectionId pulumi.StringInput
	// Apply only to devices in these device group IDs.
	MatchOnlyDeviceGroups pulumi.StringArrayInput
	// Apply only to devices with this OS: `windows`, `macos`, `linux`, `ios`, `android`, `chromeos`, `Controller`, or
	// `unknown`. Changing or removing this recreates the exclusion.
	MatchOnlyDeviceOs pulumi.StringPtrInput
	// Apply only to devices of this type: `laptop`, `desktop`, `mobile`, `server`, or `other`. Changing or removing this
	// recreates the exclusion.
	MatchOnlyDeviceType pulumi.StringPtrInput
	// Apply only to devices owned by this organization ID. Changing or removing this recreates the exclusion.
	MatchOnlyOwnership pulumi.StringPtrInput
	// Apply only to devices whose user is in these user group IDs.
	MatchOnlyUserGroups pulumi.StringArrayInput
	// Human-readable name for the exclusion.
	Name pulumi.StringPtrInput
	// If set, the exclusion only applies when the device's WAN IP falls within one of these CIDRs (for example, an office
	// network).
	OnlyIfWanMatchesCidrs pulumi.StringArrayInput
	// The site IDs this exclusion applies to. Omit to apply to all sites.
	Sites pulumi.StringArrayInput
}

func (RouteExclusionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*routeExclusionArgs)(nil)).Elem()
}

type RouteExclusionInput interface {
	pulumi.Input

	ToRouteExclusionOutput() RouteExclusionOutput
	ToRouteExclusionOutputWithContext(ctx context.Context) RouteExclusionOutput
}

func (*RouteExclusion) ElementType() reflect.Type {
	return reflect.TypeOf((**RouteExclusion)(nil)).Elem()
}

func (i *RouteExclusion) ToRouteExclusionOutput() RouteExclusionOutput {
	return i.ToRouteExclusionOutputWithContext(context.Background())
}

func (i *RouteExclusion) ToRouteExclusionOutputWithContext(ctx context.Context) RouteExclusionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(RouteExclusionOutput)
}

type RouteExclusionOutput struct{ *pulumi.OutputState }

func (RouteExclusionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**RouteExclusion)(nil)).Elem()
}

func (o RouteExclusionOutput) ToRouteExclusionOutput() RouteExclusionOutput {
	return o
}

func (o RouteExclusionOutput) ToRouteExclusionOutputWithContext(ctx context.Context) RouteExclusionOutput {
	return o
}

// Rollout strategy: `always`, `never` (staged but inactive), `percentageUserMatch`, or `percentageDeviceMatch`. Defaults
// to `always`.
func (o RouteExclusionOutput) ApplyStrategy() pulumi.StringOutput {
	return o.ApplyT(func(v *RouteExclusion) pulumi.StringOutput { return v.ApplyStrategy }).(pulumi.StringOutput)
}

// The match percentage (0-255, in ~0.5% increments) used when `applyStrategy` is `percentageUserMatch` or
// `percentageDeviceMatch`.
func (o RouteExclusionOutput) ApplyStrategyPercentage() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *RouteExclusion) pulumi.IntPtrOutput { return v.ApplyStrategyPercentage }).(pulumi.IntPtrOutput)
}

// The ID of the collection whose CIDR members are excluded from the tunnel. The collection must already exist.
func (o RouteExclusionOutput) CollectionId() pulumi.StringOutput {
	return o.ApplyT(func(v *RouteExclusion) pulumi.StringOutput { return v.CollectionId }).(pulumi.StringOutput)
}

// Apply only to devices in these device group IDs.
func (o RouteExclusionOutput) MatchOnlyDeviceGroups() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *RouteExclusion) pulumi.StringArrayOutput { return v.MatchOnlyDeviceGroups }).(pulumi.StringArrayOutput)
}

// Apply only to devices with this OS: `windows`, `macos`, `linux`, `ios`, `android`, `chromeos`, `Controller`, or
// `unknown`. Changing or removing this recreates the exclusion.
func (o RouteExclusionOutput) MatchOnlyDeviceOs() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *RouteExclusion) pulumi.StringPtrOutput { return v.MatchOnlyDeviceOs }).(pulumi.StringPtrOutput)
}

// Apply only to devices of this type: `laptop`, `desktop`, `mobile`, `server`, or `other`. Changing or removing this
// recreates the exclusion.
func (o RouteExclusionOutput) MatchOnlyDeviceType() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *RouteExclusion) pulumi.StringPtrOutput { return v.MatchOnlyDeviceType }).(pulumi.StringPtrOutput)
}

// Apply only to devices owned by this organization ID. Changing or removing this recreates the exclusion.
func (o RouteExclusionOutput) MatchOnlyOwnership() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *RouteExclusion) pulumi.StringPtrOutput { return v.MatchOnlyOwnership }).(pulumi.StringPtrOutput)
}

// Apply only to devices whose user is in these user group IDs.
func (o RouteExclusionOutput) MatchOnlyUserGroups() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *RouteExclusion) pulumi.StringArrayOutput { return v.MatchOnlyUserGroups }).(pulumi.StringArrayOutput)
}

// Human-readable name for the exclusion.
func (o RouteExclusionOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *RouteExclusion) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// If set, the exclusion only applies when the device's WAN IP falls within one of these CIDRs (for example, an office
// network).
func (o RouteExclusionOutput) OnlyIfWanMatchesCidrs() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *RouteExclusion) pulumi.StringArrayOutput { return v.OnlyIfWanMatchesCidrs }).(pulumi.StringArrayOutput)
}

// The site IDs this exclusion applies to. Omit to apply to all sites.
func (o RouteExclusionOutput) Sites() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *RouteExclusion) pulumi.StringArrayOutput { return v.Sites }).(pulumi.StringArrayOutput)
}

// A content hash of the exclusion, computed by the Controller.
func (o RouteExclusionOutput) Version() pulumi.StringOutput {
	return o.ApplyT(func(v *RouteExclusion) pulumi.StringOutput { return v.Version }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*RouteExclusionInput)(nil)).Elem(), &RouteExclusion{})
	pulumi.RegisterOutputType(RouteExclusionOutput{})
}
