// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package bowtie

import (
	"context"
	"reflect"

	"errors"
	"github.com/bowtieworks/pulumi-bowtie/sdk/go/bowtie/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type User struct {
	pulumi.CustomResourceState

	// Grants the user access to the Control Plane UI and API.
	AuthzControlPlane pulumi.BoolOutput `pulumi:"authzControlPlane"`
	// Grants the user access to the Devices UI and API.
	AuthzDevices pulumi.BoolOutput `pulumi:"authzDevices"`
	// Grants the user access to the Policies UI and API.
	AuthzPolicies pulumi.BoolOutput `pulumi:"authzPolicies"`
	// Grants the user access to the Users UI and API.
	AuthzUsers pulumi.BoolOutput `pulumi:"authzUsers"`
	// The user's email.
	Email pulumi.StringOutput `pulumi:"email"`
	// Configures if the user is `Active` or `Disabled`.
	Enabled pulumi.BoolOutput `pulumi:"enabled"`
	// The user's name.
	Name pulumi.StringOutput `pulumi:"name"`
	// What role the user is assigned. Value must be one of `Ownder`, `User`, `FullAdministrator`, or `LimitedAdministrator`.
	Role pulumi.StringOutput `pulumi:"role"`
}

// NewUser registers a new resource with the given unique name, arguments, and options.
func NewUser(ctx *pulumi.Context,
	name string, args *UserArgs, opts ...pulumi.ResourceOption) (*User, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Email == nil {
		return nil, errors.New("invalid value for required argument 'Email'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource User
	err := ctx.RegisterResource("bowtie:index/user:User", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetUser gets an existing User resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetUser(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *UserState, opts ...pulumi.ResourceOption) (*User, error) {
	var resource User
	err := ctx.ReadResource("bowtie:index/user:User", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering User resources.
type userState struct {
	// Grants the user access to the Control Plane UI and API.
	AuthzControlPlane *bool `pulumi:"authzControlPlane"`
	// Grants the user access to the Devices UI and API.
	AuthzDevices *bool `pulumi:"authzDevices"`
	// Grants the user access to the Policies UI and API.
	AuthzPolicies *bool `pulumi:"authzPolicies"`
	// Grants the user access to the Users UI and API.
	AuthzUsers *bool `pulumi:"authzUsers"`
	// The user's email.
	Email *string `pulumi:"email"`
	// Configures if the user is `Active` or `Disabled`.
	Enabled *bool `pulumi:"enabled"`
	// The user's name.
	Name *string `pulumi:"name"`
	// What role the user is assigned. Value must be one of `Ownder`, `User`, `FullAdministrator`, or `LimitedAdministrator`.
	Role *string `pulumi:"role"`
}

type UserState struct {
	// Grants the user access to the Control Plane UI and API.
	AuthzControlPlane pulumi.BoolPtrInput
	// Grants the user access to the Devices UI and API.
	AuthzDevices pulumi.BoolPtrInput
	// Grants the user access to the Policies UI and API.
	AuthzPolicies pulumi.BoolPtrInput
	// Grants the user access to the Users UI and API.
	AuthzUsers pulumi.BoolPtrInput
	// The user's email.
	Email pulumi.StringPtrInput
	// Configures if the user is `Active` or `Disabled`.
	Enabled pulumi.BoolPtrInput
	// The user's name.
	Name pulumi.StringPtrInput
	// What role the user is assigned. Value must be one of `Ownder`, `User`, `FullAdministrator`, or `LimitedAdministrator`.
	Role pulumi.StringPtrInput
}

func (UserState) ElementType() reflect.Type {
	return reflect.TypeOf((*userState)(nil)).Elem()
}

type userArgs struct {
	// Grants the user access to the Control Plane UI and API.
	AuthzControlPlane *bool `pulumi:"authzControlPlane"`
	// Grants the user access to the Devices UI and API.
	AuthzDevices *bool `pulumi:"authzDevices"`
	// Grants the user access to the Policies UI and API.
	AuthzPolicies *bool `pulumi:"authzPolicies"`
	// Grants the user access to the Users UI and API.
	AuthzUsers *bool `pulumi:"authzUsers"`
	// The user's email.
	Email string `pulumi:"email"`
	// Configures if the user is `Active` or `Disabled`.
	Enabled *bool `pulumi:"enabled"`
	// The user's name.
	Name *string `pulumi:"name"`
	// What role the user is assigned. Value must be one of `Ownder`, `User`, `FullAdministrator`, or `LimitedAdministrator`.
	Role *string `pulumi:"role"`
}

// The set of arguments for constructing a User resource.
type UserArgs struct {
	// Grants the user access to the Control Plane UI and API.
	AuthzControlPlane pulumi.BoolPtrInput
	// Grants the user access to the Devices UI and API.
	AuthzDevices pulumi.BoolPtrInput
	// Grants the user access to the Policies UI and API.
	AuthzPolicies pulumi.BoolPtrInput
	// Grants the user access to the Users UI and API.
	AuthzUsers pulumi.BoolPtrInput
	// The user's email.
	Email pulumi.StringInput
	// Configures if the user is `Active` or `Disabled`.
	Enabled pulumi.BoolPtrInput
	// The user's name.
	Name pulumi.StringPtrInput
	// What role the user is assigned. Value must be one of `Ownder`, `User`, `FullAdministrator`, or `LimitedAdministrator`.
	Role pulumi.StringPtrInput
}

func (UserArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*userArgs)(nil)).Elem()
}

type UserInput interface {
	pulumi.Input

	ToUserOutput() UserOutput
	ToUserOutputWithContext(ctx context.Context) UserOutput
}

func (*User) ElementType() reflect.Type {
	return reflect.TypeOf((**User)(nil)).Elem()
}

func (i *User) ToUserOutput() UserOutput {
	return i.ToUserOutputWithContext(context.Background())
}

func (i *User) ToUserOutputWithContext(ctx context.Context) UserOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UserOutput)
}

type UserOutput struct{ *pulumi.OutputState }

func (UserOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**User)(nil)).Elem()
}

func (o UserOutput) ToUserOutput() UserOutput {
	return o
}

func (o UserOutput) ToUserOutputWithContext(ctx context.Context) UserOutput {
	return o
}

// Grants the user access to the Control Plane UI and API.
func (o UserOutput) AuthzControlPlane() pulumi.BoolOutput {
	return o.ApplyT(func(v *User) pulumi.BoolOutput { return v.AuthzControlPlane }).(pulumi.BoolOutput)
}

// Grants the user access to the Devices UI and API.
func (o UserOutput) AuthzDevices() pulumi.BoolOutput {
	return o.ApplyT(func(v *User) pulumi.BoolOutput { return v.AuthzDevices }).(pulumi.BoolOutput)
}

// Grants the user access to the Policies UI and API.
func (o UserOutput) AuthzPolicies() pulumi.BoolOutput {
	return o.ApplyT(func(v *User) pulumi.BoolOutput { return v.AuthzPolicies }).(pulumi.BoolOutput)
}

// Grants the user access to the Users UI and API.
func (o UserOutput) AuthzUsers() pulumi.BoolOutput {
	return o.ApplyT(func(v *User) pulumi.BoolOutput { return v.AuthzUsers }).(pulumi.BoolOutput)
}

// The user's email.
func (o UserOutput) Email() pulumi.StringOutput {
	return o.ApplyT(func(v *User) pulumi.StringOutput { return v.Email }).(pulumi.StringOutput)
}

// Configures if the user is `Active` or `Disabled`.
func (o UserOutput) Enabled() pulumi.BoolOutput {
	return o.ApplyT(func(v *User) pulumi.BoolOutput { return v.Enabled }).(pulumi.BoolOutput)
}

// The user's name.
func (o UserOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *User) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// What role the user is assigned. Value must be one of `Ownder`, `User`, `FullAdministrator`, or `LimitedAdministrator`.
func (o UserOutput) Role() pulumi.StringOutput {
	return o.ApplyT(func(v *User) pulumi.StringOutput { return v.Role }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*UserInput)(nil)).Elem(), &User{})
	pulumi.RegisterOutputType(UserOutput{})
}
