// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Bowtie
{
    [BowtieResourceType("bowtie:index/dns:Dns")]
    public partial class Dns : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Names under this domain to exclude from resolution.
        /// </summary>
        [Output("excludes")]
        public Output<ImmutableArray<Outputs.DnsExclude>> Excludes { get; private set; } = null!;

        /// <summary>
        /// Limit name resolution for this domain only to these sites.
        /// </summary>
        [Output("includeOnlySites")]
        public Output<ImmutableArray<string>> IncludeOnlySites { get; private set; } = null!;

        /// <summary>
        /// Whether to only log metrics for this domain and not all requests.
        /// </summary>
        [Output("isCounted")]
        public Output<bool> IsCounted { get; private set; } = null!;

        /// <summary>
        /// Whether to resolve names using DNS64.
        /// </summary>
        [Output("isDns64")]
        public Output<bool> IsDns64 { get; private set; } = null!;

        /// <summary>
        /// Whether to drop A record responses from requests for this domain.
        /// </summary>
        [Output("isDropA")]
        public Output<bool> IsDropA { get; private set; } = null!;

        /// <summary>
        /// Whether all record responses for this domain should be dropped.
        /// </summary>
        [Output("isDropAll")]
        public Output<bool> IsDropAll { get; private set; } = null!;

        /// <summary>
        /// Whether to log all requests for names in this domain.
        /// </summary>
        [Output("isLog")]
        public Output<bool> IsLog { get; private set; } = null!;

        /// <summary>
        /// Whether this domain should be treated as a search domain.
        /// </summary>
        [Output("isSearchDomain")]
        public Output<bool> IsSearchDomain { get; private set; } = null!;

        /// <summary>
        /// Metadata about the last time a write API was called by this provider for this resource.
        /// </summary>
        [Output("lastUpdated")]
        public Output<string> LastUpdated { get; private set; } = null!;

        /// <summary>
        /// The DNS zone name you wish to target. Example: `example.com`
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Provider Metadata storing extra API data about the upstream servers for this domain
        /// </summary>
        [Output("servers")]
        public Output<ImmutableArray<Outputs.DnsServer>> Servers { get; private set; } = null!;


        /// <summary>
        /// Create a Dns resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Dns(string name, DnsArgs args, CustomResourceOptions? options = null)
            : base("bowtie:index/dns:Dns", name, args ?? new DnsArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Dns(string name, Input<string> id, DnsState? state = null, CustomResourceOptions? options = null)
            : base("bowtie:index/dns:Dns", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Dns resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Dns Get(string name, Input<string> id, DnsState? state = null, CustomResourceOptions? options = null)
        {
            return new Dns(name, id, state, options);
        }
    }

    public sealed class DnsArgs : global::Pulumi.ResourceArgs
    {
        [Input("excludes")]
        private InputList<Inputs.DnsExcludeArgs>? _excludes;

        /// <summary>
        /// Names under this domain to exclude from resolution.
        /// </summary>
        public InputList<Inputs.DnsExcludeArgs> Excludes
        {
            get => _excludes ?? (_excludes = new InputList<Inputs.DnsExcludeArgs>());
            set => _excludes = value;
        }

        [Input("includeOnlySites")]
        private InputList<string>? _includeOnlySites;

        /// <summary>
        /// Limit name resolution for this domain only to these sites.
        /// </summary>
        public InputList<string> IncludeOnlySites
        {
            get => _includeOnlySites ?? (_includeOnlySites = new InputList<string>());
            set => _includeOnlySites = value;
        }

        /// <summary>
        /// Whether to only log metrics for this domain and not all requests.
        /// </summary>
        [Input("isCounted")]
        public Input<bool>? IsCounted { get; set; }

        /// <summary>
        /// Whether to resolve names using DNS64.
        /// </summary>
        [Input("isDns64")]
        public Input<bool>? IsDns64 { get; set; }

        /// <summary>
        /// Whether to drop A record responses from requests for this domain.
        /// </summary>
        [Input("isDropA")]
        public Input<bool>? IsDropA { get; set; }

        /// <summary>
        /// Whether all record responses for this domain should be dropped.
        /// </summary>
        [Input("isDropAll")]
        public Input<bool>? IsDropAll { get; set; }

        /// <summary>
        /// Whether to log all requests for names in this domain.
        /// </summary>
        [Input("isLog")]
        public Input<bool>? IsLog { get; set; }

        /// <summary>
        /// Whether this domain should be treated as a search domain.
        /// </summary>
        [Input("isSearchDomain")]
        public Input<bool>? IsSearchDomain { get; set; }

        /// <summary>
        /// The DNS zone name you wish to target. Example: `example.com`
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("servers", required: true)]
        private InputList<Inputs.DnsServerArgs>? _servers;

        /// <summary>
        /// Provider Metadata storing extra API data about the upstream servers for this domain
        /// </summary>
        public InputList<Inputs.DnsServerArgs> Servers
        {
            get => _servers ?? (_servers = new InputList<Inputs.DnsServerArgs>());
            set => _servers = value;
        }

        public DnsArgs()
        {
        }
        public static new DnsArgs Empty => new DnsArgs();
    }

    public sealed class DnsState : global::Pulumi.ResourceArgs
    {
        [Input("excludes")]
        private InputList<Inputs.DnsExcludeGetArgs>? _excludes;

        /// <summary>
        /// Names under this domain to exclude from resolution.
        /// </summary>
        public InputList<Inputs.DnsExcludeGetArgs> Excludes
        {
            get => _excludes ?? (_excludes = new InputList<Inputs.DnsExcludeGetArgs>());
            set => _excludes = value;
        }

        [Input("includeOnlySites")]
        private InputList<string>? _includeOnlySites;

        /// <summary>
        /// Limit name resolution for this domain only to these sites.
        /// </summary>
        public InputList<string> IncludeOnlySites
        {
            get => _includeOnlySites ?? (_includeOnlySites = new InputList<string>());
            set => _includeOnlySites = value;
        }

        /// <summary>
        /// Whether to only log metrics for this domain and not all requests.
        /// </summary>
        [Input("isCounted")]
        public Input<bool>? IsCounted { get; set; }

        /// <summary>
        /// Whether to resolve names using DNS64.
        /// </summary>
        [Input("isDns64")]
        public Input<bool>? IsDns64 { get; set; }

        /// <summary>
        /// Whether to drop A record responses from requests for this domain.
        /// </summary>
        [Input("isDropA")]
        public Input<bool>? IsDropA { get; set; }

        /// <summary>
        /// Whether all record responses for this domain should be dropped.
        /// </summary>
        [Input("isDropAll")]
        public Input<bool>? IsDropAll { get; set; }

        /// <summary>
        /// Whether to log all requests for names in this domain.
        /// </summary>
        [Input("isLog")]
        public Input<bool>? IsLog { get; set; }

        /// <summary>
        /// Whether this domain should be treated as a search domain.
        /// </summary>
        [Input("isSearchDomain")]
        public Input<bool>? IsSearchDomain { get; set; }

        /// <summary>
        /// Metadata about the last time a write API was called by this provider for this resource.
        /// </summary>
        [Input("lastUpdated")]
        public Input<string>? LastUpdated { get; set; }

        /// <summary>
        /// The DNS zone name you wish to target. Example: `example.com`
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        [Input("servers")]
        private InputList<Inputs.DnsServerGetArgs>? _servers;

        /// <summary>
        /// Provider Metadata storing extra API data about the upstream servers for this domain
        /// </summary>
        public InputList<Inputs.DnsServerGetArgs> Servers
        {
            get => _servers ?? (_servers = new InputList<Inputs.DnsServerGetArgs>());
            set => _servers = value;
        }

        public DnsState()
        {
        }
        public static new DnsState Empty => new DnsState();
    }
}
