// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Bowtie
{
    public static class GetCollection
    {
        public static Task<GetCollectionResult> InvokeAsync(GetCollectionArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetCollectionResult>("bowtie:index/getCollection:getCollection", args ?? new GetCollectionArgs(), options.WithDefaults());

        public static Output<GetCollectionResult> Invoke(GetCollectionInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetCollectionResult>("bowtie:index/getCollection:getCollection", args ?? new GetCollectionInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetCollectionArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetCollectionArgs()
        {
        }
        public static new GetCollectionArgs Empty => new GetCollectionArgs();
    }

    public sealed class GetCollectionInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GetCollectionInvokeArgs()
        {
        }
        public static new GetCollectionInvokeArgs Empty => new GetCollectionInvokeArgs();
    }


    [OutputType]
    public sealed class GetCollectionResult
    {
        public readonly string Description;
        public readonly string Id;
        public readonly string Name;

        [OutputConstructor]
        private GetCollectionResult(
            string description,

            string id,

            string name)
        {
            Description = description;
            Id = id;
            Name = name;
        }
    }
}
