// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Bowtie
{
    public static class GetDeviceGroup
    {
        public static Task<GetDeviceGroupResult> InvokeAsync(GetDeviceGroupArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetDeviceGroupResult>("bowtie:index/getDeviceGroup:getDeviceGroup", args ?? new GetDeviceGroupArgs(), options.WithDefaults());

        public static Output<GetDeviceGroupResult> Invoke(GetDeviceGroupInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetDeviceGroupResult>("bowtie:index/getDeviceGroup:getDeviceGroup", args ?? new GetDeviceGroupInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetDeviceGroupArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public string Name { get; set; } = null!;

        public GetDeviceGroupArgs()
        {
        }
        public static new GetDeviceGroupArgs Empty => new GetDeviceGroupArgs();
    }

    public sealed class GetDeviceGroupInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public GetDeviceGroupInvokeArgs()
        {
        }
        public static new GetDeviceGroupInvokeArgs Empty => new GetDeviceGroupInvokeArgs();
    }


    [OutputType]
    public sealed class GetDeviceGroupResult
    {
        public readonly string Description;
        public readonly string Id;
        public readonly string Name;

        [OutputConstructor]
        private GetDeviceGroupResult(
            string description,

            string id,

            string name)
        {
            Description = description;
            Id = id;
            Name = name;
        }
    }
}
