// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Bowtie
{
    public static class GetUser
    {
        public static Task<GetUserResult> InvokeAsync(GetUserArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetUserResult>("bowtie:index/getUser:getUser", args ?? new GetUserArgs(), options.WithDefaults());

        public static Output<GetUserResult> Invoke(GetUserInvokeArgs args, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetUserResult>("bowtie:index/getUser:getUser", args ?? new GetUserInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetUserArgs : global::Pulumi.InvokeArgs
    {
        [Input("email", required: true)]
        public string Email { get; set; } = null!;

        public GetUserArgs()
        {
        }
        public static new GetUserArgs Empty => new GetUserArgs();
    }

    public sealed class GetUserInvokeArgs : global::Pulumi.InvokeArgs
    {
        [Input("email", required: true)]
        public Input<string> Email { get; set; } = null!;

        public GetUserInvokeArgs()
        {
        }
        public static new GetUserInvokeArgs Empty => new GetUserInvokeArgs();
    }


    [OutputType]
    public sealed class GetUserResult
    {
        public readonly bool AuthzControlPlane;
        public readonly bool AuthzDevices;
        public readonly bool AuthzPolicies;
        public readonly bool AuthzUsers;
        public readonly string Email;
        public readonly string Id;
        public readonly string Name;
        public readonly string Status;

        [OutputConstructor]
        private GetUserResult(
            bool authzControlPlane,

            bool authzDevices,

            bool authzPolicies,

            bool authzUsers,

            string email,

            string id,

            string name,

            string status)
        {
            AuthzControlPlane = authzControlPlane;
            AuthzDevices = authzDevices;
            AuthzPolicies = authzPolicies;
            AuthzUsers = authzUsers;
            Email = email;
            Id = id;
            Name = name;
            Status = status;
        }
    }
}
