// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Bowtie
{
    [BowtieResourceType("bowtie:index/ipv6Range:Ipv6Range")]
    public partial class Ipv6Range : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Whether the Controller assigns addresses to devices from this pool.
        /// </summary>
        [Output("assignAddressesFromHere")]
        public Output<bool> AssignAddressesFromHere { get; private set; } = null!;

        [Output("lastUpdated")]
        public Output<string> LastUpdated { get; private set; } = null!;

        /// <summary>
        /// The IPv6 CIDR for the pool, for example `fd00:1:1:5678::/64`. Generated by the Controller when unset.
        /// </summary>
        [Output("range")]
        public Output<string> Range { get; private set; } = null!;


        /// <summary>
        /// Create a Ipv6Range resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Ipv6Range(string name, Ipv6RangeArgs args, CustomResourceOptions? options = null)
            : base("bowtie:index/ipv6Range:Ipv6Range", name, args ?? new Ipv6RangeArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Ipv6Range(string name, Input<string> id, Ipv6RangeState? state = null, CustomResourceOptions? options = null)
            : base("bowtie:index/ipv6Range:Ipv6Range", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Ipv6Range resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Ipv6Range Get(string name, Input<string> id, Ipv6RangeState? state = null, CustomResourceOptions? options = null)
        {
            return new Ipv6Range(name, id, state, options);
        }
    }

    public sealed class Ipv6RangeArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether the Controller assigns addresses to devices from this pool.
        /// </summary>
        [Input("assignAddressesFromHere", required: true)]
        public Input<bool> AssignAddressesFromHere { get; set; } = null!;

        /// <summary>
        /// The IPv6 CIDR for the pool, for example `fd00:1:1:5678::/64`. Generated by the Controller when unset.
        /// </summary>
        [Input("range")]
        public Input<string>? Range { get; set; }

        public Ipv6RangeArgs()
        {
        }
        public static new Ipv6RangeArgs Empty => new Ipv6RangeArgs();
    }

    public sealed class Ipv6RangeState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether the Controller assigns addresses to devices from this pool.
        /// </summary>
        [Input("assignAddressesFromHere")]
        public Input<bool>? AssignAddressesFromHere { get; set; }

        [Input("lastUpdated")]
        public Input<string>? LastUpdated { get; set; }

        /// <summary>
        /// The IPv6 CIDR for the pool, for example `fd00:1:1:5678::/64`. Generated by the Controller when unset.
        /// </summary>
        [Input("range")]
        public Input<string>? Range { get; set; }

        public Ipv6RangeState()
        {
        }
        public static new Ipv6RangeState Empty => new Ipv6RangeState();
    }
}
