// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Bowtie
{
    [BowtieResourceType("bowtie:index/orgConfig:OrgConfig")]
    public partial class OrgConfig : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Automatically admit a Controller that presents a valid pre-shared key, for zero-touch cluster scale-out.
        /// </summary>
        [Output("allowControllerApprovalWithPskOnly")]
        public Output<bool> AllowControllerApprovalWithPskOnly { get; private set; } = null!;

        /// <summary>
        /// Automatically approve a device when its user authenticates after installing the client.
        /// </summary>
        [Output("allowDeviceApprovalOnUserAuth")]
        public Output<bool> AllowDeviceApprovalOnUserAuth { get; private set; } = null!;

        /// <summary>
        /// Organization default for how Controllers listen on the SSH port: `any`, `local-only`, or `tunnel-only`.
        /// </summary>
        [Output("controllerSshListener")]
        public Output<string> ControllerSshListener { get; private set; } = null!;

        /// <summary>
        /// Default for considering pre-release versions when Controllers do not specify their own value.
        /// </summary>
        [Output("controllerVersionIncludePrereleases")]
        public Output<bool> ControllerVersionIncludePrereleases { get; private set; } = null!;

        /// <summary>
        /// Default minimum age, in days, a release must have before adoption under a latest-version strategy.
        /// </summary>
        [Output("controllerVersionMinimumAge")]
        public Output<int> ControllerVersionMinimumAge { get; private set; } = null!;

        /// <summary>
        /// Organization default update stagger: `no-delay`, `randomized-delay`, or `consistent-randomized-delay`.
        /// </summary>
        [Output("controllerVersionSplayType")]
        public Output<string> ControllerVersionSplayType { get; private set; } = null!;

        /// <summary>
        /// A systemd time-span for `randomized-delay` and `consistent-randomized-delay`.
        /// </summary>
        [Output("controllerVersionSplayValue")]
        public Output<string> ControllerVersionSplayValue { get; private set; } = null!;

        /// <summary>
        /// Organization default update strategy: `manual`, `specific`, `newest-at-interval`, or `newest-at-calendar`.
        /// (`org-default` is not valid here; the organization default cannot itself defer to the organization default.)
        /// </summary>
        [Output("controllerVersionStrategyType")]
        public Output<string> ControllerVersionStrategyType { get; private set; } = null!;

        /// <summary>
        /// Value for the default update strategy when it requires one (a version, time-span, or calendar expression).
        /// </summary>
        [Output("controllerVersionStrategyValue")]
        public Output<string> ControllerVersionStrategyValue { get; private set; } = null!;

        /// <summary>
        /// Delete devices that have not checked in for more than this many days. Must be greater than 7.
        /// </summary>
        [Output("deleteDevicesMoreStaleThanDays")]
        public Output<int> DeleteDevicesMoreStaleThanDays { get; private set; } = null!;

        /// <summary>
        /// When false, destructive device cleanup only proceeds when a quorum of Controller peers is connected.
        /// </summary>
        [Output("disablePeersRequireQuorum")]
        public Output<bool> DisablePeersRequireQuorum { get; private set; } = null!;

        [Output("lastUpdated")]
        public Output<string> LastUpdated { get; private set; } = null!;

        /// <summary>
        /// Percentage (0-100) of Controller peers required for quorum. Default 51.
        /// </summary>
        [Output("peersRequireQuorumPercentage")]
        public Output<int> PeersRequireQuorumPercentage { get; private set; } = null!;

        /// <summary>
        /// Revoke approval for devices that have not checked in for more than this many days. Must be greater than 7.
        /// </summary>
        [Output("removeApprovalDevicesMoreStaleThanDays")]
        public Output<int> RemoveApprovalDevicesMoreStaleThanDays { get; private set; } = null!;

        /// <summary>
        /// Disassociate a device from its user after this many minutes.
        /// </summary>
        [Output("userDeviceDisassociationMinutes")]
        public Output<int> UserDeviceDisassociationMinutes { get; private set; } = null!;


        /// <summary>
        /// Create a OrgConfig resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public OrgConfig(string name, OrgConfigArgs? args = null, CustomResourceOptions? options = null)
            : base("bowtie:index/orgConfig:OrgConfig", name, args ?? new OrgConfigArgs(), MakeResourceOptions(options, ""))
        {
        }

        private OrgConfig(string name, Input<string> id, OrgConfigState? state = null, CustomResourceOptions? options = null)
            : base("bowtie:index/orgConfig:OrgConfig", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing OrgConfig resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static OrgConfig Get(string name, Input<string> id, OrgConfigState? state = null, CustomResourceOptions? options = null)
        {
            return new OrgConfig(name, id, state, options);
        }
    }

    public sealed class OrgConfigArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Automatically admit a Controller that presents a valid pre-shared key, for zero-touch cluster scale-out.
        /// </summary>
        [Input("allowControllerApprovalWithPskOnly")]
        public Input<bool>? AllowControllerApprovalWithPskOnly { get; set; }

        /// <summary>
        /// Automatically approve a device when its user authenticates after installing the client.
        /// </summary>
        [Input("allowDeviceApprovalOnUserAuth")]
        public Input<bool>? AllowDeviceApprovalOnUserAuth { get; set; }

        /// <summary>
        /// Organization default for how Controllers listen on the SSH port: `any`, `local-only`, or `tunnel-only`.
        /// </summary>
        [Input("controllerSshListener")]
        public Input<string>? ControllerSshListener { get; set; }

        /// <summary>
        /// Default for considering pre-release versions when Controllers do not specify their own value.
        /// </summary>
        [Input("controllerVersionIncludePrereleases")]
        public Input<bool>? ControllerVersionIncludePrereleases { get; set; }

        /// <summary>
        /// Default minimum age, in days, a release must have before adoption under a latest-version strategy.
        /// </summary>
        [Input("controllerVersionMinimumAge")]
        public Input<int>? ControllerVersionMinimumAge { get; set; }

        /// <summary>
        /// Organization default update stagger: `no-delay`, `randomized-delay`, or `consistent-randomized-delay`.
        /// </summary>
        [Input("controllerVersionSplayType")]
        public Input<string>? ControllerVersionSplayType { get; set; }

        /// <summary>
        /// A systemd time-span for `randomized-delay` and `consistent-randomized-delay`.
        /// </summary>
        [Input("controllerVersionSplayValue")]
        public Input<string>? ControllerVersionSplayValue { get; set; }

        /// <summary>
        /// Organization default update strategy: `manual`, `specific`, `newest-at-interval`, or `newest-at-calendar`.
        /// (`org-default` is not valid here; the organization default cannot itself defer to the organization default.)
        /// </summary>
        [Input("controllerVersionStrategyType")]
        public Input<string>? ControllerVersionStrategyType { get; set; }

        /// <summary>
        /// Value for the default update strategy when it requires one (a version, time-span, or calendar expression).
        /// </summary>
        [Input("controllerVersionStrategyValue")]
        public Input<string>? ControllerVersionStrategyValue { get; set; }

        /// <summary>
        /// Delete devices that have not checked in for more than this many days. Must be greater than 7.
        /// </summary>
        [Input("deleteDevicesMoreStaleThanDays")]
        public Input<int>? DeleteDevicesMoreStaleThanDays { get; set; }

        /// <summary>
        /// When false, destructive device cleanup only proceeds when a quorum of Controller peers is connected.
        /// </summary>
        [Input("disablePeersRequireQuorum")]
        public Input<bool>? DisablePeersRequireQuorum { get; set; }

        /// <summary>
        /// Percentage (0-100) of Controller peers required for quorum. Default 51.
        /// </summary>
        [Input("peersRequireQuorumPercentage")]
        public Input<int>? PeersRequireQuorumPercentage { get; set; }

        /// <summary>
        /// Revoke approval for devices that have not checked in for more than this many days. Must be greater than 7.
        /// </summary>
        [Input("removeApprovalDevicesMoreStaleThanDays")]
        public Input<int>? RemoveApprovalDevicesMoreStaleThanDays { get; set; }

        /// <summary>
        /// Disassociate a device from its user after this many minutes.
        /// </summary>
        [Input("userDeviceDisassociationMinutes")]
        public Input<int>? UserDeviceDisassociationMinutes { get; set; }

        public OrgConfigArgs()
        {
        }
        public static new OrgConfigArgs Empty => new OrgConfigArgs();
    }

    public sealed class OrgConfigState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Automatically admit a Controller that presents a valid pre-shared key, for zero-touch cluster scale-out.
        /// </summary>
        [Input("allowControllerApprovalWithPskOnly")]
        public Input<bool>? AllowControllerApprovalWithPskOnly { get; set; }

        /// <summary>
        /// Automatically approve a device when its user authenticates after installing the client.
        /// </summary>
        [Input("allowDeviceApprovalOnUserAuth")]
        public Input<bool>? AllowDeviceApprovalOnUserAuth { get; set; }

        /// <summary>
        /// Organization default for how Controllers listen on the SSH port: `any`, `local-only`, or `tunnel-only`.
        /// </summary>
        [Input("controllerSshListener")]
        public Input<string>? ControllerSshListener { get; set; }

        /// <summary>
        /// Default for considering pre-release versions when Controllers do not specify their own value.
        /// </summary>
        [Input("controllerVersionIncludePrereleases")]
        public Input<bool>? ControllerVersionIncludePrereleases { get; set; }

        /// <summary>
        /// Default minimum age, in days, a release must have before adoption under a latest-version strategy.
        /// </summary>
        [Input("controllerVersionMinimumAge")]
        public Input<int>? ControllerVersionMinimumAge { get; set; }

        /// <summary>
        /// Organization default update stagger: `no-delay`, `randomized-delay`, or `consistent-randomized-delay`.
        /// </summary>
        [Input("controllerVersionSplayType")]
        public Input<string>? ControllerVersionSplayType { get; set; }

        /// <summary>
        /// A systemd time-span for `randomized-delay` and `consistent-randomized-delay`.
        /// </summary>
        [Input("controllerVersionSplayValue")]
        public Input<string>? ControllerVersionSplayValue { get; set; }

        /// <summary>
        /// Organization default update strategy: `manual`, `specific`, `newest-at-interval`, or `newest-at-calendar`.
        /// (`org-default` is not valid here; the organization default cannot itself defer to the organization default.)
        /// </summary>
        [Input("controllerVersionStrategyType")]
        public Input<string>? ControllerVersionStrategyType { get; set; }

        /// <summary>
        /// Value for the default update strategy when it requires one (a version, time-span, or calendar expression).
        /// </summary>
        [Input("controllerVersionStrategyValue")]
        public Input<string>? ControllerVersionStrategyValue { get; set; }

        /// <summary>
        /// Delete devices that have not checked in for more than this many days. Must be greater than 7.
        /// </summary>
        [Input("deleteDevicesMoreStaleThanDays")]
        public Input<int>? DeleteDevicesMoreStaleThanDays { get; set; }

        /// <summary>
        /// When false, destructive device cleanup only proceeds when a quorum of Controller peers is connected.
        /// </summary>
        [Input("disablePeersRequireQuorum")]
        public Input<bool>? DisablePeersRequireQuorum { get; set; }

        [Input("lastUpdated")]
        public Input<string>? LastUpdated { get; set; }

        /// <summary>
        /// Percentage (0-100) of Controller peers required for quorum. Default 51.
        /// </summary>
        [Input("peersRequireQuorumPercentage")]
        public Input<int>? PeersRequireQuorumPercentage { get; set; }

        /// <summary>
        /// Revoke approval for devices that have not checked in for more than this many days. Must be greater than 7.
        /// </summary>
        [Input("removeApprovalDevicesMoreStaleThanDays")]
        public Input<int>? RemoveApprovalDevicesMoreStaleThanDays { get; set; }

        /// <summary>
        /// Disassociate a device from its user after this many minutes.
        /// </summary>
        [Input("userDeviceDisassociationMinutes")]
        public Input<int>? UserDeviceDisassociationMinutes { get; set; }

        public OrgConfigState()
        {
        }
        public static new OrgConfigState Empty => new OrgConfigState();
    }
}
