// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Bowtie
{
    [BowtieResourceType("bowtie:index/policy:Policy")]
    public partial class Policy : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The action to take on matching traffic: `Accept`, `Reject` (deny with feedback), or `Drop` (deny silently).
        /// </summary>
        [Output("action")]
        public Output<string> Action { get; private set; } = null!;

        /// <summary>
        /// The ID of the resource group this policy controls access to.
        /// </summary>
        [Output("dest")]
        public Output<string> Dest { get; private set; } = null!;

        /// <summary>
        /// Evaluation order of the policy. When omitted, the Controller appends the policy to the end of the list.
        /// </summary>
        [Output("order")]
        public Output<int> Order { get; private set; } = null!;

        /// <summary>
        /// The set of devices this policy applies to. Set exactly one of the leaf matchers (`always`, `authenticated_user`, `user`,
        /// `device`, `user_group`, `device_group`) or exactly one of the boolean groups (`and`, `or`, `nor`).
        /// </summary>
        [Output("source")]
        public Output<Outputs.PolicySource> Source { get; private set; } = null!;

        /// <summary>
        /// Whether the policy is `Enabled` or `Disabled`. Defaults to `Enabled`.
        /// </summary>
        [Output("status")]
        public Output<string> Status { get; private set; } = null!;


        /// <summary>
        /// Create a Policy resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public Policy(string name, PolicyArgs args, CustomResourceOptions? options = null)
            : base("bowtie:index/policy:Policy", name, args ?? new PolicyArgs(), MakeResourceOptions(options, ""))
        {
        }

        private Policy(string name, Input<string> id, PolicyState? state = null, CustomResourceOptions? options = null)
            : base("bowtie:index/policy:Policy", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing Policy resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static Policy Get(string name, Input<string> id, PolicyState? state = null, CustomResourceOptions? options = null)
        {
            return new Policy(name, id, state, options);
        }
    }

    public sealed class PolicyArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The action to take on matching traffic: `Accept`, `Reject` (deny with feedback), or `Drop` (deny silently).
        /// </summary>
        [Input("action", required: true)]
        public Input<string> Action { get; set; } = null!;

        /// <summary>
        /// The ID of the resource group this policy controls access to.
        /// </summary>
        [Input("dest", required: true)]
        public Input<string> Dest { get; set; } = null!;

        /// <summary>
        /// Evaluation order of the policy. When omitted, the Controller appends the policy to the end of the list.
        /// </summary>
        [Input("order")]
        public Input<int>? Order { get; set; }

        /// <summary>
        /// The set of devices this policy applies to. Set exactly one of the leaf matchers (`always`, `authenticated_user`, `user`,
        /// `device`, `user_group`, `device_group`) or exactly one of the boolean groups (`and`, `or`, `nor`).
        /// </summary>
        [Input("source", required: true)]
        public Input<Inputs.PolicySourceArgs> Source { get; set; } = null!;

        /// <summary>
        /// Whether the policy is `Enabled` or `Disabled`. Defaults to `Enabled`.
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        public PolicyArgs()
        {
        }
        public static new PolicyArgs Empty => new PolicyArgs();
    }

    public sealed class PolicyState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The action to take on matching traffic: `Accept`, `Reject` (deny with feedback), or `Drop` (deny silently).
        /// </summary>
        [Input("action")]
        public Input<string>? Action { get; set; }

        /// <summary>
        /// The ID of the resource group this policy controls access to.
        /// </summary>
        [Input("dest")]
        public Input<string>? Dest { get; set; }

        /// <summary>
        /// Evaluation order of the policy. When omitted, the Controller appends the policy to the end of the list.
        /// </summary>
        [Input("order")]
        public Input<int>? Order { get; set; }

        /// <summary>
        /// The set of devices this policy applies to. Set exactly one of the leaf matchers (`always`, `authenticated_user`, `user`,
        /// `device`, `user_group`, `device_group`) or exactly one of the boolean groups (`and`, `or`, `nor`).
        /// </summary>
        [Input("source")]
        public Input<Inputs.PolicySourceGetArgs>? Source { get; set; }

        /// <summary>
        /// Whether the policy is `Enabled` or `Disabled`. Defaults to `Enabled`.
        /// </summary>
        [Input("status")]
        public Input<string>? Status { get; set; }

        public PolicyState()
        {
        }
        public static new PolicyState Empty => new PolicyState();
    }
}
