// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Bowtie
{
    [BowtieResourceType("bowtie:index/siteRange:SiteRange")]
    public partial class SiteRange : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Long-form description for this site.
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// The IPv4 CIDR range for this site range. **Mutually exclusive with `ipv6_range`**.
        /// </summary>
        [Output("ipv4Range")]
        public Output<string?> Ipv4Range { get; private set; } = null!;

        /// <summary>
        /// The IPv6 CIDR range for this site range. **Mutually exclusive with `ipv4_range`**.
        /// </summary>
        [Output("ipv6Range")]
        public Output<string?> Ipv6Range { get; private set; } = null!;

        [Output("lastUpdated")]
        public Output<string> LastUpdated { get; private set; } = null!;

        /// <summary>
        /// The metric for this range. Currently unused but may be in future updates.
        /// </summary>
        [Output("metric")]
        public Output<int> Metric { get; private set; } = null!;

        /// <summary>
        /// The human readable name of this range.
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// The Site ID that this range should be associated with.
        /// </summary>
        [Output("siteId")]
        public Output<string> SiteId { get; private set; } = null!;

        /// <summary>
        /// The weight for this range. Currently unused but may be in future updates.
        /// </summary>
        [Output("weight")]
        public Output<int> Weight { get; private set; } = null!;


        /// <summary>
        /// Create a SiteRange resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public SiteRange(string name, SiteRangeArgs args, CustomResourceOptions? options = null)
            : base("bowtie:index/siteRange:SiteRange", name, args ?? new SiteRangeArgs(), MakeResourceOptions(options, ""))
        {
        }

        private SiteRange(string name, Input<string> id, SiteRangeState? state = null, CustomResourceOptions? options = null)
            : base("bowtie:index/siteRange:SiteRange", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing SiteRange resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static SiteRange Get(string name, Input<string> id, SiteRangeState? state = null, CustomResourceOptions? options = null)
        {
            return new SiteRange(name, id, state, options);
        }
    }

    public sealed class SiteRangeArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Long-form description for this site.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The IPv4 CIDR range for this site range. **Mutually exclusive with `ipv6_range`**.
        /// </summary>
        [Input("ipv4Range")]
        public Input<string>? Ipv4Range { get; set; }

        /// <summary>
        /// The IPv6 CIDR range for this site range. **Mutually exclusive with `ipv4_range`**.
        /// </summary>
        [Input("ipv6Range")]
        public Input<string>? Ipv6Range { get; set; }

        /// <summary>
        /// The metric for this range. Currently unused but may be in future updates.
        /// </summary>
        [Input("metric")]
        public Input<int>? Metric { get; set; }

        /// <summary>
        /// The human readable name of this range.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The Site ID that this range should be associated with.
        /// </summary>
        [Input("siteId", required: true)]
        public Input<string> SiteId { get; set; } = null!;

        /// <summary>
        /// The weight for this range. Currently unused but may be in future updates.
        /// </summary>
        [Input("weight")]
        public Input<int>? Weight { get; set; }

        public SiteRangeArgs()
        {
        }
        public static new SiteRangeArgs Empty => new SiteRangeArgs();
    }

    public sealed class SiteRangeState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Long-form description for this site.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The IPv4 CIDR range for this site range. **Mutually exclusive with `ipv6_range`**.
        /// </summary>
        [Input("ipv4Range")]
        public Input<string>? Ipv4Range { get; set; }

        /// <summary>
        /// The IPv6 CIDR range for this site range. **Mutually exclusive with `ipv4_range`**.
        /// </summary>
        [Input("ipv6Range")]
        public Input<string>? Ipv6Range { get; set; }

        [Input("lastUpdated")]
        public Input<string>? LastUpdated { get; set; }

        /// <summary>
        /// The metric for this range. Currently unused but may be in future updates.
        /// </summary>
        [Input("metric")]
        public Input<int>? Metric { get; set; }

        /// <summary>
        /// The human readable name of this range.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The Site ID that this range should be associated with.
        /// </summary>
        [Input("siteId")]
        public Input<string>? SiteId { get; set; }

        /// <summary>
        /// The weight for this range. Currently unused but may be in future updates.
        /// </summary>
        [Input("weight")]
        public Input<int>? Weight { get; set; }

        public SiteRangeState()
        {
        }
        public static new SiteRangeState Empty => new SiteRangeState();
    }
}
