# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .collection import *
from .controller import *
from .device_group import *
from .dns import *
from .dns_block_list import *
from .get_collection import *
from .get_device import *
from .get_device_group import *
from .get_group import *
from .get_resource_group import *
from .get_user import *
from .group import *
from .group_membership import *
from .ipv4_range import *
from .ipv6_range import *
from .org_config import *
from .organization import *
from .policy import *
from .provider import *
from .resource import *
from .resource_group import *
from .route_exclusion import *
from .site import *
from .site_range import *
from .user import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_bowtie.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_bowtie.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "bowtie",
  "mod": "index/collection",
  "fqn": "pulumi_bowtie",
  "classes": {
   "bowtie:index/collection:Collection": "Collection"
  }
 },
 {
  "pkg": "bowtie",
  "mod": "index/controller",
  "fqn": "pulumi_bowtie",
  "classes": {
   "bowtie:index/controller:Controller": "Controller"
  }
 },
 {
  "pkg": "bowtie",
  "mod": "index/deviceGroup",
  "fqn": "pulumi_bowtie",
  "classes": {
   "bowtie:index/deviceGroup:DeviceGroup": "DeviceGroup"
  }
 },
 {
  "pkg": "bowtie",
  "mod": "index/dns",
  "fqn": "pulumi_bowtie",
  "classes": {
   "bowtie:index/dns:Dns": "Dns"
  }
 },
 {
  "pkg": "bowtie",
  "mod": "index/dnsBlockList",
  "fqn": "pulumi_bowtie",
  "classes": {
   "bowtie:index/dnsBlockList:DnsBlockList": "DnsBlockList"
  }
 },
 {
  "pkg": "bowtie",
  "mod": "index/group",
  "fqn": "pulumi_bowtie",
  "classes": {
   "bowtie:index/group:Group": "Group"
  }
 },
 {
  "pkg": "bowtie",
  "mod": "index/groupMembership",
  "fqn": "pulumi_bowtie",
  "classes": {
   "bowtie:index/groupMembership:GroupMembership": "GroupMembership"
  }
 },
 {
  "pkg": "bowtie",
  "mod": "index/ipv4Range",
  "fqn": "pulumi_bowtie",
  "classes": {
   "bowtie:index/ipv4Range:Ipv4Range": "Ipv4Range"
  }
 },
 {
  "pkg": "bowtie",
  "mod": "index/ipv6Range",
  "fqn": "pulumi_bowtie",
  "classes": {
   "bowtie:index/ipv6Range:Ipv6Range": "Ipv6Range"
  }
 },
 {
  "pkg": "bowtie",
  "mod": "index/orgConfig",
  "fqn": "pulumi_bowtie",
  "classes": {
   "bowtie:index/orgConfig:OrgConfig": "OrgConfig"
  }
 },
 {
  "pkg": "bowtie",
  "mod": "index/organization",
  "fqn": "pulumi_bowtie",
  "classes": {
   "bowtie:index/organization:Organization": "Organization"
  }
 },
 {
  "pkg": "bowtie",
  "mod": "index/policy",
  "fqn": "pulumi_bowtie",
  "classes": {
   "bowtie:index/policy:Policy": "Policy"
  }
 },
 {
  "pkg": "bowtie",
  "mod": "index/resource",
  "fqn": "pulumi_bowtie",
  "classes": {
   "bowtie:index/resource:Resource": "Resource"
  }
 },
 {
  "pkg": "bowtie",
  "mod": "index/resourceGroup",
  "fqn": "pulumi_bowtie",
  "classes": {
   "bowtie:index/resourceGroup:ResourceGroup": "ResourceGroup"
  }
 },
 {
  "pkg": "bowtie",
  "mod": "index/routeExclusion",
  "fqn": "pulumi_bowtie",
  "classes": {
   "bowtie:index/routeExclusion:RouteExclusion": "RouteExclusion"
  }
 },
 {
  "pkg": "bowtie",
  "mod": "index/site",
  "fqn": "pulumi_bowtie",
  "classes": {
   "bowtie:index/site:Site": "Site"
  }
 },
 {
  "pkg": "bowtie",
  "mod": "index/siteRange",
  "fqn": "pulumi_bowtie",
  "classes": {
   "bowtie:index/siteRange:SiteRange": "SiteRange"
  }
 },
 {
  "pkg": "bowtie",
  "mod": "index/user",
  "fqn": "pulumi_bowtie",
  "classes": {
   "bowtie:index/user:User": "User"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "bowtie",
  "token": "pulumi:providers:bowtie",
  "fqn": "pulumi_bowtie",
  "class": "Provider"
 }
]
"""
)
