# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['DnsBlockListArgs', 'DnsBlockList']

@pulumi.input_type
class DnsBlockListArgs:
    def __init__(__self__, *,
                 name: Optional[pulumi.Input[str]] = None,
                 override_to_allows: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 upstream: Optional[pulumi.Input[str]] = None):
        """
        The set of arguments for constructing a DnsBlockList resource.
        :param pulumi.Input[str] name: The human readable name of the block list.
        :param pulumi.Input[Sequence[pulumi.Input[str]]] override_to_allows: Optional list of DNS names to exclude from any retrieved DNS block lists.
        :param pulumi.Input[str] upstream: An upstream URL that returns a DNS block list.
        """
        if name is not None:
            pulumi.set(__self__, "name", name)
        if override_to_allows is not None:
            pulumi.set(__self__, "override_to_allows", override_to_allows)
        if upstream is not None:
            pulumi.set(__self__, "upstream", upstream)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[str]]:
        """
        The human readable name of the block list.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter(name="overrideToAllows")
    def override_to_allows(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]:
        """
        Optional list of DNS names to exclude from any retrieved DNS block lists.
        """
        return pulumi.get(self, "override_to_allows")

    @override_to_allows.setter
    def override_to_allows(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]):
        pulumi.set(self, "override_to_allows", value)

    @property
    @pulumi.getter
    def upstream(self) -> Optional[pulumi.Input[str]]:
        """
        An upstream URL that returns a DNS block list.
        """
        return pulumi.get(self, "upstream")

    @upstream.setter
    def upstream(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "upstream", value)


@pulumi.input_type
class _DnsBlockListState:
    def __init__(__self__, *,
                 last_updated: Optional[pulumi.Input[str]] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 override_to_allows: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 upstream: Optional[pulumi.Input[str]] = None):
        """
        Input properties used for looking up and filtering DnsBlockList resources.
        :param pulumi.Input[str] name: The human readable name of the block list.
        :param pulumi.Input[Sequence[pulumi.Input[str]]] override_to_allows: Optional list of DNS names to exclude from any retrieved DNS block lists.
        :param pulumi.Input[str] upstream: An upstream URL that returns a DNS block list.
        """
        if last_updated is not None:
            pulumi.set(__self__, "last_updated", last_updated)
        if name is not None:
            pulumi.set(__self__, "name", name)
        if override_to_allows is not None:
            pulumi.set(__self__, "override_to_allows", override_to_allows)
        if upstream is not None:
            pulumi.set(__self__, "upstream", upstream)

    @property
    @pulumi.getter(name="lastUpdated")
    def last_updated(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "last_updated")

    @last_updated.setter
    def last_updated(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "last_updated", value)

    @property
    @pulumi.getter
    def name(self) -> Optional[pulumi.Input[str]]:
        """
        The human readable name of the block list.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "name", value)

    @property
    @pulumi.getter(name="overrideToAllows")
    def override_to_allows(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]:
        """
        Optional list of DNS names to exclude from any retrieved DNS block lists.
        """
        return pulumi.get(self, "override_to_allows")

    @override_to_allows.setter
    def override_to_allows(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]):
        pulumi.set(self, "override_to_allows", value)

    @property
    @pulumi.getter
    def upstream(self) -> Optional[pulumi.Input[str]]:
        """
        An upstream URL that returns a DNS block list.
        """
        return pulumi.get(self, "upstream")

    @upstream.setter
    def upstream(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "upstream", value)


class DnsBlockList(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 override_to_allows: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 upstream: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        Create a DnsBlockList resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] name: The human readable name of the block list.
        :param pulumi.Input[Sequence[pulumi.Input[str]]] override_to_allows: Optional list of DNS names to exclude from any retrieved DNS block lists.
        :param pulumi.Input[str] upstream: An upstream URL that returns a DNS block list.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[DnsBlockListArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a DnsBlockList resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param DnsBlockListArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(DnsBlockListArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 name: Optional[pulumi.Input[str]] = None,
                 override_to_allows: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
                 upstream: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = DnsBlockListArgs.__new__(DnsBlockListArgs)

            __props__.__dict__["name"] = name
            __props__.__dict__["override_to_allows"] = override_to_allows
            __props__.__dict__["upstream"] = upstream
            __props__.__dict__["last_updated"] = None
        super(DnsBlockList, __self__).__init__(
            'bowtie:index/dnsBlockList:DnsBlockList',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            last_updated: Optional[pulumi.Input[str]] = None,
            name: Optional[pulumi.Input[str]] = None,
            override_to_allows: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None,
            upstream: Optional[pulumi.Input[str]] = None) -> 'DnsBlockList':
        """
        Get an existing DnsBlockList resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] name: The human readable name of the block list.
        :param pulumi.Input[Sequence[pulumi.Input[str]]] override_to_allows: Optional list of DNS names to exclude from any retrieved DNS block lists.
        :param pulumi.Input[str] upstream: An upstream URL that returns a DNS block list.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _DnsBlockListState.__new__(_DnsBlockListState)

        __props__.__dict__["last_updated"] = last_updated
        __props__.__dict__["name"] = name
        __props__.__dict__["override_to_allows"] = override_to_allows
        __props__.__dict__["upstream"] = upstream
        return DnsBlockList(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter(name="lastUpdated")
    def last_updated(self) -> pulumi.Output[str]:
        return pulumi.get(self, "last_updated")

    @property
    @pulumi.getter
    def name(self) -> pulumi.Output[str]:
        """
        The human readable name of the block list.
        """
        return pulumi.get(self, "name")

    @property
    @pulumi.getter(name="overrideToAllows")
    def override_to_allows(self) -> pulumi.Output[Optional[Sequence[str]]]:
        """
        Optional list of DNS names to exclude from any retrieved DNS block lists.
        """
        return pulumi.get(self, "override_to_allows")

    @property
    @pulumi.getter
    def upstream(self) -> pulumi.Output[Optional[str]]:
        """
        An upstream URL that returns a DNS block list.
        """
        return pulumi.get(self, "upstream")

