# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['OrgConfigArgs', 'OrgConfig']

@pulumi.input_type
class OrgConfigArgs:
    def __init__(__self__, *,
                 allow_controller_approval_with_psk_only: Optional[pulumi.Input[bool]] = None,
                 allow_device_approval_on_user_auth: Optional[pulumi.Input[bool]] = None,
                 controller_ssh_listener: Optional[pulumi.Input[str]] = None,
                 controller_version_include_prereleases: Optional[pulumi.Input[bool]] = None,
                 controller_version_minimum_age: Optional[pulumi.Input[int]] = None,
                 controller_version_splay_type: Optional[pulumi.Input[str]] = None,
                 controller_version_splay_value: Optional[pulumi.Input[str]] = None,
                 controller_version_strategy_type: Optional[pulumi.Input[str]] = None,
                 controller_version_strategy_value: Optional[pulumi.Input[str]] = None,
                 delete_devices_more_stale_than_days: Optional[pulumi.Input[int]] = None,
                 disable_peers_require_quorum: Optional[pulumi.Input[bool]] = None,
                 peers_require_quorum_percentage: Optional[pulumi.Input[int]] = None,
                 remove_approval_devices_more_stale_than_days: Optional[pulumi.Input[int]] = None,
                 user_device_disassociation_minutes: Optional[pulumi.Input[int]] = None):
        """
        The set of arguments for constructing a OrgConfig resource.
        :param pulumi.Input[bool] allow_controller_approval_with_psk_only: Automatically admit a Controller that presents a valid pre-shared key, for zero-touch cluster scale-out.
        :param pulumi.Input[bool] allow_device_approval_on_user_auth: Automatically approve a device when its user authenticates after installing the client.
        :param pulumi.Input[str] controller_ssh_listener: Organization default for how Controllers listen on the SSH port: `any`, `local-only`, or `tunnel-only`.
        :param pulumi.Input[bool] controller_version_include_prereleases: Default for considering pre-release versions when Controllers do not specify their own value.
        :param pulumi.Input[int] controller_version_minimum_age: Default minimum age, in days, a release must have before adoption under a latest-version strategy.
        :param pulumi.Input[str] controller_version_splay_type: Organization default update stagger: `no-delay`, `randomized-delay`, or `consistent-randomized-delay`.
        :param pulumi.Input[str] controller_version_splay_value: A systemd time-span for `randomized-delay` and `consistent-randomized-delay`.
        :param pulumi.Input[str] controller_version_strategy_type: Organization default update strategy: `manual`, `specific`, `newest-at-interval`, or `newest-at-calendar`.
               (`org-default` is not valid here; the organization default cannot itself defer to the organization default.)
        :param pulumi.Input[str] controller_version_strategy_value: Value for the default update strategy when it requires one (a version, time-span, or calendar expression).
        :param pulumi.Input[int] delete_devices_more_stale_than_days: Delete devices that have not checked in for more than this many days. Must be greater than 7.
        :param pulumi.Input[bool] disable_peers_require_quorum: When false, destructive device cleanup only proceeds when a quorum of Controller peers is connected.
        :param pulumi.Input[int] peers_require_quorum_percentage: Percentage (0-100) of Controller peers required for quorum. Default 51.
        :param pulumi.Input[int] remove_approval_devices_more_stale_than_days: Revoke approval for devices that have not checked in for more than this many days. Must be greater than 7.
        :param pulumi.Input[int] user_device_disassociation_minutes: Disassociate a device from its user after this many minutes.
        """
        if allow_controller_approval_with_psk_only is not None:
            pulumi.set(__self__, "allow_controller_approval_with_psk_only", allow_controller_approval_with_psk_only)
        if allow_device_approval_on_user_auth is not None:
            pulumi.set(__self__, "allow_device_approval_on_user_auth", allow_device_approval_on_user_auth)
        if controller_ssh_listener is not None:
            pulumi.set(__self__, "controller_ssh_listener", controller_ssh_listener)
        if controller_version_include_prereleases is not None:
            pulumi.set(__self__, "controller_version_include_prereleases", controller_version_include_prereleases)
        if controller_version_minimum_age is not None:
            pulumi.set(__self__, "controller_version_minimum_age", controller_version_minimum_age)
        if controller_version_splay_type is not None:
            pulumi.set(__self__, "controller_version_splay_type", controller_version_splay_type)
        if controller_version_splay_value is not None:
            pulumi.set(__self__, "controller_version_splay_value", controller_version_splay_value)
        if controller_version_strategy_type is not None:
            pulumi.set(__self__, "controller_version_strategy_type", controller_version_strategy_type)
        if controller_version_strategy_value is not None:
            pulumi.set(__self__, "controller_version_strategy_value", controller_version_strategy_value)
        if delete_devices_more_stale_than_days is not None:
            pulumi.set(__self__, "delete_devices_more_stale_than_days", delete_devices_more_stale_than_days)
        if disable_peers_require_quorum is not None:
            pulumi.set(__self__, "disable_peers_require_quorum", disable_peers_require_quorum)
        if peers_require_quorum_percentage is not None:
            pulumi.set(__self__, "peers_require_quorum_percentage", peers_require_quorum_percentage)
        if remove_approval_devices_more_stale_than_days is not None:
            pulumi.set(__self__, "remove_approval_devices_more_stale_than_days", remove_approval_devices_more_stale_than_days)
        if user_device_disassociation_minutes is not None:
            pulumi.set(__self__, "user_device_disassociation_minutes", user_device_disassociation_minutes)

    @property
    @pulumi.getter(name="allowControllerApprovalWithPskOnly")
    def allow_controller_approval_with_psk_only(self) -> Optional[pulumi.Input[bool]]:
        """
        Automatically admit a Controller that presents a valid pre-shared key, for zero-touch cluster scale-out.
        """
        return pulumi.get(self, "allow_controller_approval_with_psk_only")

    @allow_controller_approval_with_psk_only.setter
    def allow_controller_approval_with_psk_only(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "allow_controller_approval_with_psk_only", value)

    @property
    @pulumi.getter(name="allowDeviceApprovalOnUserAuth")
    def allow_device_approval_on_user_auth(self) -> Optional[pulumi.Input[bool]]:
        """
        Automatically approve a device when its user authenticates after installing the client.
        """
        return pulumi.get(self, "allow_device_approval_on_user_auth")

    @allow_device_approval_on_user_auth.setter
    def allow_device_approval_on_user_auth(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "allow_device_approval_on_user_auth", value)

    @property
    @pulumi.getter(name="controllerSshListener")
    def controller_ssh_listener(self) -> Optional[pulumi.Input[str]]:
        """
        Organization default for how Controllers listen on the SSH port: `any`, `local-only`, or `tunnel-only`.
        """
        return pulumi.get(self, "controller_ssh_listener")

    @controller_ssh_listener.setter
    def controller_ssh_listener(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "controller_ssh_listener", value)

    @property
    @pulumi.getter(name="controllerVersionIncludePrereleases")
    def controller_version_include_prereleases(self) -> Optional[pulumi.Input[bool]]:
        """
        Default for considering pre-release versions when Controllers do not specify their own value.
        """
        return pulumi.get(self, "controller_version_include_prereleases")

    @controller_version_include_prereleases.setter
    def controller_version_include_prereleases(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "controller_version_include_prereleases", value)

    @property
    @pulumi.getter(name="controllerVersionMinimumAge")
    def controller_version_minimum_age(self) -> Optional[pulumi.Input[int]]:
        """
        Default minimum age, in days, a release must have before adoption under a latest-version strategy.
        """
        return pulumi.get(self, "controller_version_minimum_age")

    @controller_version_minimum_age.setter
    def controller_version_minimum_age(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "controller_version_minimum_age", value)

    @property
    @pulumi.getter(name="controllerVersionSplayType")
    def controller_version_splay_type(self) -> Optional[pulumi.Input[str]]:
        """
        Organization default update stagger: `no-delay`, `randomized-delay`, or `consistent-randomized-delay`.
        """
        return pulumi.get(self, "controller_version_splay_type")

    @controller_version_splay_type.setter
    def controller_version_splay_type(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "controller_version_splay_type", value)

    @property
    @pulumi.getter(name="controllerVersionSplayValue")
    def controller_version_splay_value(self) -> Optional[pulumi.Input[str]]:
        """
        A systemd time-span for `randomized-delay` and `consistent-randomized-delay`.
        """
        return pulumi.get(self, "controller_version_splay_value")

    @controller_version_splay_value.setter
    def controller_version_splay_value(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "controller_version_splay_value", value)

    @property
    @pulumi.getter(name="controllerVersionStrategyType")
    def controller_version_strategy_type(self) -> Optional[pulumi.Input[str]]:
        """
        Organization default update strategy: `manual`, `specific`, `newest-at-interval`, or `newest-at-calendar`.
        (`org-default` is not valid here; the organization default cannot itself defer to the organization default.)
        """
        return pulumi.get(self, "controller_version_strategy_type")

    @controller_version_strategy_type.setter
    def controller_version_strategy_type(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "controller_version_strategy_type", value)

    @property
    @pulumi.getter(name="controllerVersionStrategyValue")
    def controller_version_strategy_value(self) -> Optional[pulumi.Input[str]]:
        """
        Value for the default update strategy when it requires one (a version, time-span, or calendar expression).
        """
        return pulumi.get(self, "controller_version_strategy_value")

    @controller_version_strategy_value.setter
    def controller_version_strategy_value(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "controller_version_strategy_value", value)

    @property
    @pulumi.getter(name="deleteDevicesMoreStaleThanDays")
    def delete_devices_more_stale_than_days(self) -> Optional[pulumi.Input[int]]:
        """
        Delete devices that have not checked in for more than this many days. Must be greater than 7.
        """
        return pulumi.get(self, "delete_devices_more_stale_than_days")

    @delete_devices_more_stale_than_days.setter
    def delete_devices_more_stale_than_days(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "delete_devices_more_stale_than_days", value)

    @property
    @pulumi.getter(name="disablePeersRequireQuorum")
    def disable_peers_require_quorum(self) -> Optional[pulumi.Input[bool]]:
        """
        When false, destructive device cleanup only proceeds when a quorum of Controller peers is connected.
        """
        return pulumi.get(self, "disable_peers_require_quorum")

    @disable_peers_require_quorum.setter
    def disable_peers_require_quorum(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "disable_peers_require_quorum", value)

    @property
    @pulumi.getter(name="peersRequireQuorumPercentage")
    def peers_require_quorum_percentage(self) -> Optional[pulumi.Input[int]]:
        """
        Percentage (0-100) of Controller peers required for quorum. Default 51.
        """
        return pulumi.get(self, "peers_require_quorum_percentage")

    @peers_require_quorum_percentage.setter
    def peers_require_quorum_percentage(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "peers_require_quorum_percentage", value)

    @property
    @pulumi.getter(name="removeApprovalDevicesMoreStaleThanDays")
    def remove_approval_devices_more_stale_than_days(self) -> Optional[pulumi.Input[int]]:
        """
        Revoke approval for devices that have not checked in for more than this many days. Must be greater than 7.
        """
        return pulumi.get(self, "remove_approval_devices_more_stale_than_days")

    @remove_approval_devices_more_stale_than_days.setter
    def remove_approval_devices_more_stale_than_days(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "remove_approval_devices_more_stale_than_days", value)

    @property
    @pulumi.getter(name="userDeviceDisassociationMinutes")
    def user_device_disassociation_minutes(self) -> Optional[pulumi.Input[int]]:
        """
        Disassociate a device from its user after this many minutes.
        """
        return pulumi.get(self, "user_device_disassociation_minutes")

    @user_device_disassociation_minutes.setter
    def user_device_disassociation_minutes(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "user_device_disassociation_minutes", value)


@pulumi.input_type
class _OrgConfigState:
    def __init__(__self__, *,
                 allow_controller_approval_with_psk_only: Optional[pulumi.Input[bool]] = None,
                 allow_device_approval_on_user_auth: Optional[pulumi.Input[bool]] = None,
                 controller_ssh_listener: Optional[pulumi.Input[str]] = None,
                 controller_version_include_prereleases: Optional[pulumi.Input[bool]] = None,
                 controller_version_minimum_age: Optional[pulumi.Input[int]] = None,
                 controller_version_splay_type: Optional[pulumi.Input[str]] = None,
                 controller_version_splay_value: Optional[pulumi.Input[str]] = None,
                 controller_version_strategy_type: Optional[pulumi.Input[str]] = None,
                 controller_version_strategy_value: Optional[pulumi.Input[str]] = None,
                 delete_devices_more_stale_than_days: Optional[pulumi.Input[int]] = None,
                 disable_peers_require_quorum: Optional[pulumi.Input[bool]] = None,
                 last_updated: Optional[pulumi.Input[str]] = None,
                 peers_require_quorum_percentage: Optional[pulumi.Input[int]] = None,
                 remove_approval_devices_more_stale_than_days: Optional[pulumi.Input[int]] = None,
                 user_device_disassociation_minutes: Optional[pulumi.Input[int]] = None):
        """
        Input properties used for looking up and filtering OrgConfig resources.
        :param pulumi.Input[bool] allow_controller_approval_with_psk_only: Automatically admit a Controller that presents a valid pre-shared key, for zero-touch cluster scale-out.
        :param pulumi.Input[bool] allow_device_approval_on_user_auth: Automatically approve a device when its user authenticates after installing the client.
        :param pulumi.Input[str] controller_ssh_listener: Organization default for how Controllers listen on the SSH port: `any`, `local-only`, or `tunnel-only`.
        :param pulumi.Input[bool] controller_version_include_prereleases: Default for considering pre-release versions when Controllers do not specify their own value.
        :param pulumi.Input[int] controller_version_minimum_age: Default minimum age, in days, a release must have before adoption under a latest-version strategy.
        :param pulumi.Input[str] controller_version_splay_type: Organization default update stagger: `no-delay`, `randomized-delay`, or `consistent-randomized-delay`.
        :param pulumi.Input[str] controller_version_splay_value: A systemd time-span for `randomized-delay` and `consistent-randomized-delay`.
        :param pulumi.Input[str] controller_version_strategy_type: Organization default update strategy: `manual`, `specific`, `newest-at-interval`, or `newest-at-calendar`.
               (`org-default` is not valid here; the organization default cannot itself defer to the organization default.)
        :param pulumi.Input[str] controller_version_strategy_value: Value for the default update strategy when it requires one (a version, time-span, or calendar expression).
        :param pulumi.Input[int] delete_devices_more_stale_than_days: Delete devices that have not checked in for more than this many days. Must be greater than 7.
        :param pulumi.Input[bool] disable_peers_require_quorum: When false, destructive device cleanup only proceeds when a quorum of Controller peers is connected.
        :param pulumi.Input[int] peers_require_quorum_percentage: Percentage (0-100) of Controller peers required for quorum. Default 51.
        :param pulumi.Input[int] remove_approval_devices_more_stale_than_days: Revoke approval for devices that have not checked in for more than this many days. Must be greater than 7.
        :param pulumi.Input[int] user_device_disassociation_minutes: Disassociate a device from its user after this many minutes.
        """
        if allow_controller_approval_with_psk_only is not None:
            pulumi.set(__self__, "allow_controller_approval_with_psk_only", allow_controller_approval_with_psk_only)
        if allow_device_approval_on_user_auth is not None:
            pulumi.set(__self__, "allow_device_approval_on_user_auth", allow_device_approval_on_user_auth)
        if controller_ssh_listener is not None:
            pulumi.set(__self__, "controller_ssh_listener", controller_ssh_listener)
        if controller_version_include_prereleases is not None:
            pulumi.set(__self__, "controller_version_include_prereleases", controller_version_include_prereleases)
        if controller_version_minimum_age is not None:
            pulumi.set(__self__, "controller_version_minimum_age", controller_version_minimum_age)
        if controller_version_splay_type is not None:
            pulumi.set(__self__, "controller_version_splay_type", controller_version_splay_type)
        if controller_version_splay_value is not None:
            pulumi.set(__self__, "controller_version_splay_value", controller_version_splay_value)
        if controller_version_strategy_type is not None:
            pulumi.set(__self__, "controller_version_strategy_type", controller_version_strategy_type)
        if controller_version_strategy_value is not None:
            pulumi.set(__self__, "controller_version_strategy_value", controller_version_strategy_value)
        if delete_devices_more_stale_than_days is not None:
            pulumi.set(__self__, "delete_devices_more_stale_than_days", delete_devices_more_stale_than_days)
        if disable_peers_require_quorum is not None:
            pulumi.set(__self__, "disable_peers_require_quorum", disable_peers_require_quorum)
        if last_updated is not None:
            pulumi.set(__self__, "last_updated", last_updated)
        if peers_require_quorum_percentage is not None:
            pulumi.set(__self__, "peers_require_quorum_percentage", peers_require_quorum_percentage)
        if remove_approval_devices_more_stale_than_days is not None:
            pulumi.set(__self__, "remove_approval_devices_more_stale_than_days", remove_approval_devices_more_stale_than_days)
        if user_device_disassociation_minutes is not None:
            pulumi.set(__self__, "user_device_disassociation_minutes", user_device_disassociation_minutes)

    @property
    @pulumi.getter(name="allowControllerApprovalWithPskOnly")
    def allow_controller_approval_with_psk_only(self) -> Optional[pulumi.Input[bool]]:
        """
        Automatically admit a Controller that presents a valid pre-shared key, for zero-touch cluster scale-out.
        """
        return pulumi.get(self, "allow_controller_approval_with_psk_only")

    @allow_controller_approval_with_psk_only.setter
    def allow_controller_approval_with_psk_only(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "allow_controller_approval_with_psk_only", value)

    @property
    @pulumi.getter(name="allowDeviceApprovalOnUserAuth")
    def allow_device_approval_on_user_auth(self) -> Optional[pulumi.Input[bool]]:
        """
        Automatically approve a device when its user authenticates after installing the client.
        """
        return pulumi.get(self, "allow_device_approval_on_user_auth")

    @allow_device_approval_on_user_auth.setter
    def allow_device_approval_on_user_auth(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "allow_device_approval_on_user_auth", value)

    @property
    @pulumi.getter(name="controllerSshListener")
    def controller_ssh_listener(self) -> Optional[pulumi.Input[str]]:
        """
        Organization default for how Controllers listen on the SSH port: `any`, `local-only`, or `tunnel-only`.
        """
        return pulumi.get(self, "controller_ssh_listener")

    @controller_ssh_listener.setter
    def controller_ssh_listener(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "controller_ssh_listener", value)

    @property
    @pulumi.getter(name="controllerVersionIncludePrereleases")
    def controller_version_include_prereleases(self) -> Optional[pulumi.Input[bool]]:
        """
        Default for considering pre-release versions when Controllers do not specify their own value.
        """
        return pulumi.get(self, "controller_version_include_prereleases")

    @controller_version_include_prereleases.setter
    def controller_version_include_prereleases(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "controller_version_include_prereleases", value)

    @property
    @pulumi.getter(name="controllerVersionMinimumAge")
    def controller_version_minimum_age(self) -> Optional[pulumi.Input[int]]:
        """
        Default minimum age, in days, a release must have before adoption under a latest-version strategy.
        """
        return pulumi.get(self, "controller_version_minimum_age")

    @controller_version_minimum_age.setter
    def controller_version_minimum_age(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "controller_version_minimum_age", value)

    @property
    @pulumi.getter(name="controllerVersionSplayType")
    def controller_version_splay_type(self) -> Optional[pulumi.Input[str]]:
        """
        Organization default update stagger: `no-delay`, `randomized-delay`, or `consistent-randomized-delay`.
        """
        return pulumi.get(self, "controller_version_splay_type")

    @controller_version_splay_type.setter
    def controller_version_splay_type(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "controller_version_splay_type", value)

    @property
    @pulumi.getter(name="controllerVersionSplayValue")
    def controller_version_splay_value(self) -> Optional[pulumi.Input[str]]:
        """
        A systemd time-span for `randomized-delay` and `consistent-randomized-delay`.
        """
        return pulumi.get(self, "controller_version_splay_value")

    @controller_version_splay_value.setter
    def controller_version_splay_value(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "controller_version_splay_value", value)

    @property
    @pulumi.getter(name="controllerVersionStrategyType")
    def controller_version_strategy_type(self) -> Optional[pulumi.Input[str]]:
        """
        Organization default update strategy: `manual`, `specific`, `newest-at-interval`, or `newest-at-calendar`.
        (`org-default` is not valid here; the organization default cannot itself defer to the organization default.)
        """
        return pulumi.get(self, "controller_version_strategy_type")

    @controller_version_strategy_type.setter
    def controller_version_strategy_type(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "controller_version_strategy_type", value)

    @property
    @pulumi.getter(name="controllerVersionStrategyValue")
    def controller_version_strategy_value(self) -> Optional[pulumi.Input[str]]:
        """
        Value for the default update strategy when it requires one (a version, time-span, or calendar expression).
        """
        return pulumi.get(self, "controller_version_strategy_value")

    @controller_version_strategy_value.setter
    def controller_version_strategy_value(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "controller_version_strategy_value", value)

    @property
    @pulumi.getter(name="deleteDevicesMoreStaleThanDays")
    def delete_devices_more_stale_than_days(self) -> Optional[pulumi.Input[int]]:
        """
        Delete devices that have not checked in for more than this many days. Must be greater than 7.
        """
        return pulumi.get(self, "delete_devices_more_stale_than_days")

    @delete_devices_more_stale_than_days.setter
    def delete_devices_more_stale_than_days(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "delete_devices_more_stale_than_days", value)

    @property
    @pulumi.getter(name="disablePeersRequireQuorum")
    def disable_peers_require_quorum(self) -> Optional[pulumi.Input[bool]]:
        """
        When false, destructive device cleanup only proceeds when a quorum of Controller peers is connected.
        """
        return pulumi.get(self, "disable_peers_require_quorum")

    @disable_peers_require_quorum.setter
    def disable_peers_require_quorum(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "disable_peers_require_quorum", value)

    @property
    @pulumi.getter(name="lastUpdated")
    def last_updated(self) -> Optional[pulumi.Input[str]]:
        return pulumi.get(self, "last_updated")

    @last_updated.setter
    def last_updated(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "last_updated", value)

    @property
    @pulumi.getter(name="peersRequireQuorumPercentage")
    def peers_require_quorum_percentage(self) -> Optional[pulumi.Input[int]]:
        """
        Percentage (0-100) of Controller peers required for quorum. Default 51.
        """
        return pulumi.get(self, "peers_require_quorum_percentage")

    @peers_require_quorum_percentage.setter
    def peers_require_quorum_percentage(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "peers_require_quorum_percentage", value)

    @property
    @pulumi.getter(name="removeApprovalDevicesMoreStaleThanDays")
    def remove_approval_devices_more_stale_than_days(self) -> Optional[pulumi.Input[int]]:
        """
        Revoke approval for devices that have not checked in for more than this many days. Must be greater than 7.
        """
        return pulumi.get(self, "remove_approval_devices_more_stale_than_days")

    @remove_approval_devices_more_stale_than_days.setter
    def remove_approval_devices_more_stale_than_days(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "remove_approval_devices_more_stale_than_days", value)

    @property
    @pulumi.getter(name="userDeviceDisassociationMinutes")
    def user_device_disassociation_minutes(self) -> Optional[pulumi.Input[int]]:
        """
        Disassociate a device from its user after this many minutes.
        """
        return pulumi.get(self, "user_device_disassociation_minutes")

    @user_device_disassociation_minutes.setter
    def user_device_disassociation_minutes(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "user_device_disassociation_minutes", value)


class OrgConfig(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 allow_controller_approval_with_psk_only: Optional[pulumi.Input[bool]] = None,
                 allow_device_approval_on_user_auth: Optional[pulumi.Input[bool]] = None,
                 controller_ssh_listener: Optional[pulumi.Input[str]] = None,
                 controller_version_include_prereleases: Optional[pulumi.Input[bool]] = None,
                 controller_version_minimum_age: Optional[pulumi.Input[int]] = None,
                 controller_version_splay_type: Optional[pulumi.Input[str]] = None,
                 controller_version_splay_value: Optional[pulumi.Input[str]] = None,
                 controller_version_strategy_type: Optional[pulumi.Input[str]] = None,
                 controller_version_strategy_value: Optional[pulumi.Input[str]] = None,
                 delete_devices_more_stale_than_days: Optional[pulumi.Input[int]] = None,
                 disable_peers_require_quorum: Optional[pulumi.Input[bool]] = None,
                 peers_require_quorum_percentage: Optional[pulumi.Input[int]] = None,
                 remove_approval_devices_more_stale_than_days: Optional[pulumi.Input[int]] = None,
                 user_device_disassociation_minutes: Optional[pulumi.Input[int]] = None,
                 __props__=None):
        """
        Create a OrgConfig resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[bool] allow_controller_approval_with_psk_only: Automatically admit a Controller that presents a valid pre-shared key, for zero-touch cluster scale-out.
        :param pulumi.Input[bool] allow_device_approval_on_user_auth: Automatically approve a device when its user authenticates after installing the client.
        :param pulumi.Input[str] controller_ssh_listener: Organization default for how Controllers listen on the SSH port: `any`, `local-only`, or `tunnel-only`.
        :param pulumi.Input[bool] controller_version_include_prereleases: Default for considering pre-release versions when Controllers do not specify their own value.
        :param pulumi.Input[int] controller_version_minimum_age: Default minimum age, in days, a release must have before adoption under a latest-version strategy.
        :param pulumi.Input[str] controller_version_splay_type: Organization default update stagger: `no-delay`, `randomized-delay`, or `consistent-randomized-delay`.
        :param pulumi.Input[str] controller_version_splay_value: A systemd time-span for `randomized-delay` and `consistent-randomized-delay`.
        :param pulumi.Input[str] controller_version_strategy_type: Organization default update strategy: `manual`, `specific`, `newest-at-interval`, or `newest-at-calendar`.
               (`org-default` is not valid here; the organization default cannot itself defer to the organization default.)
        :param pulumi.Input[str] controller_version_strategy_value: Value for the default update strategy when it requires one (a version, time-span, or calendar expression).
        :param pulumi.Input[int] delete_devices_more_stale_than_days: Delete devices that have not checked in for more than this many days. Must be greater than 7.
        :param pulumi.Input[bool] disable_peers_require_quorum: When false, destructive device cleanup only proceeds when a quorum of Controller peers is connected.
        :param pulumi.Input[int] peers_require_quorum_percentage: Percentage (0-100) of Controller peers required for quorum. Default 51.
        :param pulumi.Input[int] remove_approval_devices_more_stale_than_days: Revoke approval for devices that have not checked in for more than this many days. Must be greater than 7.
        :param pulumi.Input[int] user_device_disassociation_minutes: Disassociate a device from its user after this many minutes.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[OrgConfigArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a OrgConfig resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param OrgConfigArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(OrgConfigArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 allow_controller_approval_with_psk_only: Optional[pulumi.Input[bool]] = None,
                 allow_device_approval_on_user_auth: Optional[pulumi.Input[bool]] = None,
                 controller_ssh_listener: Optional[pulumi.Input[str]] = None,
                 controller_version_include_prereleases: Optional[pulumi.Input[bool]] = None,
                 controller_version_minimum_age: Optional[pulumi.Input[int]] = None,
                 controller_version_splay_type: Optional[pulumi.Input[str]] = None,
                 controller_version_splay_value: Optional[pulumi.Input[str]] = None,
                 controller_version_strategy_type: Optional[pulumi.Input[str]] = None,
                 controller_version_strategy_value: Optional[pulumi.Input[str]] = None,
                 delete_devices_more_stale_than_days: Optional[pulumi.Input[int]] = None,
                 disable_peers_require_quorum: Optional[pulumi.Input[bool]] = None,
                 peers_require_quorum_percentage: Optional[pulumi.Input[int]] = None,
                 remove_approval_devices_more_stale_than_days: Optional[pulumi.Input[int]] = None,
                 user_device_disassociation_minutes: Optional[pulumi.Input[int]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = OrgConfigArgs.__new__(OrgConfigArgs)

            __props__.__dict__["allow_controller_approval_with_psk_only"] = allow_controller_approval_with_psk_only
            __props__.__dict__["allow_device_approval_on_user_auth"] = allow_device_approval_on_user_auth
            __props__.__dict__["controller_ssh_listener"] = controller_ssh_listener
            __props__.__dict__["controller_version_include_prereleases"] = controller_version_include_prereleases
            __props__.__dict__["controller_version_minimum_age"] = controller_version_minimum_age
            __props__.__dict__["controller_version_splay_type"] = controller_version_splay_type
            __props__.__dict__["controller_version_splay_value"] = controller_version_splay_value
            __props__.__dict__["controller_version_strategy_type"] = controller_version_strategy_type
            __props__.__dict__["controller_version_strategy_value"] = controller_version_strategy_value
            __props__.__dict__["delete_devices_more_stale_than_days"] = delete_devices_more_stale_than_days
            __props__.__dict__["disable_peers_require_quorum"] = disable_peers_require_quorum
            __props__.__dict__["peers_require_quorum_percentage"] = peers_require_quorum_percentage
            __props__.__dict__["remove_approval_devices_more_stale_than_days"] = remove_approval_devices_more_stale_than_days
            __props__.__dict__["user_device_disassociation_minutes"] = user_device_disassociation_minutes
            __props__.__dict__["last_updated"] = None
        super(OrgConfig, __self__).__init__(
            'bowtie:index/orgConfig:OrgConfig',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            allow_controller_approval_with_psk_only: Optional[pulumi.Input[bool]] = None,
            allow_device_approval_on_user_auth: Optional[pulumi.Input[bool]] = None,
            controller_ssh_listener: Optional[pulumi.Input[str]] = None,
            controller_version_include_prereleases: Optional[pulumi.Input[bool]] = None,
            controller_version_minimum_age: Optional[pulumi.Input[int]] = None,
            controller_version_splay_type: Optional[pulumi.Input[str]] = None,
            controller_version_splay_value: Optional[pulumi.Input[str]] = None,
            controller_version_strategy_type: Optional[pulumi.Input[str]] = None,
            controller_version_strategy_value: Optional[pulumi.Input[str]] = None,
            delete_devices_more_stale_than_days: Optional[pulumi.Input[int]] = None,
            disable_peers_require_quorum: Optional[pulumi.Input[bool]] = None,
            last_updated: Optional[pulumi.Input[str]] = None,
            peers_require_quorum_percentage: Optional[pulumi.Input[int]] = None,
            remove_approval_devices_more_stale_than_days: Optional[pulumi.Input[int]] = None,
            user_device_disassociation_minutes: Optional[pulumi.Input[int]] = None) -> 'OrgConfig':
        """
        Get an existing OrgConfig resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[bool] allow_controller_approval_with_psk_only: Automatically admit a Controller that presents a valid pre-shared key, for zero-touch cluster scale-out.
        :param pulumi.Input[bool] allow_device_approval_on_user_auth: Automatically approve a device when its user authenticates after installing the client.
        :param pulumi.Input[str] controller_ssh_listener: Organization default for how Controllers listen on the SSH port: `any`, `local-only`, or `tunnel-only`.
        :param pulumi.Input[bool] controller_version_include_prereleases: Default for considering pre-release versions when Controllers do not specify their own value.
        :param pulumi.Input[int] controller_version_minimum_age: Default minimum age, in days, a release must have before adoption under a latest-version strategy.
        :param pulumi.Input[str] controller_version_splay_type: Organization default update stagger: `no-delay`, `randomized-delay`, or `consistent-randomized-delay`.
        :param pulumi.Input[str] controller_version_splay_value: A systemd time-span for `randomized-delay` and `consistent-randomized-delay`.
        :param pulumi.Input[str] controller_version_strategy_type: Organization default update strategy: `manual`, `specific`, `newest-at-interval`, or `newest-at-calendar`.
               (`org-default` is not valid here; the organization default cannot itself defer to the organization default.)
        :param pulumi.Input[str] controller_version_strategy_value: Value for the default update strategy when it requires one (a version, time-span, or calendar expression).
        :param pulumi.Input[int] delete_devices_more_stale_than_days: Delete devices that have not checked in for more than this many days. Must be greater than 7.
        :param pulumi.Input[bool] disable_peers_require_quorum: When false, destructive device cleanup only proceeds when a quorum of Controller peers is connected.
        :param pulumi.Input[int] peers_require_quorum_percentage: Percentage (0-100) of Controller peers required for quorum. Default 51.
        :param pulumi.Input[int] remove_approval_devices_more_stale_than_days: Revoke approval for devices that have not checked in for more than this many days. Must be greater than 7.
        :param pulumi.Input[int] user_device_disassociation_minutes: Disassociate a device from its user after this many minutes.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _OrgConfigState.__new__(_OrgConfigState)

        __props__.__dict__["allow_controller_approval_with_psk_only"] = allow_controller_approval_with_psk_only
        __props__.__dict__["allow_device_approval_on_user_auth"] = allow_device_approval_on_user_auth
        __props__.__dict__["controller_ssh_listener"] = controller_ssh_listener
        __props__.__dict__["controller_version_include_prereleases"] = controller_version_include_prereleases
        __props__.__dict__["controller_version_minimum_age"] = controller_version_minimum_age
        __props__.__dict__["controller_version_splay_type"] = controller_version_splay_type
        __props__.__dict__["controller_version_splay_value"] = controller_version_splay_value
        __props__.__dict__["controller_version_strategy_type"] = controller_version_strategy_type
        __props__.__dict__["controller_version_strategy_value"] = controller_version_strategy_value
        __props__.__dict__["delete_devices_more_stale_than_days"] = delete_devices_more_stale_than_days
        __props__.__dict__["disable_peers_require_quorum"] = disable_peers_require_quorum
        __props__.__dict__["last_updated"] = last_updated
        __props__.__dict__["peers_require_quorum_percentage"] = peers_require_quorum_percentage
        __props__.__dict__["remove_approval_devices_more_stale_than_days"] = remove_approval_devices_more_stale_than_days
        __props__.__dict__["user_device_disassociation_minutes"] = user_device_disassociation_minutes
        return OrgConfig(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter(name="allowControllerApprovalWithPskOnly")
    def allow_controller_approval_with_psk_only(self) -> pulumi.Output[bool]:
        """
        Automatically admit a Controller that presents a valid pre-shared key, for zero-touch cluster scale-out.
        """
        return pulumi.get(self, "allow_controller_approval_with_psk_only")

    @property
    @pulumi.getter(name="allowDeviceApprovalOnUserAuth")
    def allow_device_approval_on_user_auth(self) -> pulumi.Output[bool]:
        """
        Automatically approve a device when its user authenticates after installing the client.
        """
        return pulumi.get(self, "allow_device_approval_on_user_auth")

    @property
    @pulumi.getter(name="controllerSshListener")
    def controller_ssh_listener(self) -> pulumi.Output[str]:
        """
        Organization default for how Controllers listen on the SSH port: `any`, `local-only`, or `tunnel-only`.
        """
        return pulumi.get(self, "controller_ssh_listener")

    @property
    @pulumi.getter(name="controllerVersionIncludePrereleases")
    def controller_version_include_prereleases(self) -> pulumi.Output[bool]:
        """
        Default for considering pre-release versions when Controllers do not specify their own value.
        """
        return pulumi.get(self, "controller_version_include_prereleases")

    @property
    @pulumi.getter(name="controllerVersionMinimumAge")
    def controller_version_minimum_age(self) -> pulumi.Output[int]:
        """
        Default minimum age, in days, a release must have before adoption under a latest-version strategy.
        """
        return pulumi.get(self, "controller_version_minimum_age")

    @property
    @pulumi.getter(name="controllerVersionSplayType")
    def controller_version_splay_type(self) -> pulumi.Output[str]:
        """
        Organization default update stagger: `no-delay`, `randomized-delay`, or `consistent-randomized-delay`.
        """
        return pulumi.get(self, "controller_version_splay_type")

    @property
    @pulumi.getter(name="controllerVersionSplayValue")
    def controller_version_splay_value(self) -> pulumi.Output[str]:
        """
        A systemd time-span for `randomized-delay` and `consistent-randomized-delay`.
        """
        return pulumi.get(self, "controller_version_splay_value")

    @property
    @pulumi.getter(name="controllerVersionStrategyType")
    def controller_version_strategy_type(self) -> pulumi.Output[str]:
        """
        Organization default update strategy: `manual`, `specific`, `newest-at-interval`, or `newest-at-calendar`.
        (`org-default` is not valid here; the organization default cannot itself defer to the organization default.)
        """
        return pulumi.get(self, "controller_version_strategy_type")

    @property
    @pulumi.getter(name="controllerVersionStrategyValue")
    def controller_version_strategy_value(self) -> pulumi.Output[str]:
        """
        Value for the default update strategy when it requires one (a version, time-span, or calendar expression).
        """
        return pulumi.get(self, "controller_version_strategy_value")

    @property
    @pulumi.getter(name="deleteDevicesMoreStaleThanDays")
    def delete_devices_more_stale_than_days(self) -> pulumi.Output[int]:
        """
        Delete devices that have not checked in for more than this many days. Must be greater than 7.
        """
        return pulumi.get(self, "delete_devices_more_stale_than_days")

    @property
    @pulumi.getter(name="disablePeersRequireQuorum")
    def disable_peers_require_quorum(self) -> pulumi.Output[bool]:
        """
        When false, destructive device cleanup only proceeds when a quorum of Controller peers is connected.
        """
        return pulumi.get(self, "disable_peers_require_quorum")

    @property
    @pulumi.getter(name="lastUpdated")
    def last_updated(self) -> pulumi.Output[str]:
        return pulumi.get(self, "last_updated")

    @property
    @pulumi.getter(name="peersRequireQuorumPercentage")
    def peers_require_quorum_percentage(self) -> pulumi.Output[int]:
        """
        Percentage (0-100) of Controller peers required for quorum. Default 51.
        """
        return pulumi.get(self, "peers_require_quorum_percentage")

    @property
    @pulumi.getter(name="removeApprovalDevicesMoreStaleThanDays")
    def remove_approval_devices_more_stale_than_days(self) -> pulumi.Output[int]:
        """
        Revoke approval for devices that have not checked in for more than this many days. Must be greater than 7.
        """
        return pulumi.get(self, "remove_approval_devices_more_stale_than_days")

    @property
    @pulumi.getter(name="userDeviceDisassociationMinutes")
    def user_device_disassociation_minutes(self) -> pulumi.Output[int]:
        """
        Disassociate a device from its user after this many minutes.
        """
        return pulumi.get(self, "user_device_disassociation_minutes")

