# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['PolicyArgs', 'Policy']

@pulumi.input_type
class PolicyArgs:
    def __init__(__self__, *,
                 action: pulumi.Input[str],
                 dest: pulumi.Input[str],
                 source: pulumi.Input['PolicySourceArgs'],
                 order: Optional[pulumi.Input[int]] = None,
                 status: Optional[pulumi.Input[str]] = None):
        """
        The set of arguments for constructing a Policy resource.
        :param pulumi.Input[str] action: The action to take on matching traffic: `Accept`, `Reject` (deny with feedback), or `Drop` (deny silently).
        :param pulumi.Input[str] dest: The ID of the resource group this policy controls access to.
        :param pulumi.Input['PolicySourceArgs'] source: The set of devices this policy applies to. Set exactly one of the leaf matchers (`always`, `authenticated_user`, `user`,
               `device`, `user_group`, `device_group`) or exactly one of the boolean groups (`and`, `or`, `nor`).
        :param pulumi.Input[int] order: Evaluation order of the policy. When omitted, the Controller appends the policy to the end of the list.
        :param pulumi.Input[str] status: Whether the policy is `Enabled` or `Disabled`. Defaults to `Enabled`.
        """
        pulumi.set(__self__, "action", action)
        pulumi.set(__self__, "dest", dest)
        pulumi.set(__self__, "source", source)
        if order is not None:
            pulumi.set(__self__, "order", order)
        if status is not None:
            pulumi.set(__self__, "status", status)

    @property
    @pulumi.getter
    def action(self) -> pulumi.Input[str]:
        """
        The action to take on matching traffic: `Accept`, `Reject` (deny with feedback), or `Drop` (deny silently).
        """
        return pulumi.get(self, "action")

    @action.setter
    def action(self, value: pulumi.Input[str]):
        pulumi.set(self, "action", value)

    @property
    @pulumi.getter
    def dest(self) -> pulumi.Input[str]:
        """
        The ID of the resource group this policy controls access to.
        """
        return pulumi.get(self, "dest")

    @dest.setter
    def dest(self, value: pulumi.Input[str]):
        pulumi.set(self, "dest", value)

    @property
    @pulumi.getter
    def source(self) -> pulumi.Input['PolicySourceArgs']:
        """
        The set of devices this policy applies to. Set exactly one of the leaf matchers (`always`, `authenticated_user`, `user`,
        `device`, `user_group`, `device_group`) or exactly one of the boolean groups (`and`, `or`, `nor`).
        """
        return pulumi.get(self, "source")

    @source.setter
    def source(self, value: pulumi.Input['PolicySourceArgs']):
        pulumi.set(self, "source", value)

    @property
    @pulumi.getter
    def order(self) -> Optional[pulumi.Input[int]]:
        """
        Evaluation order of the policy. When omitted, the Controller appends the policy to the end of the list.
        """
        return pulumi.get(self, "order")

    @order.setter
    def order(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "order", value)

    @property
    @pulumi.getter
    def status(self) -> Optional[pulumi.Input[str]]:
        """
        Whether the policy is `Enabled` or `Disabled`. Defaults to `Enabled`.
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "status", value)


@pulumi.input_type
class _PolicyState:
    def __init__(__self__, *,
                 action: Optional[pulumi.Input[str]] = None,
                 dest: Optional[pulumi.Input[str]] = None,
                 order: Optional[pulumi.Input[int]] = None,
                 source: Optional[pulumi.Input['PolicySourceArgs']] = None,
                 status: Optional[pulumi.Input[str]] = None):
        """
        Input properties used for looking up and filtering Policy resources.
        :param pulumi.Input[str] action: The action to take on matching traffic: `Accept`, `Reject` (deny with feedback), or `Drop` (deny silently).
        :param pulumi.Input[str] dest: The ID of the resource group this policy controls access to.
        :param pulumi.Input[int] order: Evaluation order of the policy. When omitted, the Controller appends the policy to the end of the list.
        :param pulumi.Input['PolicySourceArgs'] source: The set of devices this policy applies to. Set exactly one of the leaf matchers (`always`, `authenticated_user`, `user`,
               `device`, `user_group`, `device_group`) or exactly one of the boolean groups (`and`, `or`, `nor`).
        :param pulumi.Input[str] status: Whether the policy is `Enabled` or `Disabled`. Defaults to `Enabled`.
        """
        if action is not None:
            pulumi.set(__self__, "action", action)
        if dest is not None:
            pulumi.set(__self__, "dest", dest)
        if order is not None:
            pulumi.set(__self__, "order", order)
        if source is not None:
            pulumi.set(__self__, "source", source)
        if status is not None:
            pulumi.set(__self__, "status", status)

    @property
    @pulumi.getter
    def action(self) -> Optional[pulumi.Input[str]]:
        """
        The action to take on matching traffic: `Accept`, `Reject` (deny with feedback), or `Drop` (deny silently).
        """
        return pulumi.get(self, "action")

    @action.setter
    def action(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "action", value)

    @property
    @pulumi.getter
    def dest(self) -> Optional[pulumi.Input[str]]:
        """
        The ID of the resource group this policy controls access to.
        """
        return pulumi.get(self, "dest")

    @dest.setter
    def dest(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "dest", value)

    @property
    @pulumi.getter
    def order(self) -> Optional[pulumi.Input[int]]:
        """
        Evaluation order of the policy. When omitted, the Controller appends the policy to the end of the list.
        """
        return pulumi.get(self, "order")

    @order.setter
    def order(self, value: Optional[pulumi.Input[int]]):
        pulumi.set(self, "order", value)

    @property
    @pulumi.getter
    def source(self) -> Optional[pulumi.Input['PolicySourceArgs']]:
        """
        The set of devices this policy applies to. Set exactly one of the leaf matchers (`always`, `authenticated_user`, `user`,
        `device`, `user_group`, `device_group`) or exactly one of the boolean groups (`and`, `or`, `nor`).
        """
        return pulumi.get(self, "source")

    @source.setter
    def source(self, value: Optional[pulumi.Input['PolicySourceArgs']]):
        pulumi.set(self, "source", value)

    @property
    @pulumi.getter
    def status(self) -> Optional[pulumi.Input[str]]:
        """
        Whether the policy is `Enabled` or `Disabled`. Defaults to `Enabled`.
        """
        return pulumi.get(self, "status")

    @status.setter
    def status(self, value: Optional[pulumi.Input[str]]):
        pulumi.set(self, "status", value)


class Policy(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 action: Optional[pulumi.Input[str]] = None,
                 dest: Optional[pulumi.Input[str]] = None,
                 order: Optional[pulumi.Input[int]] = None,
                 source: Optional[pulumi.Input[Union['PolicySourceArgs', 'PolicySourceArgsDict']]] = None,
                 status: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        """
        Create a Policy resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] action: The action to take on matching traffic: `Accept`, `Reject` (deny with feedback), or `Drop` (deny silently).
        :param pulumi.Input[str] dest: The ID of the resource group this policy controls access to.
        :param pulumi.Input[int] order: Evaluation order of the policy. When omitted, the Controller appends the policy to the end of the list.
        :param pulumi.Input[Union['PolicySourceArgs', 'PolicySourceArgsDict']] source: The set of devices this policy applies to. Set exactly one of the leaf matchers (`always`, `authenticated_user`, `user`,
               `device`, `user_group`, `device_group`) or exactly one of the boolean groups (`and`, `or`, `nor`).
        :param pulumi.Input[str] status: Whether the policy is `Enabled` or `Disabled`. Defaults to `Enabled`.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: PolicyArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a Policy resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param PolicyArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(PolicyArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 action: Optional[pulumi.Input[str]] = None,
                 dest: Optional[pulumi.Input[str]] = None,
                 order: Optional[pulumi.Input[int]] = None,
                 source: Optional[pulumi.Input[Union['PolicySourceArgs', 'PolicySourceArgsDict']]] = None,
                 status: Optional[pulumi.Input[str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = PolicyArgs.__new__(PolicyArgs)

            if action is None and not opts.urn:
                raise TypeError("Missing required property 'action'")
            __props__.__dict__["action"] = action
            if dest is None and not opts.urn:
                raise TypeError("Missing required property 'dest'")
            __props__.__dict__["dest"] = dest
            __props__.__dict__["order"] = order
            if source is None and not opts.urn:
                raise TypeError("Missing required property 'source'")
            __props__.__dict__["source"] = source
            __props__.__dict__["status"] = status
        super(Policy, __self__).__init__(
            'bowtie:index/policy:Policy',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None,
            action: Optional[pulumi.Input[str]] = None,
            dest: Optional[pulumi.Input[str]] = None,
            order: Optional[pulumi.Input[int]] = None,
            source: Optional[pulumi.Input[Union['PolicySourceArgs', 'PolicySourceArgsDict']]] = None,
            status: Optional[pulumi.Input[str]] = None) -> 'Policy':
        """
        Get an existing Policy resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[str] action: The action to take on matching traffic: `Accept`, `Reject` (deny with feedback), or `Drop` (deny silently).
        :param pulumi.Input[str] dest: The ID of the resource group this policy controls access to.
        :param pulumi.Input[int] order: Evaluation order of the policy. When omitted, the Controller appends the policy to the end of the list.
        :param pulumi.Input[Union['PolicySourceArgs', 'PolicySourceArgsDict']] source: The set of devices this policy applies to. Set exactly one of the leaf matchers (`always`, `authenticated_user`, `user`,
               `device`, `user_group`, `device_group`) or exactly one of the boolean groups (`and`, `or`, `nor`).
        :param pulumi.Input[str] status: Whether the policy is `Enabled` or `Disabled`. Defaults to `Enabled`.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = _PolicyState.__new__(_PolicyState)

        __props__.__dict__["action"] = action
        __props__.__dict__["dest"] = dest
        __props__.__dict__["order"] = order
        __props__.__dict__["source"] = source
        __props__.__dict__["status"] = status
        return Policy(resource_name, opts=opts, __props__=__props__)

    @property
    @pulumi.getter
    def action(self) -> pulumi.Output[str]:
        """
        The action to take on matching traffic: `Accept`, `Reject` (deny with feedback), or `Drop` (deny silently).
        """
        return pulumi.get(self, "action")

    @property
    @pulumi.getter
    def dest(self) -> pulumi.Output[str]:
        """
        The ID of the resource group this policy controls access to.
        """
        return pulumi.get(self, "dest")

    @property
    @pulumi.getter
    def order(self) -> pulumi.Output[int]:
        """
        Evaluation order of the policy. When omitted, the Controller appends the policy to the end of the list.
        """
        return pulumi.get(self, "order")

    @property
    @pulumi.getter
    def source(self) -> pulumi.Output['outputs.PolicySource']:
        """
        The set of devices this policy applies to. Set exactly one of the leaf matchers (`always`, `authenticated_user`, `user`,
        `device`, `user_group`, `device_group`) or exactly one of the boolean groups (`and`, `or`, `nor`).
        """
        return pulumi.get(self, "source")

    @property
    @pulumi.getter
    def status(self) -> pulumi.Output[str]:
        """
        Whether the policy is `Enabled` or `Disabled`. Defaults to `Enabled`.
        """
        return pulumi.get(self, "status")

