[[commands]]
package = "yq"

[[commands]]
package = "git"

[[commands]]
package = "go"

[[commands]]
package = "gotools"

[[commands]]
package = "gopls"

[[commands]]
package = "go-outline"

[[commands]]
package = "gopkgs"

[[commands]]
package = "gocode-gomod"

[[commands]]
package = "godef"

[[commands]]
package = "golangci-lint"

[[commands]]
package = "golint"

[[commands]]
package = "gcc"

[[commands]]
package = "just"

[[commands]]
package = "libargon2"

[[commands]]
package = "terraform"

[[commands]]
package = "vale"

[[commands]]
package = "docker-compose"

[[commands]]
package = "devshellPython"
