// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/bowtieworks/pulumi-bowtie/sdk/go/bowtie/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// A PEM-encoded CA bundle (inline contents or a path to a file) used to verify the Controller's TLS certificate, for
// Controllers issued by a private certificate authority. Honors the `BOWTIE_CA_BUNDLE` environment variable if set.
func GetCaBundle(ctx *pulumi.Context) string {
	return config.Get(ctx, "bowtie:caBundle")
}

// The Bowtie HTTP Controller endpoint. Honors the `BOWTIE_HOST` environment variable if set. Example:
// `https://bowtie.example.com`
func GetHost(ctx *pulumi.Context) string {
	return config.Get(ctx, "bowtie:host")
}

// Skip TLS certificate verification when connecting to the Controller. Honors the `BOWTIE_INSECURE` environment variable
// if set. Intended for development controllers with self-signed certificates; do not enable against production.
func GetInsecure(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "bowtie:insecure")
}
func GetLazyAuthentication(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "bowtie:lazyAuthentication")
}
func GetPassword(ctx *pulumi.Context) string {
	return config.Get(ctx, "bowtie:password")
}

// Control whether the provider will send policy resource locations using the new tagged type format or legacy format.
func GetTaggedLocations(ctx *pulumi.Context) bool {
	return config.GetBool(ctx, "bowtie:taggedLocations")
}
func GetUsername(ctx *pulumi.Context) string {
	return config.Get(ctx, "bowtie:username")
}
