package resources

import (
	"context"
	"time"

	"github.com/bowtieworks/terraform-provider-bowtie/internal/bowtie/client"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

var _ resource.Resource = &ipv6RangeResource{}
var _ resource.ResourceWithImportState = &ipv6RangeResource{}

type ipv6RangeResource struct {
	client *client.Client
}

type ipv6RangeResourceModel struct {
	ID                      types.String `tfsdk:"id"`
	LastUpdated             types.String `tfsdk:"last_updated"`
	Range                   types.String `tfsdk:"range"`
	AssignAddressesFromHere types.Bool   `tfsdk:"assign_addresses_from_here"`
}

func NewIPv6RangeResource() resource.Resource { return &ipv6RangeResource{} }

func (r *ipv6RangeResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_ipv6_range"
}

func (r *ipv6RangeResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manage an organization IPv6 address pool. Leave `range` unset to have the Controller generate a Bowtie ULA prefix. Destroying this resource deletes the range with Controller cascade behavior enabled so allocations from the pool do not block deletion.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				Computed:      true,
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"last_updated": schema.StringAttribute{
				Computed:            true,
				MarkdownDescription: "Provider metadata: the last time Terraform changed this object.",
			},
			"range": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				MarkdownDescription: "The IPv6 CIDR for the pool, for example `fd00:1:1:5678::/64`. Generated by the Controller when unset.",
				Validators: []validator.String{
					cidrPrefixValidator{version: 6},
				},
				PlanModifiers: []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"assign_addresses_from_here": schema.BoolAttribute{
				Required:            true,
				MarkdownDescription: "Whether the Controller assigns addresses to devices from this pool.",
			},
		},
	}
}

func (r *ipv6RangeResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError("Incorrect provider data", "The provider data did not resolve as *client.Client")
		return
	}
	r.client = c
}

func (r *ipv6RangeResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan ipv6RangeResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	out, err := r.client.UpsertIPv6Range(&client.OrgIPv6Range{
		Range:                   plan.Range.ValueString(),
		AssignAddressesFromHere: plan.AssignAddressesFromHere.ValueBool(),
	})
	if err != nil {
		resp.Diagnostics.AddError("Failed creating IPv6 range", err.Error())
		return
	}

	plan.ID = types.StringValue(out.ID)
	plan.Range = types.StringValue(out.Range)
	plan.LastUpdated = types.StringValue(time.Now().Format(time.RFC850))
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *ipv6RangeResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state ipv6RangeResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}

	out, err := r.client.GetIPv6Range(state.ID.ValueString())
	if err != nil {
		if isNotFoundError(err) {
			resp.Diagnostics.AddAttributeWarning(
				path.Root("id"),
				"IPv6 range not found, removing from state",
				state.ID.ValueString(),
			)
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Failed reading IPv6 range", err.Error())
		return
	}

	state.Range = types.StringValue(out.Range)
	state.AssignAddressesFromHere = types.BoolValue(out.AssignAddressesFromHere)
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *ipv6RangeResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan ipv6RangeResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}

	// Always send the existing prefix so the Controller never regenerates a new
	// one (which would renumber every device assigned from this pool). The plan
	// normally carries the prefix via UseStateForUnknown; fall back to a read if
	// it is somehow empty.
	var rangeValue string
	if !plan.Range.IsNull() && !plan.Range.IsUnknown() {
		rangeValue = plan.Range.ValueString()
	}
	if rangeValue == "" {
		current, err := r.client.GetIPv6Range(plan.ID.ValueString())
		if err != nil {
			if isNotFoundError(err) {
				resp.Diagnostics.AddAttributeWarning(
					path.Root("id"),
					"IPv6 range not found, removing from state",
					plan.ID.ValueString(),
				)
				resp.State.RemoveResource(ctx)
				return
			}
			resp.Diagnostics.AddError("Failed reading IPv6 range before update", err.Error())
			return
		}
		rangeValue = current.Range
	}
	if rangeValue == "" {
		resp.Diagnostics.AddAttributeError(
			path.Root("range"),
			"Missing IPv6 range",
			"The provider could not determine the existing IPv6 prefix, so it will not update the range because the Controller would generate a new prefix.",
		)
		return
	}

	out, err := r.client.UpsertIPv6Range(&client.OrgIPv6Range{
		ID:                      plan.ID.ValueString(),
		Range:                   rangeValue,
		AssignAddressesFromHere: plan.AssignAddressesFromHere.ValueBool(),
	})
	if err != nil {
		resp.Diagnostics.AddError("Failed updating IPv6 range", err.Error())
		return
	}

	plan.Range = types.StringValue(out.Range)
	plan.LastUpdated = types.StringValue(time.Now().Format(time.RFC850))
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *ipv6RangeResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state ipv6RangeResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.client.DeleteIPv6Range(state.ID.ValueString()); err != nil {
		if isNotFoundError(err) {
			return
		}
		resp.Diagnostics.AddError("Failed deleting IPv6 range", err.Error())
	}
}

func (r *ipv6RangeResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
