// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Bowtie.Inputs
{

    public sealed class CollectionMemberLocationGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// A CIDR range.
        /// </summary>
        [Input("cidr")]
        public Input<string>? Cidr { get; set; }

        /// <summary>
        /// The ID of another collection to nest inside this one.
        /// </summary>
        [Input("collection")]
        public Input<string>? Collection { get; set; }

        /// <summary>
        /// A DNS name.
        /// </summary>
        [Input("dns")]
        public Input<string>? Dns { get; set; }

        /// <summary>
        /// A single IP address.
        /// </summary>
        [Input("ip")]
        public Input<string>? Ip { get; set; }

        public CollectionMemberLocationGetArgs()
        {
        }
        public static new CollectionMemberLocationGetArgs Empty => new CollectionMemberLocationGetArgs();
    }
}
