// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Bowtie.Inputs
{

    public sealed class DnsExcludeGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Internal resource ID.
        /// </summary>
        [Input("id")]
        public Input<string>? Id { get; set; }

        /// <summary>
        /// Name to exclude sending to the upstream server for resolution.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// Order when presented with other excluded names in the web interface
        /// </summary>
        [Input("order")]
        public Input<int>? Order { get; set; }

        public DnsExcludeGetArgs()
        {
        }
        public static new DnsExcludeGetArgs Empty => new DnsExcludeGetArgs();
    }
}
