// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Bowtie.Inputs
{

    public sealed class PolicySourceAndAndNorGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Match every device, authenticated or not.
        /// </summary>
        [Input("always")]
        public Input<bool>? Always { get; set; }

        /// <summary>
        /// Match any device attached to an authenticated user.
        /// </summary>
        [Input("authenticatedUser")]
        public Input<bool>? AuthenticatedUser { get; set; }

        /// <summary>
        /// Match a single device by ID.
        /// </summary>
        [Input("device")]
        public Input<string>? Device { get; set; }

        /// <summary>
        /// Match any device in the device group with this ID.
        /// </summary>
        [Input("deviceGroup")]
        public Input<string>? DeviceGroup { get; set; }

        /// <summary>
        /// Match a single user by ID.
        /// </summary>
        [Input("user")]
        public Input<string>? User { get; set; }

        /// <summary>
        /// Match any user in the user group with this ID.
        /// </summary>
        [Input("userGroup")]
        public Input<string>? UserGroup { get; set; }

        public PolicySourceAndAndNorGetArgs()
        {
        }
        public static new PolicySourceAndAndNorGetArgs Empty => new PolicySourceAndAndNorGetArgs();
    }
}
