// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Bowtie.Inputs
{

    public sealed class PolicySourceAndGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Match every device, authenticated or not.
        /// </summary>
        [Input("always")]
        public Input<bool>? Always { get; set; }

        [Input("ands")]
        private InputList<Inputs.PolicySourceAndAndGetArgs>? _ands;

        /// <summary>
        /// Match if all of the listed operands match. Each operand is a single matcher or a further and/or/nor group.
        /// </summary>
        public InputList<Inputs.PolicySourceAndAndGetArgs> Ands
        {
            get => _ands ?? (_ands = new InputList<Inputs.PolicySourceAndAndGetArgs>());
            set => _ands = value;
        }

        /// <summary>
        /// Match any device attached to an authenticated user.
        /// </summary>
        [Input("authenticatedUser")]
        public Input<bool>? AuthenticatedUser { get; set; }

        /// <summary>
        /// Match a single device by ID.
        /// </summary>
        [Input("device")]
        public Input<string>? Device { get; set; }

        /// <summary>
        /// Match any device in the device group with this ID.
        /// </summary>
        [Input("deviceGroup")]
        public Input<string>? DeviceGroup { get; set; }

        [Input("nors")]
        private InputList<Inputs.PolicySourceAndNorGetArgs>? _nors;

        /// <summary>
        /// Match if none of the listed operands match. Each operand is a single matcher or a further and/or/nor group.
        /// </summary>
        public InputList<Inputs.PolicySourceAndNorGetArgs> Nors
        {
            get => _nors ?? (_nors = new InputList<Inputs.PolicySourceAndNorGetArgs>());
            set => _nors = value;
        }

        [Input("ors")]
        private InputList<Inputs.PolicySourceAndOrGetArgs>? _ors;

        /// <summary>
        /// Match if at least one of the listed operands match. Each operand is a single matcher or a further and/or/nor group.
        /// </summary>
        public InputList<Inputs.PolicySourceAndOrGetArgs> Ors
        {
            get => _ors ?? (_ors = new InputList<Inputs.PolicySourceAndOrGetArgs>());
            set => _ors = value;
        }

        /// <summary>
        /// Match a single user by ID.
        /// </summary>
        [Input("user")]
        public Input<string>? User { get; set; }

        /// <summary>
        /// Match any user in the user group with this ID.
        /// </summary>
        [Input("userGroup")]
        public Input<string>? UserGroup { get; set; }

        public PolicySourceAndGetArgs()
        {
        }
        public static new PolicySourceAndGetArgs Empty => new PolicySourceAndGetArgs();
    }
}
