// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Bowtie.Inputs
{

    public sealed class ResourcePortsArgs : global::Pulumi.ResourceArgs
    {
        [Input("collections")]
        private InputList<int>? _collections;

        /// <summary>
        /// List of allowed ports.
        /// </summary>
        public InputList<int> Collections
        {
            get => _collections ?? (_collections = new InputList<int>());
            set => _collections = value;
        }

        [Input("ranges")]
        private InputList<int>? _ranges;

        /// <summary>
        /// First element is the low port and second is the high port (range is inclusive).
        /// </summary>
        public InputList<int> Ranges
        {
            get => _ranges ?? (_ranges = new InputList<int>());
            set => _ranges = value;
        }

        public ResourcePortsArgs()
        {
        }
        public static new ResourcePortsArgs Empty => new ResourcePortsArgs();
    }
}
