// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Immutable;

namespace Pulumi.Bowtie
{
    public static class Config
    {
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "IDE1006", Justification = 
        "Double underscore prefix used to avoid conflicts with variable names.")]
        private sealed class __Value<T>
        {
            private readonly Func<T> _getter;
            private T _value = default!;
            private bool _set;

            public __Value(Func<T> getter)
            {
                _getter = getter;
            }

            public T Get() => _set ? _value : _getter();

            public void Set(T value)
            {
                _value = value;
                _set = true;
            }
        }

        private static readonly global::Pulumi.Config __config = new global::Pulumi.Config("bowtie");

        private static readonly __Value<string?> _caBundle = new __Value<string?>(() => __config.Get("caBundle"));
        /// <summary>
        /// A PEM-encoded CA bundle (inline contents or a path to a file) used to verify the Controller's TLS certificate, for
        /// Controllers issued by a private certificate authority. Honors the `BOWTIE_CA_BUNDLE` environment variable if set.
        /// </summary>
        public static string? CaBundle
        {
            get => _caBundle.Get();
            set => _caBundle.Set(value);
        }

        private static readonly __Value<string?> _host = new __Value<string?>(() => __config.Get("host"));
        /// <summary>
        /// The Bowtie HTTP Controller endpoint. Honors the `BOWTIE_HOST` environment variable if set. Example:
        /// `https://bowtie.example.com`
        /// </summary>
        public static string? Host
        {
            get => _host.Get();
            set => _host.Set(value);
        }

        private static readonly __Value<bool?> _insecure = new __Value<bool?>(() => __config.GetBoolean("insecure"));
        /// <summary>
        /// Skip TLS certificate verification when connecting to the Controller. Honors the `BOWTIE_INSECURE` environment variable
        /// if set. Intended for development controllers with self-signed certificates; do not enable against production.
        /// </summary>
        public static bool? Insecure
        {
            get => _insecure.Get();
            set => _insecure.Set(value);
        }

        private static readonly __Value<bool?> _lazyAuthentication = new __Value<bool?>(() => __config.GetBoolean("lazyAuthentication"));
        public static bool? LazyAuthentication
        {
            get => _lazyAuthentication.Get();
            set => _lazyAuthentication.Set(value);
        }

        private static readonly __Value<string?> _password = new __Value<string?>(() => __config.Get("password"));
        public static string? Password
        {
            get => _password.Get();
            set => _password.Set(value);
        }

        private static readonly __Value<bool?> _taggedLocations = new __Value<bool?>(() => __config.GetBoolean("taggedLocations"));
        /// <summary>
        /// Control whether the provider will send policy resource locations using the new tagged type format or legacy format.
        /// </summary>
        public static bool? TaggedLocations
        {
            get => _taggedLocations.Get();
            set => _taggedLocations.Set(value);
        }

        private static readonly __Value<string?> _username = new __Value<string?>(() => __config.Get("username"));
        public static string? Username
        {
            get => _username.Get();
            set => _username.Set(value);
        }

    }
}
