// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Bowtie.Outputs
{

    [OutputType]
    public sealed class CollectionMember
    {
        /// <summary>
        /// An optional comment describing this member.
        /// </summary>
        public readonly string? Comment;
        /// <summary>
        /// An optional RFC 3339 timestamp after which the Controller automatically removes this member.
        /// </summary>
        public readonly string? Expires;
        /// <summary>
        /// The location this member matches. Set exactly one of `ip`, `cidr`, `dns`, or `collection`.
        /// </summary>
        public readonly Outputs.CollectionMemberLocation Location;
        /// <summary>
        /// A human readable name for this member.
        /// </summary>
        public readonly string Name;

        [OutputConstructor]
        private CollectionMember(
            string? comment,

            string? expires,

            Outputs.CollectionMemberLocation location,

            string name)
        {
            Comment = comment;
            Expires = expires;
            Location = location;
            Name = name;
        }
    }
}
