// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Bowtie.Outputs
{

    [OutputType]
    public sealed class CollectionMemberLocation
    {
        /// <summary>
        /// A CIDR range.
        /// </summary>
        public readonly string? Cidr;
        /// <summary>
        /// The ID of another collection to nest inside this one.
        /// </summary>
        public readonly string? Collection;
        /// <summary>
        /// A DNS name.
        /// </summary>
        public readonly string? Dns;
        /// <summary>
        /// A single IP address.
        /// </summary>
        public readonly string? Ip;

        [OutputConstructor]
        private CollectionMemberLocation(
            string? cidr,

            string? collection,

            string? dns,

            string? ip)
        {
            Cidr = cidr;
            Collection = collection;
            Dns = dns;
            Ip = ip;
        }
    }
}
