// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Bowtie.Outputs
{

    [OutputType]
    public sealed class DnsServer
    {
        /// <summary>
        /// The IP address for this DNS server.
        /// </summary>
        public readonly string Addr;
        /// <summary>
        /// Internal resource ID.
        /// </summary>
        public readonly string? Id;
        /// <summary>
        /// The order for this DNS server.
        /// </summary>
        public readonly int? Order;

        [OutputConstructor]
        private DnsServer(
            string addr,

            string? id,

            int? order)
        {
            Addr = addr;
            Id = id;
            Order = order;
        }
    }
}
