// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Bowtie.Outputs
{

    [OutputType]
    public sealed class PolicySourceNorNor
    {
        /// <summary>
        /// Match every device, authenticated or not.
        /// </summary>
        public readonly bool? Always;
        /// <summary>
        /// Match if all of the listed operands match. Each operand is a single matcher or a further and/or/nor group.
        /// </summary>
        public readonly ImmutableArray<Outputs.PolicySourceNorNorAnd> Ands;
        /// <summary>
        /// Match any device attached to an authenticated user.
        /// </summary>
        public readonly bool? AuthenticatedUser;
        /// <summary>
        /// Match a single device by ID.
        /// </summary>
        public readonly string? Device;
        /// <summary>
        /// Match any device in the device group with this ID.
        /// </summary>
        public readonly string? DeviceGroup;
        /// <summary>
        /// Match if none of the listed operands match. Each operand is a single matcher or a further and/or/nor group.
        /// </summary>
        public readonly ImmutableArray<Outputs.PolicySourceNorNorNor> Nors;
        /// <summary>
        /// Match if at least one of the listed operands match. Each operand is a single matcher or a further and/or/nor group.
        /// </summary>
        public readonly ImmutableArray<Outputs.PolicySourceNorNorOr> Ors;
        /// <summary>
        /// Match a single user by ID.
        /// </summary>
        public readonly string? User;
        /// <summary>
        /// Match any user in the user group with this ID.
        /// </summary>
        public readonly string? UserGroup;

        [OutputConstructor]
        private PolicySourceNorNor(
            bool? always,

            ImmutableArray<Outputs.PolicySourceNorNorAnd> ands,

            bool? authenticatedUser,

            string? device,

            string? deviceGroup,

            ImmutableArray<Outputs.PolicySourceNorNorNor> nors,

            ImmutableArray<Outputs.PolicySourceNorNorOr> ors,

            string? user,

            string? userGroup)
        {
            Always = always;
            Ands = ands;
            AuthenticatedUser = authenticatedUser;
            Device = device;
            DeviceGroup = deviceGroup;
            Nors = nors;
            Ors = ors;
            User = user;
            UserGroup = userGroup;
        }
    }
}
