// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Bowtie.Outputs
{

    [OutputType]
    public sealed class ResourceLocation
    {
        /// <summary>
        /// A CIDR address reachable from behind your Bowtie Controller.
        /// </summary>
        public readonly string? Cidr;
        /// <summary>
        /// The ID of a collection whose members this resource should match. Requires the default tagged location format.
        /// </summary>
        public readonly string? Collection;
        /// <summary>
        /// A DNS name pointing to a resource reachable from behind your Bowtie Controller.
        /// </summary>
        public readonly string? Dns;
        /// <summary>
        /// The IP address of a resource reachable from behind your Bowtie Controller.
        /// </summary>
        public readonly string? Ip;

        [OutputConstructor]
        private ResourceLocation(
            string? cidr,

            string? collection,

            string? dns,

            string? ip)
        {
            Cidr = cidr;
            Collection = collection;
            Dns = dns;
            Ip = ip;
        }
    }
}
