# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

caBundle: Optional[str]
"""
A PEM-encoded CA bundle (inline contents or a path to a file) used to verify the Controller's TLS certificate, for
Controllers issued by a private certificate authority. Honors the `BOWTIE_CA_BUNDLE` environment variable if set.
"""

host: Optional[str]
"""
The Bowtie HTTP Controller endpoint. Honors the `BOWTIE_HOST` environment variable if set. Example:
`https://bowtie.example.com`
"""

insecure: Optional[bool]
"""
Skip TLS certificate verification when connecting to the Controller. Honors the `BOWTIE_INSECURE` environment variable
if set. Intended for development controllers with self-signed certificates; do not enable against production.
"""

lazyAuthentication: Optional[bool]

password: Optional[str]

taggedLocations: Optional[bool]
"""
Control whether the provider will send policy resource locations using the new tagged type format or legacy format.
"""

username: Optional[str]

