# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

import types

__config__ = pulumi.Config('bowtie')


class _ExportableConfig(types.ModuleType):
    @property
    def ca_bundle(self) -> Optional[str]:
        """
        A PEM-encoded CA bundle (inline contents or a path to a file) used to verify the Controller's TLS certificate, for
        Controllers issued by a private certificate authority. Honors the `BOWTIE_CA_BUNDLE` environment variable if set.
        """
        return __config__.get('caBundle')

    @property
    def host(self) -> Optional[str]:
        """
        The Bowtie HTTP Controller endpoint. Honors the `BOWTIE_HOST` environment variable if set. Example:
        `https://bowtie.example.com`
        """
        return __config__.get('host')

    @property
    def insecure(self) -> Optional[bool]:
        """
        Skip TLS certificate verification when connecting to the Controller. Honors the `BOWTIE_INSECURE` environment variable
        if set. Intended for development controllers with self-signed certificates; do not enable against production.
        """
        return __config__.get_bool('insecure')

    @property
    def lazy_authentication(self) -> Optional[bool]:
        return __config__.get_bool('lazyAuthentication')

    @property
    def password(self) -> Optional[str]:
        return __config__.get('password')

    @property
    def tagged_locations(self) -> Optional[bool]:
        """
        Control whether the provider will send policy resource locations using the new tagged type format or legacy format.
        """
        return __config__.get_bool('taggedLocations')

    @property
    def username(self) -> Optional[str]:
        return __config__.get('username')

