// Package bowtie defines the Pulumi bridge metadata for the Bowtie provider.
//
// The bridge wraps the existing terraform-plugin-framework provider, so it is
// regenerated from the Terraform provider: when Terraform resources are added
// or changed, re-running tfgen (see ../README.md) picks the changes up. Tokens
// are computed automatically from the Terraform resource names, so new
// bowtie_* resources are mapped without editing this file.
package bowtie

import (
	_ "embed"

	bowtieshim "github.com/bowtieworks/terraform-provider-bowtie/shim"
	pf "github.com/pulumi/pulumi-terraform-bridge/v3/pkg/pf/tfbridge"
	"github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge"
	"github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge/tokens"
)

// Version is overridden at build time via -ldflags.
var Version = "0.1.0"

// bridgeMetadata holds runtime mapping data that tfgen writes alongside the
// schema. The plugin-framework bridge requires it. It starts as an empty JSON
// object and is regenerated by tfgen on every schema build.
//
//go:embed cmd/pulumi-resource-bowtie/bridge-metadata.json
var bridgeMetadata []byte

// Provider returns the Pulumi bridge metadata for the Bowtie provider.
func Provider() tfbridge.ProviderInfo {
	info := tfbridge.ProviderInfo{
		P:            pf.ShimProvider(bowtieshim.NewProvider()),
		Name:         "bowtie",
		DisplayName:  "Bowtie",
		Publisher:    "Bowtie",
		Version:      Version,
		Description:  "A Pulumi package for managing Bowtie ZTNA resources.",
		Keywords:     []string{"pulumi", "bowtie", "ztna", "category/network"},
		License:      "Apache-2.0",
		Homepage:     "https://bowtie.works",
		Repository:   "https://github.com/bowtieworks/pulumi-bowtie",
		GitHubOrg:    "bowtieworks",
		Config:       map[string]*tfbridge.SchemaInfo{},
		MetadataInfo: tfbridge.NewProviderMetadata(bridgeMetadata),
		Resources: map[string]*tfbridge.ResourceInfo{
			// bowtie_group_membership has no "id" attribute in its Terraform
			// schema. Pulumi requires every resource to expose an id, so derive
			// it from group_id (one membership resource exists per group).
			"bowtie_group_membership": {
				ComputeID: tfbridge.DelegateIDField(
					"groupId", "bowtie", "https://github.com/bowtieworks/pulumi-bowtie",
				),
			},
		},
	}

	// Auto-map every bowtie_* Terraform resource and data source to a Pulumi
	// token in the index module. This keeps the bridge thin and regenerable.
	info.MustComputeTokens(tokens.SingleModule("bowtie_", "index", tokens.MakeStandard("bowtie")))
	info.SetAutonaming(255, "-")

	return info
}
