// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Dns extends pulumi.CustomResource {
    /**
     * Get an existing Dns resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DnsState, opts?: pulumi.CustomResourceOptions): Dns {
        return new Dns(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'bowtie:index/dns:Dns';

    /**
     * Returns true if the given object is an instance of Dns.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Dns {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Dns.__pulumiType;
    }

    /**
     * Names under this domain to exclude from resolution.
     */
    public readonly excludes!: pulumi.Output<outputs.DnsExclude[] | undefined>;
    /**
     * Limit name resolution for this domain only to these sites.
     */
    public readonly includeOnlySites!: pulumi.Output<string[] | undefined>;
    /**
     * Whether to only log metrics for this domain and not all requests.
     */
    public readonly isCounted!: pulumi.Output<boolean>;
    /**
     * Whether to resolve names using DNS64.
     */
    public readonly isDns64!: pulumi.Output<boolean>;
    /**
     * Whether to drop A record responses from requests for this domain.
     */
    public readonly isDropA!: pulumi.Output<boolean>;
    /**
     * Whether all record responses for this domain should be dropped.
     */
    public readonly isDropAll!: pulumi.Output<boolean>;
    /**
     * Whether to log all requests for names in this domain.
     */
    public readonly isLog!: pulumi.Output<boolean>;
    /**
     * Whether this domain should be treated as a search domain.
     */
    public readonly isSearchDomain!: pulumi.Output<boolean>;
    /**
     * Metadata about the last time a write API was called by this provider for this resource.
     */
    public /*out*/ readonly lastUpdated!: pulumi.Output<string>;
    /**
     * The DNS zone name you wish to target. Example: `example.com`
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * Provider Metadata storing extra API data about the upstream servers for this domain
     */
    public readonly servers!: pulumi.Output<outputs.DnsServer[]>;

    /**
     * Create a Dns resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DnsArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DnsArgs | DnsState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DnsState | undefined;
            resourceInputs["excludes"] = state ? state.excludes : undefined;
            resourceInputs["includeOnlySites"] = state ? state.includeOnlySites : undefined;
            resourceInputs["isCounted"] = state ? state.isCounted : undefined;
            resourceInputs["isDns64"] = state ? state.isDns64 : undefined;
            resourceInputs["isDropA"] = state ? state.isDropA : undefined;
            resourceInputs["isDropAll"] = state ? state.isDropAll : undefined;
            resourceInputs["isLog"] = state ? state.isLog : undefined;
            resourceInputs["isSearchDomain"] = state ? state.isSearchDomain : undefined;
            resourceInputs["lastUpdated"] = state ? state.lastUpdated : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["servers"] = state ? state.servers : undefined;
        } else {
            const args = argsOrState as DnsArgs | undefined;
            if ((!args || args.servers === undefined) && !opts.urn) {
                throw new Error("Missing required property 'servers'");
            }
            resourceInputs["excludes"] = args ? args.excludes : undefined;
            resourceInputs["includeOnlySites"] = args ? args.includeOnlySites : undefined;
            resourceInputs["isCounted"] = args ? args.isCounted : undefined;
            resourceInputs["isDns64"] = args ? args.isDns64 : undefined;
            resourceInputs["isDropA"] = args ? args.isDropA : undefined;
            resourceInputs["isDropAll"] = args ? args.isDropAll : undefined;
            resourceInputs["isLog"] = args ? args.isLog : undefined;
            resourceInputs["isSearchDomain"] = args ? args.isSearchDomain : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["servers"] = args ? args.servers : undefined;
            resourceInputs["lastUpdated"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Dns.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Dns resources.
 */
export interface DnsState {
    /**
     * Names under this domain to exclude from resolution.
     */
    excludes?: pulumi.Input<pulumi.Input<inputs.DnsExclude>[]>;
    /**
     * Limit name resolution for this domain only to these sites.
     */
    includeOnlySites?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Whether to only log metrics for this domain and not all requests.
     */
    isCounted?: pulumi.Input<boolean>;
    /**
     * Whether to resolve names using DNS64.
     */
    isDns64?: pulumi.Input<boolean>;
    /**
     * Whether to drop A record responses from requests for this domain.
     */
    isDropA?: pulumi.Input<boolean>;
    /**
     * Whether all record responses for this domain should be dropped.
     */
    isDropAll?: pulumi.Input<boolean>;
    /**
     * Whether to log all requests for names in this domain.
     */
    isLog?: pulumi.Input<boolean>;
    /**
     * Whether this domain should be treated as a search domain.
     */
    isSearchDomain?: pulumi.Input<boolean>;
    /**
     * Metadata about the last time a write API was called by this provider for this resource.
     */
    lastUpdated?: pulumi.Input<string>;
    /**
     * The DNS zone name you wish to target. Example: `example.com`
     */
    name?: pulumi.Input<string>;
    /**
     * Provider Metadata storing extra API data about the upstream servers for this domain
     */
    servers?: pulumi.Input<pulumi.Input<inputs.DnsServer>[]>;
}

/**
 * The set of arguments for constructing a Dns resource.
 */
export interface DnsArgs {
    /**
     * Names under this domain to exclude from resolution.
     */
    excludes?: pulumi.Input<pulumi.Input<inputs.DnsExclude>[]>;
    /**
     * Limit name resolution for this domain only to these sites.
     */
    includeOnlySites?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Whether to only log metrics for this domain and not all requests.
     */
    isCounted?: pulumi.Input<boolean>;
    /**
     * Whether to resolve names using DNS64.
     */
    isDns64?: pulumi.Input<boolean>;
    /**
     * Whether to drop A record responses from requests for this domain.
     */
    isDropA?: pulumi.Input<boolean>;
    /**
     * Whether all record responses for this domain should be dropped.
     */
    isDropAll?: pulumi.Input<boolean>;
    /**
     * Whether to log all requests for names in this domain.
     */
    isLog?: pulumi.Input<boolean>;
    /**
     * Whether this domain should be treated as a search domain.
     */
    isSearchDomain?: pulumi.Input<boolean>;
    /**
     * The DNS zone name you wish to target. Example: `example.com`
     */
    name?: pulumi.Input<string>;
    /**
     * Provider Metadata storing extra API data about the upstream servers for this domain
     */
    servers: pulumi.Input<pulumi.Input<inputs.DnsServer>[]>;
}
