// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class DnsBlockList extends pulumi.CustomResource {
    /**
     * Get an existing DnsBlockList resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: DnsBlockListState, opts?: pulumi.CustomResourceOptions): DnsBlockList {
        return new DnsBlockList(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'bowtie:index/dnsBlockList:DnsBlockList';

    /**
     * Returns true if the given object is an instance of DnsBlockList.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is DnsBlockList {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === DnsBlockList.__pulumiType;
    }

    public /*out*/ readonly lastUpdated!: pulumi.Output<string>;
    /**
     * The human readable name of the block list.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * Optional list of DNS names to exclude from any retrieved DNS block lists.
     */
    public readonly overrideToAllows!: pulumi.Output<string[] | undefined>;
    /**
     * An upstream URL that returns a DNS block list.
     */
    public readonly upstream!: pulumi.Output<string | undefined>;

    /**
     * Create a DnsBlockList resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: DnsBlockListArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: DnsBlockListArgs | DnsBlockListState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as DnsBlockListState | undefined;
            resourceInputs["lastUpdated"] = state ? state.lastUpdated : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["overrideToAllows"] = state ? state.overrideToAllows : undefined;
            resourceInputs["upstream"] = state ? state.upstream : undefined;
        } else {
            const args = argsOrState as DnsBlockListArgs | undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["overrideToAllows"] = args ? args.overrideToAllows : undefined;
            resourceInputs["upstream"] = args ? args.upstream : undefined;
            resourceInputs["lastUpdated"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(DnsBlockList.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering DnsBlockList resources.
 */
export interface DnsBlockListState {
    lastUpdated?: pulumi.Input<string>;
    /**
     * The human readable name of the block list.
     */
    name?: pulumi.Input<string>;
    /**
     * Optional list of DNS names to exclude from any retrieved DNS block lists.
     */
    overrideToAllows?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * An upstream URL that returns a DNS block list.
     */
    upstream?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a DnsBlockList resource.
 */
export interface DnsBlockListArgs {
    /**
     * The human readable name of the block list.
     */
    name?: pulumi.Input<string>;
    /**
     * Optional list of DNS names to exclude from any retrieved DNS block lists.
     */
    overrideToAllows?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * An upstream URL that returns a DNS block list.
     */
    upstream?: pulumi.Input<string>;
}
