// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getCollection(args: GetCollectionArgs, opts?: pulumi.InvokeOptions): Promise<GetCollectionResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("bowtie:index/getCollection:getCollection", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getCollection.
 */
export interface GetCollectionArgs {
    name: string;
}

/**
 * A collection of values returned by getCollection.
 */
export interface GetCollectionResult {
    readonly description: string;
    readonly id: string;
    readonly name: string;
}
export function getCollectionOutput(args: GetCollectionOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetCollectionResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("bowtie:index/getCollection:getCollection", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getCollection.
 */
export interface GetCollectionOutputArgs {
    name: pulumi.Input<string>;
}
