// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getDeviceGroup(args: GetDeviceGroupArgs, opts?: pulumi.InvokeOptions): Promise<GetDeviceGroupResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("bowtie:index/getDeviceGroup:getDeviceGroup", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getDeviceGroup.
 */
export interface GetDeviceGroupArgs {
    name: string;
}

/**
 * A collection of values returned by getDeviceGroup.
 */
export interface GetDeviceGroupResult {
    readonly description: string;
    readonly id: string;
    readonly name: string;
}
export function getDeviceGroupOutput(args: GetDeviceGroupOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetDeviceGroupResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("bowtie:index/getDeviceGroup:getDeviceGroup", {
        "name": args.name,
    }, opts);
}

/**
 * A collection of arguments for invoking getDeviceGroup.
 */
export interface GetDeviceGroupOutputArgs {
    name: pulumi.Input<string>;
}
