// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Ipv4Range extends pulumi.CustomResource {
    /**
     * Get an existing Ipv4Range resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: Ipv4RangeState, opts?: pulumi.CustomResourceOptions): Ipv4Range {
        return new Ipv4Range(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'bowtie:index/ipv4Range:Ipv4Range';

    /**
     * Returns true if the given object is an instance of Ipv4Range.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Ipv4Range {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Ipv4Range.__pulumiType;
    }

    /**
     * Address assignment strategy: `never`, `on-demand-assign-random`, or `always-assign-random`.
     */
    public readonly assignAddressesFromHere!: pulumi.Output<string>;
    public /*out*/ readonly lastUpdated!: pulumi.Output<string>;
    /**
     * The IPv4 CIDR for the pool, for example `192.0.2.0/24`.
     */
    public readonly range!: pulumi.Output<string>;
    /**
     * Number of addresses to skip at the start of the range before assigning.
     */
    public readonly skipFirstNAddresses!: pulumi.Output<number>;

    /**
     * Create a Ipv4Range resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: Ipv4RangeArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: Ipv4RangeArgs | Ipv4RangeState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as Ipv4RangeState | undefined;
            resourceInputs["assignAddressesFromHere"] = state ? state.assignAddressesFromHere : undefined;
            resourceInputs["lastUpdated"] = state ? state.lastUpdated : undefined;
            resourceInputs["range"] = state ? state.range : undefined;
            resourceInputs["skipFirstNAddresses"] = state ? state.skipFirstNAddresses : undefined;
        } else {
            const args = argsOrState as Ipv4RangeArgs | undefined;
            if ((!args || args.assignAddressesFromHere === undefined) && !opts.urn) {
                throw new Error("Missing required property 'assignAddressesFromHere'");
            }
            if ((!args || args.range === undefined) && !opts.urn) {
                throw new Error("Missing required property 'range'");
            }
            resourceInputs["assignAddressesFromHere"] = args ? args.assignAddressesFromHere : undefined;
            resourceInputs["range"] = args ? args.range : undefined;
            resourceInputs["skipFirstNAddresses"] = args ? args.skipFirstNAddresses : undefined;
            resourceInputs["lastUpdated"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Ipv4Range.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Ipv4Range resources.
 */
export interface Ipv4RangeState {
    /**
     * Address assignment strategy: `never`, `on-demand-assign-random`, or `always-assign-random`.
     */
    assignAddressesFromHere?: pulumi.Input<string>;
    lastUpdated?: pulumi.Input<string>;
    /**
     * The IPv4 CIDR for the pool, for example `192.0.2.0/24`.
     */
    range?: pulumi.Input<string>;
    /**
     * Number of addresses to skip at the start of the range before assigning.
     */
    skipFirstNAddresses?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a Ipv4Range resource.
 */
export interface Ipv4RangeArgs {
    /**
     * Address assignment strategy: `never`, `on-demand-assign-random`, or `always-assign-random`.
     */
    assignAddressesFromHere: pulumi.Input<string>;
    /**
     * The IPv4 CIDR for the pool, for example `192.0.2.0/24`.
     */
    range: pulumi.Input<string>;
    /**
     * Number of addresses to skip at the start of the range before assigning.
     */
    skipFirstNAddresses?: pulumi.Input<number>;
}
