// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class Ipv6Range extends pulumi.CustomResource {
    /**
     * Get an existing Ipv6Range resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: Ipv6RangeState, opts?: pulumi.CustomResourceOptions): Ipv6Range {
        return new Ipv6Range(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'bowtie:index/ipv6Range:Ipv6Range';

    /**
     * Returns true if the given object is an instance of Ipv6Range.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Ipv6Range {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Ipv6Range.__pulumiType;
    }

    /**
     * Whether the Controller assigns addresses to devices from this pool.
     */
    public readonly assignAddressesFromHere!: pulumi.Output<boolean>;
    public /*out*/ readonly lastUpdated!: pulumi.Output<string>;
    /**
     * The IPv6 CIDR for the pool, for example `fd00:1:1:5678::/64`. Generated by the Controller when unset.
     */
    public readonly range!: pulumi.Output<string>;

    /**
     * Create a Ipv6Range resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: Ipv6RangeArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: Ipv6RangeArgs | Ipv6RangeState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as Ipv6RangeState | undefined;
            resourceInputs["assignAddressesFromHere"] = state ? state.assignAddressesFromHere : undefined;
            resourceInputs["lastUpdated"] = state ? state.lastUpdated : undefined;
            resourceInputs["range"] = state ? state.range : undefined;
        } else {
            const args = argsOrState as Ipv6RangeArgs | undefined;
            if ((!args || args.assignAddressesFromHere === undefined) && !opts.urn) {
                throw new Error("Missing required property 'assignAddressesFromHere'");
            }
            resourceInputs["assignAddressesFromHere"] = args ? args.assignAddressesFromHere : undefined;
            resourceInputs["range"] = args ? args.range : undefined;
            resourceInputs["lastUpdated"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Ipv6Range.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Ipv6Range resources.
 */
export interface Ipv6RangeState {
    /**
     * Whether the Controller assigns addresses to devices from this pool.
     */
    assignAddressesFromHere?: pulumi.Input<boolean>;
    lastUpdated?: pulumi.Input<string>;
    /**
     * The IPv6 CIDR for the pool, for example `fd00:1:1:5678::/64`. Generated by the Controller when unset.
     */
    range?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Ipv6Range resource.
 */
export interface Ipv6RangeArgs {
    /**
     * Whether the Controller assigns addresses to devices from this pool.
     */
    assignAddressesFromHere: pulumi.Input<boolean>;
    /**
     * The IPv6 CIDR for the pool, for example `fd00:1:1:5678::/64`. Generated by the Controller when unset.
     */
    range?: pulumi.Input<string>;
}
