// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class OrgConfig extends pulumi.CustomResource {
    /**
     * Get an existing OrgConfig resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: OrgConfigState, opts?: pulumi.CustomResourceOptions): OrgConfig {
        return new OrgConfig(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'bowtie:index/orgConfig:OrgConfig';

    /**
     * Returns true if the given object is an instance of OrgConfig.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is OrgConfig {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === OrgConfig.__pulumiType;
    }

    /**
     * Automatically admit a Controller that presents a valid pre-shared key, for zero-touch cluster scale-out.
     */
    public readonly allowControllerApprovalWithPskOnly!: pulumi.Output<boolean>;
    /**
     * Automatically approve a device when its user authenticates after installing the client.
     */
    public readonly allowDeviceApprovalOnUserAuth!: pulumi.Output<boolean>;
    /**
     * Organization default for how Controllers listen on the SSH port: `any`, `local-only`, or `tunnel-only`.
     */
    public readonly controllerSshListener!: pulumi.Output<string>;
    /**
     * Default for considering pre-release versions when Controllers do not specify their own value.
     */
    public readonly controllerVersionIncludePrereleases!: pulumi.Output<boolean>;
    /**
     * Default minimum age, in days, a release must have before adoption under a latest-version strategy.
     */
    public readonly controllerVersionMinimumAge!: pulumi.Output<number>;
    /**
     * Organization default update stagger: `no-delay`, `randomized-delay`, or `consistent-randomized-delay`.
     */
    public readonly controllerVersionSplayType!: pulumi.Output<string>;
    /**
     * A systemd time-span for `randomized-delay` and `consistent-randomized-delay`.
     */
    public readonly controllerVersionSplayValue!: pulumi.Output<string>;
    /**
     * Organization default update strategy: `manual`, `specific`, `newest-at-interval`, or `newest-at-calendar`.
     * (`org-default` is not valid here; the organization default cannot itself defer to the organization default.)
     */
    public readonly controllerVersionStrategyType!: pulumi.Output<string>;
    /**
     * Value for the default update strategy when it requires one (a version, time-span, or calendar expression).
     */
    public readonly controllerVersionStrategyValue!: pulumi.Output<string>;
    /**
     * Delete devices that have not checked in for more than this many days. Must be greater than 7.
     */
    public readonly deleteDevicesMoreStaleThanDays!: pulumi.Output<number>;
    /**
     * When false, destructive device cleanup only proceeds when a quorum of Controller peers is connected.
     */
    public readonly disablePeersRequireQuorum!: pulumi.Output<boolean>;
    public /*out*/ readonly lastUpdated!: pulumi.Output<string>;
    /**
     * Percentage (0-100) of Controller peers required for quorum. Default 51.
     */
    public readonly peersRequireQuorumPercentage!: pulumi.Output<number>;
    /**
     * Revoke approval for devices that have not checked in for more than this many days. Must be greater than 7.
     */
    public readonly removeApprovalDevicesMoreStaleThanDays!: pulumi.Output<number>;
    /**
     * Disassociate a device from its user after this many minutes.
     */
    public readonly userDeviceDisassociationMinutes!: pulumi.Output<number>;

    /**
     * Create a OrgConfig resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: OrgConfigArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: OrgConfigArgs | OrgConfigState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as OrgConfigState | undefined;
            resourceInputs["allowControllerApprovalWithPskOnly"] = state ? state.allowControllerApprovalWithPskOnly : undefined;
            resourceInputs["allowDeviceApprovalOnUserAuth"] = state ? state.allowDeviceApprovalOnUserAuth : undefined;
            resourceInputs["controllerSshListener"] = state ? state.controllerSshListener : undefined;
            resourceInputs["controllerVersionIncludePrereleases"] = state ? state.controllerVersionIncludePrereleases : undefined;
            resourceInputs["controllerVersionMinimumAge"] = state ? state.controllerVersionMinimumAge : undefined;
            resourceInputs["controllerVersionSplayType"] = state ? state.controllerVersionSplayType : undefined;
            resourceInputs["controllerVersionSplayValue"] = state ? state.controllerVersionSplayValue : undefined;
            resourceInputs["controllerVersionStrategyType"] = state ? state.controllerVersionStrategyType : undefined;
            resourceInputs["controllerVersionStrategyValue"] = state ? state.controllerVersionStrategyValue : undefined;
            resourceInputs["deleteDevicesMoreStaleThanDays"] = state ? state.deleteDevicesMoreStaleThanDays : undefined;
            resourceInputs["disablePeersRequireQuorum"] = state ? state.disablePeersRequireQuorum : undefined;
            resourceInputs["lastUpdated"] = state ? state.lastUpdated : undefined;
            resourceInputs["peersRequireQuorumPercentage"] = state ? state.peersRequireQuorumPercentage : undefined;
            resourceInputs["removeApprovalDevicesMoreStaleThanDays"] = state ? state.removeApprovalDevicesMoreStaleThanDays : undefined;
            resourceInputs["userDeviceDisassociationMinutes"] = state ? state.userDeviceDisassociationMinutes : undefined;
        } else {
            const args = argsOrState as OrgConfigArgs | undefined;
            resourceInputs["allowControllerApprovalWithPskOnly"] = args ? args.allowControllerApprovalWithPskOnly : undefined;
            resourceInputs["allowDeviceApprovalOnUserAuth"] = args ? args.allowDeviceApprovalOnUserAuth : undefined;
            resourceInputs["controllerSshListener"] = args ? args.controllerSshListener : undefined;
            resourceInputs["controllerVersionIncludePrereleases"] = args ? args.controllerVersionIncludePrereleases : undefined;
            resourceInputs["controllerVersionMinimumAge"] = args ? args.controllerVersionMinimumAge : undefined;
            resourceInputs["controllerVersionSplayType"] = args ? args.controllerVersionSplayType : undefined;
            resourceInputs["controllerVersionSplayValue"] = args ? args.controllerVersionSplayValue : undefined;
            resourceInputs["controllerVersionStrategyType"] = args ? args.controllerVersionStrategyType : undefined;
            resourceInputs["controllerVersionStrategyValue"] = args ? args.controllerVersionStrategyValue : undefined;
            resourceInputs["deleteDevicesMoreStaleThanDays"] = args ? args.deleteDevicesMoreStaleThanDays : undefined;
            resourceInputs["disablePeersRequireQuorum"] = args ? args.disablePeersRequireQuorum : undefined;
            resourceInputs["peersRequireQuorumPercentage"] = args ? args.peersRequireQuorumPercentage : undefined;
            resourceInputs["removeApprovalDevicesMoreStaleThanDays"] = args ? args.removeApprovalDevicesMoreStaleThanDays : undefined;
            resourceInputs["userDeviceDisassociationMinutes"] = args ? args.userDeviceDisassociationMinutes : undefined;
            resourceInputs["lastUpdated"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(OrgConfig.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering OrgConfig resources.
 */
export interface OrgConfigState {
    /**
     * Automatically admit a Controller that presents a valid pre-shared key, for zero-touch cluster scale-out.
     */
    allowControllerApprovalWithPskOnly?: pulumi.Input<boolean>;
    /**
     * Automatically approve a device when its user authenticates after installing the client.
     */
    allowDeviceApprovalOnUserAuth?: pulumi.Input<boolean>;
    /**
     * Organization default for how Controllers listen on the SSH port: `any`, `local-only`, or `tunnel-only`.
     */
    controllerSshListener?: pulumi.Input<string>;
    /**
     * Default for considering pre-release versions when Controllers do not specify their own value.
     */
    controllerVersionIncludePrereleases?: pulumi.Input<boolean>;
    /**
     * Default minimum age, in days, a release must have before adoption under a latest-version strategy.
     */
    controllerVersionMinimumAge?: pulumi.Input<number>;
    /**
     * Organization default update stagger: `no-delay`, `randomized-delay`, or `consistent-randomized-delay`.
     */
    controllerVersionSplayType?: pulumi.Input<string>;
    /**
     * A systemd time-span for `randomized-delay` and `consistent-randomized-delay`.
     */
    controllerVersionSplayValue?: pulumi.Input<string>;
    /**
     * Organization default update strategy: `manual`, `specific`, `newest-at-interval`, or `newest-at-calendar`.
     * (`org-default` is not valid here; the organization default cannot itself defer to the organization default.)
     */
    controllerVersionStrategyType?: pulumi.Input<string>;
    /**
     * Value for the default update strategy when it requires one (a version, time-span, or calendar expression).
     */
    controllerVersionStrategyValue?: pulumi.Input<string>;
    /**
     * Delete devices that have not checked in for more than this many days. Must be greater than 7.
     */
    deleteDevicesMoreStaleThanDays?: pulumi.Input<number>;
    /**
     * When false, destructive device cleanup only proceeds when a quorum of Controller peers is connected.
     */
    disablePeersRequireQuorum?: pulumi.Input<boolean>;
    lastUpdated?: pulumi.Input<string>;
    /**
     * Percentage (0-100) of Controller peers required for quorum. Default 51.
     */
    peersRequireQuorumPercentage?: pulumi.Input<number>;
    /**
     * Revoke approval for devices that have not checked in for more than this many days. Must be greater than 7.
     */
    removeApprovalDevicesMoreStaleThanDays?: pulumi.Input<number>;
    /**
     * Disassociate a device from its user after this many minutes.
     */
    userDeviceDisassociationMinutes?: pulumi.Input<number>;
}

/**
 * The set of arguments for constructing a OrgConfig resource.
 */
export interface OrgConfigArgs {
    /**
     * Automatically admit a Controller that presents a valid pre-shared key, for zero-touch cluster scale-out.
     */
    allowControllerApprovalWithPskOnly?: pulumi.Input<boolean>;
    /**
     * Automatically approve a device when its user authenticates after installing the client.
     */
    allowDeviceApprovalOnUserAuth?: pulumi.Input<boolean>;
    /**
     * Organization default for how Controllers listen on the SSH port: `any`, `local-only`, or `tunnel-only`.
     */
    controllerSshListener?: pulumi.Input<string>;
    /**
     * Default for considering pre-release versions when Controllers do not specify their own value.
     */
    controllerVersionIncludePrereleases?: pulumi.Input<boolean>;
    /**
     * Default minimum age, in days, a release must have before adoption under a latest-version strategy.
     */
    controllerVersionMinimumAge?: pulumi.Input<number>;
    /**
     * Organization default update stagger: `no-delay`, `randomized-delay`, or `consistent-randomized-delay`.
     */
    controllerVersionSplayType?: pulumi.Input<string>;
    /**
     * A systemd time-span for `randomized-delay` and `consistent-randomized-delay`.
     */
    controllerVersionSplayValue?: pulumi.Input<string>;
    /**
     * Organization default update strategy: `manual`, `specific`, `newest-at-interval`, or `newest-at-calendar`.
     * (`org-default` is not valid here; the organization default cannot itself defer to the organization default.)
     */
    controllerVersionStrategyType?: pulumi.Input<string>;
    /**
     * Value for the default update strategy when it requires one (a version, time-span, or calendar expression).
     */
    controllerVersionStrategyValue?: pulumi.Input<string>;
    /**
     * Delete devices that have not checked in for more than this many days. Must be greater than 7.
     */
    deleteDevicesMoreStaleThanDays?: pulumi.Input<number>;
    /**
     * When false, destructive device cleanup only proceeds when a quorum of Controller peers is connected.
     */
    disablePeersRequireQuorum?: pulumi.Input<boolean>;
    /**
     * Percentage (0-100) of Controller peers required for quorum. Default 51.
     */
    peersRequireQuorumPercentage?: pulumi.Input<number>;
    /**
     * Revoke approval for devices that have not checked in for more than this many days. Must be greater than 7.
     */
    removeApprovalDevicesMoreStaleThanDays?: pulumi.Input<number>;
    /**
     * Disassociate a device from its user after this many minutes.
     */
    userDeviceDisassociationMinutes?: pulumi.Input<number>;
}
