// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Policy extends pulumi.CustomResource {
    /**
     * Get an existing Policy resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: PolicyState, opts?: pulumi.CustomResourceOptions): Policy {
        return new Policy(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'bowtie:index/policy:Policy';

    /**
     * Returns true if the given object is an instance of Policy.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Policy {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Policy.__pulumiType;
    }

    /**
     * The action to take on matching traffic: `Accept`, `Reject` (deny with feedback), or `Drop` (deny silently).
     */
    public readonly action!: pulumi.Output<string>;
    /**
     * The ID of the resource group this policy controls access to.
     */
    public readonly dest!: pulumi.Output<string>;
    /**
     * Evaluation order of the policy. When omitted, the Controller appends the policy to the end of the list.
     */
    public readonly order!: pulumi.Output<number>;
    /**
     * The set of devices this policy applies to. Set exactly one of the leaf matchers (`always`, `authenticatedUser`, `user`,
     * `device`, `userGroup`, `deviceGroup`) or exactly one of the boolean groups (`and`, `or`, `nor`).
     */
    public readonly source!: pulumi.Output<outputs.PolicySource>;
    /**
     * Whether the policy is `Enabled` or `Disabled`. Defaults to `Enabled`.
     */
    public readonly status!: pulumi.Output<string>;

    /**
     * Create a Policy resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PolicyArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: PolicyArgs | PolicyState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as PolicyState | undefined;
            resourceInputs["action"] = state ? state.action : undefined;
            resourceInputs["dest"] = state ? state.dest : undefined;
            resourceInputs["order"] = state ? state.order : undefined;
            resourceInputs["source"] = state ? state.source : undefined;
            resourceInputs["status"] = state ? state.status : undefined;
        } else {
            const args = argsOrState as PolicyArgs | undefined;
            if ((!args || args.action === undefined) && !opts.urn) {
                throw new Error("Missing required property 'action'");
            }
            if ((!args || args.dest === undefined) && !opts.urn) {
                throw new Error("Missing required property 'dest'");
            }
            if ((!args || args.source === undefined) && !opts.urn) {
                throw new Error("Missing required property 'source'");
            }
            resourceInputs["action"] = args ? args.action : undefined;
            resourceInputs["dest"] = args ? args.dest : undefined;
            resourceInputs["order"] = args ? args.order : undefined;
            resourceInputs["source"] = args ? args.source : undefined;
            resourceInputs["status"] = args ? args.status : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Policy.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering Policy resources.
 */
export interface PolicyState {
    /**
     * The action to take on matching traffic: `Accept`, `Reject` (deny with feedback), or `Drop` (deny silently).
     */
    action?: pulumi.Input<string>;
    /**
     * The ID of the resource group this policy controls access to.
     */
    dest?: pulumi.Input<string>;
    /**
     * Evaluation order of the policy. When omitted, the Controller appends the policy to the end of the list.
     */
    order?: pulumi.Input<number>;
    /**
     * The set of devices this policy applies to. Set exactly one of the leaf matchers (`always`, `authenticatedUser`, `user`,
     * `device`, `userGroup`, `deviceGroup`) or exactly one of the boolean groups (`and`, `or`, `nor`).
     */
    source?: pulumi.Input<inputs.PolicySource>;
    /**
     * Whether the policy is `Enabled` or `Disabled`. Defaults to `Enabled`.
     */
    status?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Policy resource.
 */
export interface PolicyArgs {
    /**
     * The action to take on matching traffic: `Accept`, `Reject` (deny with feedback), or `Drop` (deny silently).
     */
    action: pulumi.Input<string>;
    /**
     * The ID of the resource group this policy controls access to.
     */
    dest: pulumi.Input<string>;
    /**
     * Evaluation order of the policy. When omitted, the Controller appends the policy to the end of the list.
     */
    order?: pulumi.Input<number>;
    /**
     * The set of devices this policy applies to. Set exactly one of the leaf matchers (`always`, `authenticatedUser`, `user`,
     * `device`, `userGroup`, `deviceGroup`) or exactly one of the boolean groups (`and`, `or`, `nor`).
     */
    source: pulumi.Input<inputs.PolicySource>;
    /**
     * Whether the policy is `Enabled` or `Disabled`. Defaults to `Enabled`.
     */
    status?: pulumi.Input<string>;
}
