// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export class RouteExclusion extends pulumi.CustomResource {
    /**
     * Get an existing RouteExclusion resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: RouteExclusionState, opts?: pulumi.CustomResourceOptions): RouteExclusion {
        return new RouteExclusion(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'bowtie:index/routeExclusion:RouteExclusion';

    /**
     * Returns true if the given object is an instance of RouteExclusion.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is RouteExclusion {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === RouteExclusion.__pulumiType;
    }

    /**
     * Rollout strategy: `always`, `never` (staged but inactive), `percentageUserMatch`, or `percentageDeviceMatch`. Defaults
     * to `always`.
     */
    public readonly applyStrategy!: pulumi.Output<string>;
    /**
     * The match percentage (0-255, in ~0.5% increments) used when `applyStrategy` is `percentageUserMatch` or
     * `percentageDeviceMatch`.
     */
    public readonly applyStrategyPercentage!: pulumi.Output<number | undefined>;
    /**
     * The ID of the collection whose CIDR members are excluded from the tunnel. The collection must already exist.
     */
    public readonly collectionId!: pulumi.Output<string>;
    /**
     * Apply only to devices in these device group IDs.
     */
    public readonly matchOnlyDeviceGroups!: pulumi.Output<string[] | undefined>;
    /**
     * Apply only to devices with this OS: `windows`, `macos`, `linux`, `ios`, `android`, `chromeos`, `bowtie.Controller`, or
     * `unknown`. Changing or removing this recreates the exclusion.
     */
    public readonly matchOnlyDeviceOs!: pulumi.Output<string | undefined>;
    /**
     * Apply only to devices of this type: `laptop`, `desktop`, `mobile`, `server`, or `other`. Changing or removing this
     * recreates the exclusion.
     */
    public readonly matchOnlyDeviceType!: pulumi.Output<string | undefined>;
    /**
     * Apply only to devices owned by this organization ID. Changing or removing this recreates the exclusion.
     */
    public readonly matchOnlyOwnership!: pulumi.Output<string | undefined>;
    /**
     * Apply only to devices whose user is in these user group IDs.
     */
    public readonly matchOnlyUserGroups!: pulumi.Output<string[] | undefined>;
    /**
     * Human-readable name for the exclusion.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * If set, the exclusion only applies when the device's WAN IP falls within one of these CIDRs (for example, an office
     * network).
     */
    public readonly onlyIfWanMatchesCidrs!: pulumi.Output<string[] | undefined>;
    /**
     * The site IDs this exclusion applies to. Omit to apply to all sites.
     */
    public readonly sites!: pulumi.Output<string[] | undefined>;
    /**
     * A content hash of the exclusion, computed by the Controller.
     */
    public /*out*/ readonly version!: pulumi.Output<string>;

    /**
     * Create a RouteExclusion resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: RouteExclusionArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: RouteExclusionArgs | RouteExclusionState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as RouteExclusionState | undefined;
            resourceInputs["applyStrategy"] = state ? state.applyStrategy : undefined;
            resourceInputs["applyStrategyPercentage"] = state ? state.applyStrategyPercentage : undefined;
            resourceInputs["collectionId"] = state ? state.collectionId : undefined;
            resourceInputs["matchOnlyDeviceGroups"] = state ? state.matchOnlyDeviceGroups : undefined;
            resourceInputs["matchOnlyDeviceOs"] = state ? state.matchOnlyDeviceOs : undefined;
            resourceInputs["matchOnlyDeviceType"] = state ? state.matchOnlyDeviceType : undefined;
            resourceInputs["matchOnlyOwnership"] = state ? state.matchOnlyOwnership : undefined;
            resourceInputs["matchOnlyUserGroups"] = state ? state.matchOnlyUserGroups : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["onlyIfWanMatchesCidrs"] = state ? state.onlyIfWanMatchesCidrs : undefined;
            resourceInputs["sites"] = state ? state.sites : undefined;
            resourceInputs["version"] = state ? state.version : undefined;
        } else {
            const args = argsOrState as RouteExclusionArgs | undefined;
            if ((!args || args.collectionId === undefined) && !opts.urn) {
                throw new Error("Missing required property 'collectionId'");
            }
            resourceInputs["applyStrategy"] = args ? args.applyStrategy : undefined;
            resourceInputs["applyStrategyPercentage"] = args ? args.applyStrategyPercentage : undefined;
            resourceInputs["collectionId"] = args ? args.collectionId : undefined;
            resourceInputs["matchOnlyDeviceGroups"] = args ? args.matchOnlyDeviceGroups : undefined;
            resourceInputs["matchOnlyDeviceOs"] = args ? args.matchOnlyDeviceOs : undefined;
            resourceInputs["matchOnlyDeviceType"] = args ? args.matchOnlyDeviceType : undefined;
            resourceInputs["matchOnlyOwnership"] = args ? args.matchOnlyOwnership : undefined;
            resourceInputs["matchOnlyUserGroups"] = args ? args.matchOnlyUserGroups : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["onlyIfWanMatchesCidrs"] = args ? args.onlyIfWanMatchesCidrs : undefined;
            resourceInputs["sites"] = args ? args.sites : undefined;
            resourceInputs["version"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(RouteExclusion.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering RouteExclusion resources.
 */
export interface RouteExclusionState {
    /**
     * Rollout strategy: `always`, `never` (staged but inactive), `percentageUserMatch`, or `percentageDeviceMatch`. Defaults
     * to `always`.
     */
    applyStrategy?: pulumi.Input<string>;
    /**
     * The match percentage (0-255, in ~0.5% increments) used when `applyStrategy` is `percentageUserMatch` or
     * `percentageDeviceMatch`.
     */
    applyStrategyPercentage?: pulumi.Input<number>;
    /**
     * The ID of the collection whose CIDR members are excluded from the tunnel. The collection must already exist.
     */
    collectionId?: pulumi.Input<string>;
    /**
     * Apply only to devices in these device group IDs.
     */
    matchOnlyDeviceGroups?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Apply only to devices with this OS: `windows`, `macos`, `linux`, `ios`, `android`, `chromeos`, `bowtie.Controller`, or
     * `unknown`. Changing or removing this recreates the exclusion.
     */
    matchOnlyDeviceOs?: pulumi.Input<string>;
    /**
     * Apply only to devices of this type: `laptop`, `desktop`, `mobile`, `server`, or `other`. Changing or removing this
     * recreates the exclusion.
     */
    matchOnlyDeviceType?: pulumi.Input<string>;
    /**
     * Apply only to devices owned by this organization ID. Changing or removing this recreates the exclusion.
     */
    matchOnlyOwnership?: pulumi.Input<string>;
    /**
     * Apply only to devices whose user is in these user group IDs.
     */
    matchOnlyUserGroups?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Human-readable name for the exclusion.
     */
    name?: pulumi.Input<string>;
    /**
     * If set, the exclusion only applies when the device's WAN IP falls within one of these CIDRs (for example, an office
     * network).
     */
    onlyIfWanMatchesCidrs?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The site IDs this exclusion applies to. Omit to apply to all sites.
     */
    sites?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * A content hash of the exclusion, computed by the Controller.
     */
    version?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a RouteExclusion resource.
 */
export interface RouteExclusionArgs {
    /**
     * Rollout strategy: `always`, `never` (staged but inactive), `percentageUserMatch`, or `percentageDeviceMatch`. Defaults
     * to `always`.
     */
    applyStrategy?: pulumi.Input<string>;
    /**
     * The match percentage (0-255, in ~0.5% increments) used when `applyStrategy` is `percentageUserMatch` or
     * `percentageDeviceMatch`.
     */
    applyStrategyPercentage?: pulumi.Input<number>;
    /**
     * The ID of the collection whose CIDR members are excluded from the tunnel. The collection must already exist.
     */
    collectionId: pulumi.Input<string>;
    /**
     * Apply only to devices in these device group IDs.
     */
    matchOnlyDeviceGroups?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Apply only to devices with this OS: `windows`, `macos`, `linux`, `ios`, `android`, `chromeos`, `bowtie.Controller`, or
     * `unknown`. Changing or removing this recreates the exclusion.
     */
    matchOnlyDeviceOs?: pulumi.Input<string>;
    /**
     * Apply only to devices of this type: `laptop`, `desktop`, `mobile`, `server`, or `other`. Changing or removing this
     * recreates the exclusion.
     */
    matchOnlyDeviceType?: pulumi.Input<string>;
    /**
     * Apply only to devices owned by this organization ID. Changing or removing this recreates the exclusion.
     */
    matchOnlyOwnership?: pulumi.Input<string>;
    /**
     * Apply only to devices whose user is in these user group IDs.
     */
    matchOnlyUserGroups?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * Human-readable name for the exclusion.
     */
    name?: pulumi.Input<string>;
    /**
     * If set, the exclusion only applies when the device's WAN IP falls within one of these CIDRs (for example, an office
     * network).
     */
    onlyIfWanMatchesCidrs?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The site IDs this exclusion applies to. Omit to apply to all sites.
     */
    sites?: pulumi.Input<pulumi.Input<string>[]>;
}
