name: Test Suite

on:
  workflow_dispatch:

  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'

jobs:

  test:
    name: Execute tests for given target
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        test: [stale-docs stylecheck acceptance-test]
    steps:

    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Install nix
      uses: DeterminateSystems/nix-installer-action@main

    - name: Setup nix caching
      uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Run the ${{ matrix.test }} tests
      run: nix develop . --command just ${{ matrix.test }}

    - name: Run linters
      uses: golangci/golangci-lint-action@v3.7.0
      with:
        version: latest
