name: Test

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'docs/*'
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'docs/*'

jobs:

  acceptance:
    name: Acceptance Testing
    runs-on: ubuntu-latest
    steps:

    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Install nix
      uses: DeterminateSystems/nix-installer-action@main

    - name: Setup nix caching
      uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Run linters
      uses: golangci/golangci-lint-action@v3.7.0
      with:
        version: latest

    - name: Generate user documentation
      run: nix develop . --command just generate

    - name: Confirm no stale user documentation
      run: |
        git diff --compact-summary --exit-code || \
          (echo "*** Unexpected differences after code generation. Run 'just generate' and commit."; exit 1)

    - name: Build
      run: nix develop . --command just acceptance-test
