name: Test Suite

on:
  workflow_dispatch:

  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'

  # Run the test suite at the start (~9:00AM MDT) of every weekday (Mon-Fri)
  schedule:
    - cron: "0 16 * * 1-5"

jobs:

  docs-sync:
    name: Ensure that the user documentation is in-sync
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/bootstrap
    - run: nix develop . --command just stale-docs

  docs-style:
    name: Run style and spelling checks against user documentation
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/bootstrap
    - run: nix develop . --command just stylecheck

  acceptance:
    name: Run the provider tests including acceptance tests
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/bootstrap
    - run: nix develop . --command just acceptance-test

  lint:
    name: Perform go linting checks
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/bootstrap
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v3.7.0
      with:
        version: latest
